/**
 * Term aliases for fuzzy search.
 * Maps alternate spellings, abbreviations, and common variations
 * to their canonical glossary term.
 */
export const TERM_ALIASES: Record<string, string> = {
  "counter-clockwise": "counterclockwise",
  "counter clockwise": "counterclockwise",
  "prospin": "prospin",
  "antispin": "antispin",
  "pro-spin": "prospin",
  "anti-spin": "antispin",
  "type 1": "dual-shift",
  "type1": "dual-shift",
  "type 2": "shift",
  "type2": "shift",
  "type 3": "cross-shift",
  "type3": "cross-shift",
  "type 4": "dash",
  "type4": "dash",
  "type 5": "dual-dash",
  "type5": "dual-dash",
  "type 6": "static",
  "type6": "static",
  "tog-same": "together-same",
  "tog same": "together-same",
  "ts": "together-same",
  "split-opp": "split-opposite",
  "split opp": "split-opposite",
  "so": "split-opposite",
  "tog-opp": "together-opposite",
  "tog opp": "together-opposite",
  "to": "together-opposite",
  "ss": "split-same",
  "hand reversal": "hand-reversal",
  "prop reversal": "prop-reversal",
  "full reversal": "full-reversal",
  "motion type": "shift",
  "grid mode": "diamond",
  "half-dash": "hash",
  "half dash": "hash",
  "base rotation": "base-rotation",
  "interradials": "interradial",
  "conjoined": "conjoined-grid",
  "conjoined grid": "conjoined-grid",
  "rubik's cube": "rubiks-cube",
  "rubiks cube": "rubiks-cube",
  "hand path modifier": "hand-path-modifier",
  "path modifier": "hand-path-modifier",
  "+/-": "hand-path-modifier",
  "plus minus": "hand-path-modifier",
  "skew+": "skew",
  "skew-": "skew",
  "skew plus": "skew",
  "skew minus": "skew",
  "leader follower": "leader-follower",
  "leader/follower": "leader-follower",
  "cap": "caps",
  "continuous assembly pattern": "caps",
  "continuous assembly patterns": "caps",
  "beat": "step",
  "beats": "step",
  "quarter time": "quarter-time",
  "qt": "quarter-time",
  "tau dash": "tau-dash",
  "tau-": "tau-dash",
  "τ-": "tau-dash",
  "elemental": "elemental-model",
  "elements": "elemental-model",
  "6 elements": "elemental-model",
  "six elements": "elemental-model",
  "earth element": "elemental-model",
  "water element": "elemental-model",
  "air element": "elemental-model",
  "fire element": "elemental-model",
  "sun element": "elemental-model",
  "moon element": "elemental-model",
  "sun and moon": "elemental-model",
  "half float": "half-float",
  "halffloat": "half-float",
  "hf": "half-float",
  "stuv": "symmetry-invariance",
  "s t u v": "symmetry-invariance",
  "4 letters": "symmetry-invariance",
  "four letters": "symmetry-invariance",
  "color swap": "symmetry-invariance",
  "color-swap": "symmetry-invariance",
  "invariance": "symmetry-invariance",
  "symmetry principle": "symmetry-invariance",
  "quarter same": "symmetry-invariance",
  "quarter-same": "symmetry-invariance",
  "qs": "symmetry-invariance",
} as const;

export function resolveTermAlias(term: string): string {
  const normalized = term.toLowerCase().trim();
  return TERM_ALIASES[normalized] ?? normalized;
}
