import type { FilmDirectorInput } from "../_lib/film-director-schema";
import { PropType } from "$lib/shared/pictograph/prop/domain/enums/prop-type";

export const skyIsTheLimitFilm: FilmDirectorInput = {
  version: 3,
  id: "sky-is-the-limit-r1",
  title: "Sky Is the Limit",
  brief:
    "A first directed proof that changes cast, formation, prop, effect, effort, environment, timing, and camera without inheriting the viewer settings of whoever opens it.",
  format: { width: 1920, height: 1080, fps: 30 },
  playback: { loop: true, autoplay: true },
  scenes: [
    {
      id: "autumn-fire-circle",
      title: "Autumn fire circle",
      intent:
        "Eight performers glide through one sequence with matching staffs and classic fire while the camera orbits the group.",
      durationSeconds: 10,
      location: { environmentId: "autumn", showStage: true },
      performance: {
        bpm: 78,
        formation: "circle",
        performers: [
          {
            id: "ember-1",
            avatarId: "y-bot",
            prop: PropType.STAFF,
            effect: "fire",
            effort: "glide",
          },
          {
            id: "ember-2",
            avatarId: "x-bot",
            prop: PropType.STAFF,
            effect: "fire",
            effort: "glide",
          },
          {
            id: "ember-3",
            avatarId: "ch01",
            prop: PropType.STAFF,
            effect: "fire",
            effort: "glide",
          },
          {
            id: "ember-4",
            avatarId: "y-bot",
            prop: PropType.STAFF,
            effect: "fire",
            effort: "glide",
          },
          {
            id: "ember-5",
            avatarId: "x-bot",
            prop: PropType.STAFF,
            effect: "fire",
            effort: "glide",
          },
          {
            id: "ember-6",
            avatarId: "ch01",
            prop: PropType.STAFF,
            effect: "fire",
            effort: "glide",
          },
          {
            id: "ember-7",
            avatarId: "y-bot",
            prop: PropType.STAFF,
            effect: "fire",
            effort: "glide",
          },
          {
            id: "ember-8",
            avatarId: "x-bot",
            prop: PropType.STAFF,
            effect: "fire",
            effort: "glide",
          },
        ],
      },
      effectPresets: { fire: "fire-classic" },
      effectOverrides: { fire: { intensity: 0.48, brightness: 0.28 } },
      camera: { preset: "group-orbit", orbitDegrees: 145 },
    },
    {
      id: "forest-trio",
      title: "Forest trio",
      intent:
        "A sword lead owns the foreground while two double-staff performers frame the move from behind.",
      durationSeconds: 8,
      transition: { kind: "environment-dissolve", durationSeconds: 0.9 },
      location: { environmentId: "forest", showStage: true },
      performance: {
        bpm: 92,
        formation: "custom",
        performers: [
          {
            id: "lead",
            name: "Lead",
            avatarId: "y-bot",
            prop: PropType.SWORD,
            effect: "fire",
            effort: "punch",
            position: { x: 0, z: 1.25 },
            facingDegrees: 180,
          },
          {
            id: "left-support",
            name: "Left support",
            avatarId: "x-bot",
            prop: PropType.FIRE_DOUBLE_STAFF,
            effect: "trails",
            effort: "press",
            position: { x: -1.65, z: -1.1 },
            facingDegrees: 180,
          },
          {
            id: "right-support",
            name: "Right support",
            avatarId: "ch01",
            prop: PropType.FIRE_DOUBLE_STAFF,
            effect: "trails",
            effort: "press",
            position: { x: 1.65, z: -1.1 },
            facingDegrees: 180,
          },
        ],
      },
      effectPresets: { fire: "fire-blue-flame", trails: "trail-ember" },
      effectOverrides: { fire: { intensity: 0.54, brightness: 0.35 } },
      camera: {
        preset: "hero-dolly-in",
        target: { kind: "performer", performerId: "lead", height: 1.35 },
      },
    },
    {
      id: "ocean-bubbles",
      title: "Bubbles under the ocean",
      intent:
        "Two triad and two club performers hold a stage-sized chevron underwater while a high camera settles into their level.",
      durationSeconds: 9,
      transition: { kind: "environment-dissolve", durationSeconds: 1 },
      location: { environmentId: "ocean", showStage: false },
      performance: {
        bpm: 66,
        formation: "v-shape",
        performers: [
          {
            id: "ocean-1",
            avatarId: "y-bot",
            prop: PropType.TRIAD,
            effect: "bubbles",
            effort: "glide",
          },
          {
            id: "ocean-2",
            avatarId: "x-bot",
            prop: PropType.TRIAD,
            effect: "bubbles",
            effort: "glide",
          },
          {
            id: "ocean-3",
            avatarId: "ch01",
            prop: PropType.CLUB,
            effect: "bubbles",
            effort: "elastic",
          },
          {
            id: "ocean-4",
            avatarId: "y-bot",
            prop: PropType.CLUB,
            effect: "bubbles",
            effort: "elastic",
          },
        ],
      },
      effectPresets: { bubbles: "bubbles-iridescent" },
      camera: { preset: "high-reveal" },
    },
    {
      id: "celestial-canon",
      title: "Celestial count canon",
      intent:
        "Eight club performers form a tunnel. Each starts one count behind the performer ahead while the camera moves from head-on to the side.",
      durationSeconds: 10,
      transition: { kind: "fade-through-black", durationSeconds: 1.1 },
      location: { environmentId: "celestial", showStage: true },
      performance: {
        bpm: 84,
        formation: "tunnel-stack",
        performers: [
          {
            id: "canon-1",
            avatarId: "y-bot",
            prop: PropType.CLUB,
            effect: "led",
            beatOffset: 0,
          },
          {
            id: "canon-2",
            avatarId: "x-bot",
            prop: PropType.CLUB,
            effect: "led",
            beatOffset: -1,
          },
          {
            id: "canon-3",
            avatarId: "ch01",
            prop: PropType.CLUB,
            effect: "led",
            beatOffset: -2,
          },
          {
            id: "canon-4",
            avatarId: "y-bot",
            prop: PropType.CLUB,
            effect: "led",
            beatOffset: -3,
          },
          {
            id: "canon-5",
            avatarId: "x-bot",
            prop: PropType.CLUB,
            effect: "led",
            beatOffset: -4,
          },
          {
            id: "canon-6",
            avatarId: "ch01",
            prop: PropType.CLUB,
            effect: "led",
            beatOffset: -5,
          },
          {
            id: "canon-7",
            avatarId: "y-bot",
            prop: PropType.CLUB,
            effect: "led",
            beatOffset: -6,
          },
          {
            id: "canon-8",
            avatarId: "x-bot",
            prop: PropType.CLUB,
            effect: "led",
            beatOffset: -7,
          },
        ],
      },
      effectPresets: { led: "led-rainbow-pov" },
      camera: {
        preset: "custom",
        keyframes: [
          {
            atSeconds: 0,
            position: [0, 1.2, -12],
            target: { kind: "group" },
            fovDeg: 54,
            interpolation: "smooth",
          },
          {
            atSeconds: 5,
            position: [6.5, 2.4, -6],
            target: { kind: "group" },
            fovDeg: 50,
            interpolation: "smooth",
          },
          {
            atSeconds: 10,
            position: [11, 2, 0],
            target: { kind: "group" },
            fovDeg: 48,
            interpolation: "smooth",
          },
        ],
      },
    },
  ],
};
