@echo off
setlocal
REM Generated by agent-hub install.ps1. Safe to edit or replace with a
REM project-specific launcher; the installer never overwrites an existing file.
REM Strip inherited NO_COLOR so Claude Code renders its branding.
set "NO_COLOR="
set "REPO_ROOT=%~dp0.."
set "BAT_FILE=%~f0"
set "AGENT_TERMINAL=%LOCALAPPDATA%\AgentHub\bin\AgentTerminalLauncher.exe"

if not defined TKA_AGENT_TERMINAL if exist "%AGENT_TERMINAL%" (
    "%AGENT_TERMINAL%" -Agent claude -Project "%REPO_ROOT%" -Bat "%BAT_FILE%"
    exit /b
)

cd /d "%REPO_ROOT%"

where claude >nul 2>&1
if %errorlevel%==0 (
    claude --dangerously-skip-permissions
) else if exist "%USERPROFILE%\.local\bin\claude.exe" (
    "%USERPROFILE%\.local\bin\claude.exe" --dangerously-skip-permissions
) else (
    echo.
    echo claude was not found on PATH or in %USERPROFILE%\.local\bin
    echo Install with:  irm https://claude.ai/install.ps1 ^| iex
    echo.
    pause
)
