@echo off
setlocal
REM Generated by agent-hub install.ps1. Safe to edit or replace with a
REM project-specific launcher; the installer never overwrites an existing file.
set "NO_COLOR="
set "REPO_ROOT=%~dp0.."
cd /d "%REPO_ROOT%"

where codex >nul 2>&1
if %errorlevel%==0 (
    codex --dangerously-bypass-approvals-and-sandbox
) else if exist "%APPDATA%\npm\codex.cmd" (
    "%APPDATA%\npm\codex.cmd" --dangerously-bypass-approvals-and-sandbox
) else (
    echo.
    echo codex was not found on PATH or in %APPDATA%\npm
    echo Install with:  npm install -g @openai/codex
    echo.
    pause
)
