<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { fade, fly } from "svelte/transition";
  import { container } from "$lib/shared/di";
  import type { IHapticFeedback } from "$lib/shared/application/services/contracts/IHapticFeedback";
  import PanelTabs from "$lib/shared/components/panel/PanelTabs.svelte";
  import PanelState from "$lib/shared/components/panel/PanelState.svelte";
  import type { LibrarySequence } from "$lib/features/library/domain/models/LibrarySequence";
  import type {
    EnhancedUserProfile,
    UserProfile,
  } from "$lib/shared/community/domain/models/enhanced-user-profile";
  import AvatarImage from "./AvatarImage.svelte";
  import PropAwareThumbnail from "$lib/features/browse/sequences/display/components/PropAwareThumbnail.svelte";
  import { getAnimationVisibilityManager } from "$lib/shared/animation-engine/state/animation-visibility-state.svelte";

  type ProfileTab = "gallery" | "followers" | "following" | "achievements";

  let {
    activeTab,
    userProfile,
    userSequences = [],
    followerUsers = [],
    followingUsers = [],
    followersLoading = false,
    followingLoading = false,
    onTabChange,
    onSequenceClick,
    onUserClick,
  }: {
    activeTab: ProfileTab;
    userProfile: EnhancedUserProfile;
    userSequences?: readonly LibrarySequence[];
    followerUsers?: readonly UserProfile[];
    followingUsers?: readonly UserProfile[];
    followersLoading?: boolean;
    followingLoading?: boolean;
    onTabChange: (tab: ProfileTab) => void;
    onSequenceClick: (sequence: LibrarySequence) => void;
    onUserClick: (user: UserProfile) => void;
  } = $props();

  let hapticService: IHapticFeedback | undefined;

  // Light mode tracking - reacts to "L" key toggle
  const visibilityManager = getAnimationVisibilityManager();
  let lightMode = $state(!visibilityManager.isDarkMode());

  function handleVisibilityChange() {
    lightMode = !visibilityManager.isDarkMode();
  }

  onMount(() => {
    hapticService = container.items.hapticFeedback;
    visibilityManager.registerObserver(handleVisibilityChange);
  });

  onDestroy(() => {
    visibilityManager.unregisterObserver(handleVisibilityChange);
  });

  function handleSequenceClick(sequence: LibrarySequence) {
    hapticService?.trigger("selection");
    onSequenceClick(sequence);
  }

  function handleUserClick(user: UserProfile) {
    hapticService?.trigger("selection");
    onUserClick(user);
  }

  /**
   * Get a display name for a sequence, handling malformed/auto-generated names
   */
  function getDisplayName(sequence: LibrarySequence): string {
    // Check if name looks auto-generated (e.g., "Sequence 6:15:49 PM")
    const isAutoGeneratedName = sequence.name?.match(
      /^Sequence\s+\d+:\d+:\d+/i
    );

    // Prefer word if name is auto-generated or empty
    if (sequence.word && (isAutoGeneratedName || !sequence.name)) {
      return sequence.word;
    }

    // Use name if available and not auto-generated
    if (sequence.name && !isAutoGeneratedName) {
      return sequence.name;
    }

    // Fallback to steps count
    if (sequence.steps && sequence.steps.length > 0) {
      return `${sequence.steps.length} beat sequence`;
    }

    return "Untitled Sequence";
  }
</script>

<div class="tabs-wrapper" transition:fly={{ y: 20, duration: 300, delay: 200 }}>
  <PanelTabs
    tabs={[
      {
        value: "gallery",
        label: `Sequences (${userSequences.length})`,
        icon: "fa-list",
      },
      {
        value: "followers",
        label: `Followers (${userProfile.followerCount})`,
        icon: "fa-users",
      },
      {
        value: "following",
        label: `Following (${userProfile.followingCount})`,
        icon: "fa-user-plus",
      },
      {
        value: "achievements",
        label: `Achievements (${userProfile.achievementCount})`,
        icon: "fa-trophy",
      },
    ]}
    {activeTab}
    onchange={(tab: string) => onTabChange(tab as ProfileTab)}
  />
</div>

<div class="profile-tab-content">
  {#if activeTab === "gallery"}
    {#if userSequences.length === 0}
      <PanelState
        type="empty"
        icon="fa-list"
        title="No Sequences"
        message="No sequences yet"
      />
    {:else}
      <div class="sequences-grid">
        {#each userSequences as sequence (sequence.id)}
          <button
            class="sequence-card"
            onclick={() => handleSequenceClick(sequence)}
            transition:fade={{ duration: 200 }}
          >
            <div class="sequence-thumbnail">
              <PropAwareThumbnail sequence={sequence} {lightMode} />
            </div>

            <div class="sequence-info">
              <h3 class="sequence-name">{getDisplayName(sequence)}</h3>

              <div class="sequence-meta">
                {#if sequence.createdAt}
                  <span class="meta-item">
                    <i class="fas fa-clock" aria-hidden="true"></i>
                    {sequence.createdAt instanceof Date
                      ? sequence.createdAt.toLocaleDateString()
                      : new Date(sequence.createdAt).toLocaleDateString()}
                  </span>
                {/if}
                {#if sequence.steps && sequence.steps.length > 0}
                  <span class="meta-item">
                    <i class="fas fa-music" aria-hidden="true"></i>
                    {sequence.steps.length} steps
                  </span>
                {/if}
              </div>
            </div>
          </button>
        {/each}
      </div>
    {/if}
  {:else if activeTab === "followers"}
    {#if followersLoading}
      <PanelState type="loading" message="Loading followers..." />
    {:else if followerUsers.length === 0}
      <PanelState
        type="empty"
        icon="fa-users"
        title="No Followers Yet"
        message="This user doesn't have any followers yet"
      />
    {:else}
      <div class="user-list-grid">
        {#each followerUsers as user (user.id)}
          <button
            class="user-list-card"
            onclick={() => handleUserClick(user)}
            transition:fade={{ duration: 200 }}
          >
            <div class="user-list-avatar">
              <AvatarImage src={user.avatar} alt={user.displayName} size={48} />
            </div>
            <div class="user-list-info">
              <h4 class="user-list-name">{user.displayName}</h4>
              <p class="user-list-username">@{user.username}</p>
            </div>
            <div class="user-list-stats">
              <span class="user-list-stat">
                <i class="fas fa-list" aria-hidden="true"></i>
                {user.sequenceCount}
              </span>
              <span class="user-list-stat">
                <i class="fas fa-users" aria-hidden="true"></i>
                {user.followerCount}
              </span>
            </div>
            <i class="fas fa-chevron-right user-list-arrow" aria-hidden="true"
            ></i>
          </button>
        {/each}
      </div>
    {/if}
  {:else if activeTab === "following"}
    {#if followingLoading}
      <PanelState type="loading" message="Loading following..." />
    {:else if followingUsers.length === 0}
      <PanelState
        type="empty"
        icon="fa-user-plus"
        title="Not Following Anyone"
        message="This user isn't following anyone yet"
      />
    {:else}
      <div class="user-list-grid">
        {#each followingUsers as user (user.id)}
          <button
            class="user-list-card"
            onclick={() => handleUserClick(user)}
            transition:fade={{ duration: 200 }}
          >
            <div class="user-list-avatar">
              <AvatarImage src={user.avatar} alt={user.displayName} size={48} />
            </div>
            <div class="user-list-info">
              <h4 class="user-list-name">{user.displayName}</h4>
              <p class="user-list-username">@{user.username}</p>
            </div>
            <div class="user-list-stats">
              <span class="user-list-stat">
                <i class="fas fa-list" aria-hidden="true"></i>
                {user.sequenceCount}
              </span>
              <span class="user-list-stat">
                <i class="fas fa-users" aria-hidden="true"></i>
                {user.followerCount}
              </span>
            </div>
            <i class="fas fa-chevron-right user-list-arrow" aria-hidden="true"
            ></i>
          </button>
        {/each}
      </div>
    {/if}
  {:else if activeTab === "achievements"}
    {#if userProfile.topAchievements.length === 0}
      <PanelState
        type="empty"
        icon="fa-trophy"
        title="No Achievements"
        message="No achievements yet"
      />
    {:else}
      <div class="user-profile-achievements-grid">
        {#each userProfile.topAchievements as achievement (achievement.id)}
          <div class="achievement-card" transition:fade={{ duration: 200 }}>
            <div class="achievement-icon tier-{achievement.tier}">
              <i class="fas {achievement.icon}" aria-hidden="true"></i>
            </div>
            <div class="achievement-info">
              <h4 class="achievement-name">{achievement.title}</h4>
              <p class="achievement-description">
                {achievement.description}
              </p>
              <div class="achievement-meta">
                <span class="tier-badge tier-{achievement.tier}">
                  {achievement.tier}
                </span>
                <span class="xp-badge">
                  <i class="fas fa-bolt" aria-hidden="true"></i>
                  {achievement.xpReward} XP
                </span>
              </div>
            </div>
          </div>
        {/each}
      </div>
    {/if}
  {/if}
</div>

<style>
  .tabs-wrapper {
    container-type: inline-size;
    container-name: tabs-wrapper;

    display: flex;
    justify-content: center;
    margin-bottom: 16px;
  }

  .profile-tab-content {
    container-type: inline-size;
    container-name: tab-content;

    min-height: 300px;
  }

  .sequences-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
    gap: 16px;
  }

  /* Wide screens: cap at 3 columns for readability */
  @container tab-content (min-width: 800px) {
    .sequences-grid {
      grid-template-columns: repeat(3, 1fr);
    }
  }

  .sequence-card {
    display: flex;
    flex-direction: column;
    gap: 12px;
    padding: 16px;
    background: var(--theme-card-bg);
    border: 1px solid var(--theme-stroke);
    border-radius: 12px;
    cursor: pointer;
    transition: all var(--duration-normal) ease;
    text-align: left;
  }

  .sequence-card:hover {
    background: var(--theme-card-hover-bg);
    border-color: var(--theme-stroke-strong);
    transform: translateY(-2px);
    box-shadow: 0 4px 12px var(--theme-shadow);
  }

  .sequence-thumbnail {
    width: 100%;
    border-radius: 8px;
    overflow: hidden;
    container-type: inline-size;
    container-name: sequence-card;
  }

  .sequence-info {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .sequence-name {
    margin: 0;
    font-size: var(--font-size-base);
    font-weight: 600;
    color: var(--theme-text, white);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .sequence-meta {
    display: flex;
    align-items: center;
    gap: 16px;
    flex-wrap: wrap;
  }

  .meta-item {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: var(--font-size-compact);
    color: var(--theme-text-dim);
  }

  .meta-item i {
    font-size: var(--font-size-compact);
  }

  .user-list-grid {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .user-list-card {
    display: flex;
    align-items: center;
    gap: 16px;
    padding: 16px;
    background: var(--theme-card-bg);
    border: 1px solid var(--theme-stroke);
    border-radius: 12px;
    cursor: pointer;
    transition: all var(--duration-normal) ease;
    text-align: left;
    width: 100%;
  }

  .user-list-card:hover {
    background: var(--theme-card-hover-bg);
    border-color: var(--theme-stroke-strong);
    transform: translateX(4px);
  }

  .user-list-avatar {
    width: var(--min-touch-target);
    height: var(--min-touch-target);
    flex-shrink: 0;
  }

  .user-list-info {
    flex: 1;
    min-width: 0;
  }

  .user-list-name {
    margin: 0;
    font-size: var(--font-size-sm);
    font-weight: 600;
    color: var(--theme-text, white);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .user-list-username {
    margin: 2px 0 0 0;
    font-size: var(--font-size-compact);
    color: var(--theme-text-dim);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .user-list-stats {
    display: flex;
    gap: 12px;
    flex-shrink: 0;
  }

  .user-list-stat {
    display: flex;
    align-items: center;
    gap: 4px;
    font-size: var(--font-size-compact);
    color: var(--theme-text-dim);
  }

  .user-list-stat i {
    font-size: var(--font-size-compact);
  }

  .user-list-arrow {
    font-size: var(--font-size-compact);
    color: var(--theme-text-dim);
    flex-shrink: 0;
    transition: transform var(--duration-normal) ease;
  }

  .user-list-card:hover .user-list-arrow {
    transform: translateX(4px);
    color: var(--theme-text-dim);
  }

  .user-profile-achievements-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 16px;
  }

  /* Wide screens: cap at 2 columns for achievements */
  @container tab-content (min-width: 700px) {
    .user-profile-achievements-grid {
      grid-template-columns: repeat(2, 1fr);
    }
  }

  .achievement-card {
    display: flex;
    align-items: center;
    gap: 16px;
    padding: 20px;
    background: var(--theme-card-bg);
    border: 1px solid var(--theme-stroke);
    border-radius: 12px;
    transition: all var(--duration-normal) ease;
  }

  .achievement-card:hover {
    background: var(--theme-card-hover-bg);
    border-color: var(--theme-stroke-strong);
    transform: translateY(-2px);
  }

  .achievement-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 60px;
    height: 60px;
    background: color-mix(in srgb, var(--theme-accent) 20%, transparent);
    border-radius: 50%;
    flex-shrink: 0;
    border: 2px solid color-mix(in srgb, var(--theme-accent) 30%, transparent);
  }

  .achievement-icon.tier-bronze {
    background: rgba(205, 127, 50, 0.2);
    border-color: rgba(205, 127, 50, 0.4);
  }

  .achievement-icon.tier-silver {
    background: rgba(192, 192, 192, 0.2);
    border-color: rgba(192, 192, 192, 0.4);
  }

  .achievement-icon.tier-gold {
    background: rgba(255, 215, 0, 0.2);
    border-color: rgba(255, 215, 0, 0.4);
  }

  .achievement-icon.tier-platinum {
    background: rgba(229, 228, 226, 0.2);
    border-color: rgba(229, 228, 226, 0.4);
  }

  .achievement-info {
    flex: 1;
  }

  .achievement-name {
    margin: 0 0 4px 0;
    font-size: var(--font-size-base);
    font-weight: 600;
    color: var(--theme-text, white);
  }

  .achievement-description {
    margin: 0 0 8px 0;
    font-size: var(--font-size-compact);
    line-height: 1.4;
    color: var(--theme-text-dim);
  }

  .achievement-meta {
    display: flex;
    align-items: center;
    gap: 12px;
  }

  .tier-badge,
  .xp-badge {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    padding: 4px 10px;
    border-radius: 12px;
    font-size: var(--font-size-compact);
    font-weight: 600;
    text-transform: capitalize;
  }

  .tier-badge.tier-bronze {
    background: rgba(205, 127, 50, 0.2);
    color: rgb(205, 127, 50);
  }

  .tier-badge.tier-silver {
    background: rgba(192, 192, 192, 0.2);
    color: rgb(192, 192, 192);
  }

  .tier-badge.tier-gold {
    background: rgba(255, 215, 0, 0.2);
    color: rgb(255, 215, 0);
  }

  .tier-badge.tier-platinum {
    background: rgba(229, 228, 226, 0.2);
    color: rgb(229, 228, 226);
  }

  .xp-badge {
    background: color-mix(in srgb, var(--theme-accent) 20%, transparent);
    color: var(--theme-accent);
  }

  .xp-badge i {
    font-size: var(--font-size-compact);
  }

  /* Narrow: single column */
  @container tab-content (max-width: 500px) {
    .sequences-grid {
      grid-template-columns: 1fr;
      gap: 12px;
    }

    .user-profile-achievements-grid {
      grid-template-columns: 1fr;
      gap: 12px;
    }

    .sequence-card {
      padding: 12px;
    }

    .achievement-card {
      padding: 16px;
    }
  }

  /* Very narrow: tighter spacing */
  @container tab-content (max-width: 360px) {
    .sequence-card,
    .user-list-card {
      padding: 10px;
      gap: 10px;
    }

    .achievement-card {
      padding: 12px;
      gap: 12px;
    }

    .achievement-icon {
      width: 48px;
      height: 48px;
    }
  }

  @media (prefers-reduced-motion: reduce) {
    .sequence-card,
    .achievement-card,
    .user-list-card {
      transition: none;
    }

    .sequence-card:hover,
    .achievement-card:hover,
    .user-list-card:hover {
      transform: none;
    }

    .user-list-arrow,
    .user-list-card:hover .user-list-arrow {
      transition: none;
      transform: none;
    }
  }
</style>
