/**
 * The trench floor at runtime.
 *
 * `seabed-heights.json` is generated by `scripts/traverse_seabed.py`, which is
 * also what bakes the visual mesh (`static/models/water-traverse/trench-floor.glb`)
 * and what the reef generator samples when it places specimens. One field,
 * three consumers, no second opinion about where the ground is.
 *
 * Relief is stored as metres ABOVE the analytic base floor and is never
 * negative. That is load-bearing: the flat `sea-floor` / `descent` / `ascent`
 * colliders stay exactly where they are as a safety plane, and the sculpted
 * surface is tiled on top of them. Nothing can fall through a gap in the grid.
 *
 * The tiles are flat cuboids rather than a heightfield collider because the
 * walk already runs on a cuboid world and a 3 m cell keeps every step inside
 * the controller's autostep. The route itself has zero relief by construction,
 * so the surface the visitor actually walks is smooth — the stepping only
 * exists out on the dunes, where the point is that the ground is rough.
 */

import grid from "./seabed-heights.json";

interface SeabedGrid {
  minX: number;
  minZ: number;
  step: number;
  cols: number;
  rows: number;
  pathHalfWidth: number;
  relief: number[][];
}

const field = grid as SeabedGrid;

/** Half-width of the cleared route. Relief is exactly zero inside it. */
export const PATH_HALF_W = field.pathHalfWidth;

export const SEABED_MIN_Z = field.minZ;
export const SEABED_MAX_Z = field.minZ + field.rows * field.step;

/**
 * Relief above the base floor at a world point, bilinearly interpolated.
 *
 * Bilinear rather than nearest because this is what the REEF samples: a
 * specimen snapped to its cell's height sits visibly proud on one side of a
 * dune and buried on the other. The colliders deliberately do not interpolate
 * — a tile is one flat cuboid — so a specimen can sit up to a few centimetres
 * off the surface the visitor stands on, which at 18 m depth is invisible and
 * is the right trade against 322 sloped colliders.
 */
export function seabedReliefAt(x: number, z: number): number {
  const fx = (x - field.minX) / field.step - 0.5;
  const fz = (z - field.minZ) / field.step - 0.5;

  const x0 = Math.floor(fx);
  const z0 = Math.floor(fz);
  const tx = fx - x0;
  const tz = fz - z0;

  const at = (cx: number, cz: number): number => {
    if (cz < 0 || cz >= field.rows) return 0;
    if (cx < 0 || cx >= field.cols) return 0;
    return field.relief[cz][cx];
  };

  const a = at(x0, z0);
  const b = at(x0 + 1, z0);
  const c = at(x0, z0 + 1);
  const d = at(x0 + 1, z0 + 1);

  return (
    a * (1 - tx) * (1 - tz) +
    b * tx * (1 - tz) +
    c * (1 - tx) * tz +
    d * tx * tz
  );
}

export interface SeabedTile {
  id: string;
  /** Cell centre. */
  x: number;
  z: number;
  /** Top surface of the tile, in world Y. */
  topY: number;
  size: number;
}

/**
 * The tiles worth building colliders for.
 *
 * Cells with no relief are skipped entirely: there the flat base floor already
 * IS the surface, and a tile of thickness zero on top of it is 200 wasted
 * colliders. That skip is also why the route costs nothing — it is the part of
 * the field defined to be flat.
 */
export function buildSeabedTiles(baseFloorYAt: (z: number) => number): SeabedTile[] {
  const tiles: SeabedTile[] = [];
  const MIN_RELIEF = 0.04;

  for (let row = 0; row < field.rows; row += 1) {
    const z = field.minZ + (row + 0.5) * field.step;
    // No leg filter is needed: the field spans exactly the sea leg and tapers
    // to zero relief at both seams, so the snowfield and the spring plain keep
    // their own floors untouched.
    for (let col = 0; col < field.cols; col += 1) {
      const relief = field.relief[row][col];
      if (relief < MIN_RELIEF) continue;
      const x = field.minX + (col + 0.5) * field.step;
      tiles.push({
        id: `seabed-tile-${col}-${row}`,
        x,
        z,
        topY: baseFloorYAt(z) + relief,
        size: field.step,
      });
    }
  }

  return tiles;
}
