/**
 * The trench floor at runtime.
 *
 * `seabed-heights.json` is generated by `scripts/traverse_seabed.py`, which is
 * also what bakes the visual mesh (`static/models/water-traverse/trench-floor.glb`)
 * and what the reef generator samples when it places specimens. One field,
 * three consumers, no second opinion about where the ground is.
 *
 * Relief is stored as metres ABOVE the analytic base floor and is never
 * negative. That is load-bearing: the flat `sea-floor` / `descent` / `ascent`
 * colliders stay exactly where they are as a safety plane, and the sculpted
 * surface sits on top of them. Nothing can fall through a gap in the field.
 *
 * ── Why a trimesh and not tiles ─────────────────────────────────────────────
 *
 * The first pass tiled the colliders as flat 3 m cuboids, reasoning that a step
 * smaller than the character controller's autostep would go unnoticed. That is
 * backwards: autostep means the walker CLIMBS the step instead of being blocked
 * by it, so a 3 m grid under smooth-drawn dunes reads as a staircase — which is
 * exactly how it felt.
 *
 * The grid is now the mesh's own 0.9 m vertex lattice, triangulated into a
 * single static trimesh. The collided surface IS the drawn surface: same
 * vertices, same values, generated in the same pass. There is no resolution
 * left at which they can disagree.
 */

import grid from "./seabed-heights.json";

interface SeabedGrid {
  minX: number;
  minZ: number;
  step: number;
  cols: number;
  rows: number;
  pathHalfWidth: number;
  relief: number[][];
}

const field = grid as SeabedGrid;

/** Half-width of the cleared route. Relief is exactly zero inside it. */
export const PATH_HALF_W = field.pathHalfWidth;

export const SEABED_MIN_Z = field.minZ;
export const SEABED_MAX_Z = field.minZ + (field.rows - 1) * field.step;

/**
 * Relief above the base floor at a world point.
 *
 * Bilinear across the vertex lattice, which is the same interpolation the
 * trimesh's triangles perform, so a specimen placed with this function and the
 * ground the visitor stands on agree to within the split of a quad's diagonal —
 * sub-millimetre at this cell size.
 */
export function seabedReliefAt(x: number, z: number): number {
  const fx = (x - field.minX) / field.step;
  const fz = (z - field.minZ) / field.step;

  const x0 = Math.floor(fx);
  const z0 = Math.floor(fz);
  const tx = fx - x0;
  const tz = fz - z0;

  const at = (cx: number, cz: number): number => {
    if (cz < 0 || cz >= field.rows) return 0;
    if (cx < 0 || cx >= field.cols) return 0;
    return field.relief[cz][cx];
  };

  const a = at(x0, z0);
  const b = at(x0 + 1, z0);
  const c = at(x0, z0 + 1);
  const d = at(x0 + 1, z0 + 1);

  return (
    a * (1 - tx) * (1 - tz) +
    b * tx * (1 - tz) +
    c * (1 - tx) * tz +
    d * tx * tz
  );
}

/** A static triangle soup, in world coordinates, ready for Rapier. */
export interface SeabedMesh {
  vertices: Float32Array;
  indices: Uint32Array;
  triangleCount: number;
}

/**
 * Triangulate the field into the collider the visitor walks on.
 *
 * World coordinates rather than a local grid plus a transform: the base floor
 * ramps with Z (the descent drops 18 m), so a vertex's height depends on where
 * it is along the walk and cannot be factored out into a collider translation.
 *
 * Winding is irrelevant here — Rapier's trimesh is solid from both sides — so
 * this deliberately does NOT mirror the bake's `(a, d, c, b)` order, which
 * exists only to make the renderer's back-face culling point the right way.
 */
export function buildSeabedMesh(baseFloorYAt: (z: number) => number): SeabedMesh {
  const { cols, rows, step, minX, minZ } = field;

  const vertices = new Float32Array(cols * rows * 3);
  for (let row = 0; row < rows; row += 1) {
    const z = minZ + row * step;
    const baseY = baseFloorYAt(z);
    for (let col = 0; col < cols; col += 1) {
      const i = (row * cols + col) * 3;
      vertices[i] = minX + col * step;
      vertices[i + 1] = baseY + field.relief[row][col];
      vertices[i + 2] = z;
    }
  }

  const quadCount = (cols - 1) * (rows - 1);
  const indices = new Uint32Array(quadCount * 6);
  let out = 0;
  for (let row = 0; row < rows - 1; row += 1) {
    for (let col = 0; col < cols - 1; col += 1) {
      const a = row * cols + col;
      const b = a + 1;
      const c = a + cols + 1;
      const d = a + cols;
      indices[out] = a;
      indices[out + 1] = b;
      indices[out + 2] = c;
      indices[out + 3] = a;
      indices[out + 4] = c;
      indices[out + 5] = d;
      out += 6;
    }
  }

  return { vertices, indices, triangleCount: quadCount * 2 };
}
