/**
 * AUTO-GENERATED by scripts/ingest-half-arrows.mjs — do not edit by hand.
 * Regenerate with: npx tsx scripts/ingest-half-arrows.mjs
 *
 * Per-motion-type turns values that have a dedicated halved-motion glyph
 * (`static/images/arrows/{mt}_half/from_radial/{mt}_half_{turns}.svg`).
 * Anything absent falls back to the bare `{mt}_half.svg`.
 *
 * This is the single source of truth for half-glyph coverage: the arrow path
 * resolver reads it to pick asset files, and /test/half-movements reads it to
 * paint the coverage matrix.
 */
export const HALF_ASSET_TURNS: Readonly<
  Record<string, ReadonlySet<number | "fl">>
> = {
  pro: new Set<number | "fl">([1, 2]),
  anti: new Set<number | "fl">([1, 2]),
  dash: new Set<number | "fl">([2]),
  static: new Set<number | "fl">([2]),
};
