<script lang="ts">
  // Plain looping video of a pre-baked guide motion demo.
  // Assets are generated by /test/guide-motion-bake — see guide-motion-configs.ts.
  let { id, label }: { id: string; label: string } = $props();
</script>

<video
  class="guide-motion-video"
  src={`/guide/level-1/motions/${id}.mp4`}
  autoplay
  loop
  muted
  playsinline
  preload="metadata"
  aria-label={label}
></video>

<style>
  .guide-motion-video {
    display: block;
    width: 100%;
    aspect-ratio: 1;
    object-fit: contain;
  }
</style>
