import type { GuideNavChapter } from "./guide-types";

export const guideChapters: GuideNavChapter[] = [
  {
    slug: "positions-motions",
    title: "1.0 - Positions & Motions",
    sections: [
      { id: "the-grid", title: "The Grid" },
      { id: "hand-positions", title: "Hand Positions" },
      { id: "hand-motions", title: "Hand Motions" },
      { id: "type-1-alpha-beta", title: "Type 1 - Dual-Shifts" },
      { id: "type-1-gamma", title: "Gamma" },
      { id: "type-2-shifts", title: "Type 2 - Shifts" },
      { id: "type-3-cross-shifts", title: "Type 3 - Cross-Shifts" },
      { id: "type-4-dash", title: "Type 4 - Dash" },
      { id: "type-5-dual-dash", title: "Type 5 - Dual-Dash" },
      { id: "type-6-static", title: "Type 6 - Static" },
      { id: "staff-positions", title: "Staff Positions" },
      { id: "staff-motions", title: "Staff Motions" },
      { id: "negative-space", title: "Negative Space" },
    ],
  },
  {
    slug: "letters",
    title: "1.1 - Letters",
    sections: [
      { id: "codex-type-1-2", title: "Codex - Type 1/2" },
      { id: "codex-type-3-6", title: "Codex - Type 3–6" },
      { id: "type-1-letters", title: "Type 1 Letters" },
      { id: "alpha-beta-words", title: "Alpha/Beta Words" },
      { id: "compound-letters", title: "Compound Letters" },
      { id: "compound-words", title: "Compound Words" },
      { id: "gamma-letters", title: "Gamma Letters" },
      { id: "gamma-words", title: "Gamma Words" },
      { id: "type-2-shifts-letters", title: "Type 2 Letters" },
      { id: "type-3-cross-shift-letters", title: "Type 3 Letters" },
      { id: "type-4-5-6-letters", title: "Type 4/5/6 Letters" },
    ],
  },
  {
    slug: "words",
    title: "1.2 - Words & LOOPs",
    sections: [
      { id: "words-intro", title: "Words" },
      { id: "loops", title: "LOOPs" },
      { id: "loops-vs-caps", title: "LOOPs vs CAPs" },
      { id: "reversals", title: "Reversals" },
      { id: "aabb-examples", title: "AABB Examples" },
      { id: "aabb-body-turn", title: "AABB Body Turn" },
      { id: "acac-bcbc", title: "ACAC / BCBC" },
      { id: "type-1-loops", title: "Type 1 LOOPs" },
      { id: "gamma-loops", title: "Gamma LOOPs" },
      { id: "type-2-loops", title: "Type 2 LOOPs" },
      { id: "sixteen-count", title: "16-Count" },
      { id: "eight-letter-words", title: "8-Letter Words" },
      { id: "prop-reversal-loops", title: "Prop-Reversal LOOPs" },
      { id: "full-reversal-loops", title: "Full-Reversal LOOPs" },
    ],
  },
];
