import type { Mesh } from "three";
import { composerRegistry } from "$lib/shared/3d/scene-composer/registry";
import type {
  SceneComposerPlugin,
  ComposerCatalog,
  CatalogCategory,
  SurfaceRules,
  PlacementConstraints,
} from "$lib/shared/3d/scene-composer/types";
import type { ObjectDefinition } from "$lib/shared/3d/procedural-engine/objects/object-catalog";
import { OCEAN_PLACEMENTS } from "./placements";
import { createMetadataSceneObjectAdapter } from "$lib/shared/3d/scene-composer/metadata-scene-object-adapter";

// ─────────────────────────────────────────────────────────────
// CORALS
// ─────────────────────────────────────────────────────────────
const coralItems: ObjectDefinition[] = [
  {
    key: "coral-0",
    name: "Brain Coral",
    type: "prop",
    icon: "fa-circle-nodes",
    modelPath: "/models/ocean/meshy/brain_coral.glb",
    fallbackGeometry: "sphere",
    defaultScale: 1.2,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff6666,
  },
  {
    key: "coral-1",
    name: "Fan Coral",
    type: "prop",
    icon: "fa-circle-nodes",
    modelPath: "/models/ocean/meshy/fan_coral.glb",
    fallbackGeometry: "cone",
    defaultScale: 1.0,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff9944,
  },
  {
    key: "coral-2",
    name: "Branching Coral",
    type: "prop",
    icon: "fa-circle-nodes",
    modelPath: "/models/ocean/meshy/staghorn_coral.glb",
    fallbackGeometry: "cylinder",
    defaultScale: 1.1,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xcc4488,
  },
  {
    key: "coral-3",
    name: "Staghorn Coral",
    type: "prop",
    icon: "fa-circle-nodes",
    modelPath: "/models/ocean/meshy/table_coral.glb",
    fallbackGeometry: "cone",
    defaultScale: 1.3,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff8866,
  },
  {
    key: "coral-4",
    name: "Mushroom Coral",
    type: "prop",
    icon: "fa-circle-nodes",
    modelPath: "/models/ocean/meshy/photorealistic_coral_0.glb",
    fallbackGeometry: "sphere",
    defaultScale: 0.9,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xee5577,
  },
  {
    key: "coral-5",
    name: "Pillar Coral",
    type: "prop",
    icon: "fa-circle-nodes",
    modelPath: "/models/ocean/meshy/photorealistic_coral_1.glb",
    fallbackGeometry: "cylinder",
    defaultScale: 1.4,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff7733,
  },
  {
    key: "coral-6",
    name: "Table Coral",
    type: "prop",
    icon: "fa-circle-nodes",
    modelPath: "/models/ocean/meshy/photorealistic_coral_2.glb",
    fallbackGeometry: "box",
    defaultScale: 1.0,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xdd5599,
  },
  {
    key: "coral-large",
    name: "Large Coral Head",
    type: "prop",
    icon: "fa-circle-nodes",
    modelPath: "/models/ocean/meshy/coral_mountain.glb",
    fallbackGeometry: "sphere",
    defaultScale: 2.0,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff4455,
  },
];

// ─────────────────────────────────────────────────────────────
// FLORA
// ─────────────────────────────────────────────────────────────
const floraItems: ObjectDefinition[] = [
  {
    key: "seaweed",
    name: "Seaweed",
    type: "prop",
    icon: "fa-leaf",
    modelPath: "/models/ocean/meshy/ribbon_seaweed.glb",
    fallbackGeometry: "cylinder",
    defaultScale: 1.2,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x44aa66,
  },
  {
    key: "kelp-plant",
    name: "Kelp Plant",
    type: "prop",
    icon: "fa-leaf",
    modelPath: "/models/ocean/kelp_plant.glb",
    fallbackGeometry: "cylinder",
    defaultScale: 1.8,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x228844,
  },
];

// ─────────────────────────────────────────────────────────────
// DECORATIONS
// ─────────────────────────────────────────────────────────────
const decorationItems: ObjectDefinition[] = [
  {
    key: "starfish",
    name: "Starfish",
    type: "prop",
    icon: "fa-star",
    modelPath: "/models/ocean/starfish.glb",
    fallbackGeometry: "sphere",
    defaultScale: 0.5,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xffaa44,
  },
  {
    key: "sea-urchin",
    name: "Sea Urchin",
    type: "prop",
    icon: "fa-circle-dot",
    modelPath: "/models/ocean/sea_urchin.glb",
    fallbackGeometry: "sphere",
    defaultScale: 0.4,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x332244,
  },
  {
    key: "shell",
    name: "Shell",
    type: "prop",
    icon: "fa-spiral",
    modelPath: "/models/ocean/shell.glb",
    fallbackGeometry: "sphere",
    defaultScale: 0.3,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xeeddcc,
  },
  {
    key: "anemone",
    name: "Sea Anemone",
    type: "prop",
    icon: "fa-asterisk",
    modelPath: "/models/ocean/anemone.glb",
    fallbackGeometry: "cylinder",
    defaultScale: 0.7,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff66aa,
  },
];

// ─────────────────────────────────────────────────────────────
// ROCKS
// ─────────────────────────────────────────────────────────────
const rockItems: ObjectDefinition[] = [
  {
    key: "rock-0",
    name: "Smooth Rock",
    type: "prop",
    icon: "fa-mountain",
    modelPath: "/models/ocean/rock_0.glb",
    fallbackGeometry: "sphere",
    defaultScale: 1.0,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x445566,
  },
  {
    key: "rock-1",
    name: "Jagged Rock",
    type: "prop",
    icon: "fa-mountain",
    modelPath: "/models/ocean/rock_1.glb",
    fallbackGeometry: "box",
    defaultScale: 1.2,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x334455,
  },
  {
    key: "rock-2",
    name: "Flat Rock",
    type: "prop",
    icon: "fa-mountain",
    modelPath: "/models/ocean/rock_2.glb",
    fallbackGeometry: "box",
    defaultScale: 0.9,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x3d4f5f,
  },
  {
    key: "rock-3",
    name: "Mossy Rock",
    type: "prop",
    icon: "fa-mountain",
    modelPath: "/models/ocean/rock_3.glb",
    fallbackGeometry: "sphere",
    defaultScale: 1.1,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x3a5544,
  },
  {
    key: "rock-4",
    name: "Boulder",
    type: "prop",
    icon: "fa-mountain",
    modelPath: "/models/ocean/rock_4.glb",
    fallbackGeometry: "sphere",
    defaultScale: 1.6,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x4a5566,
  },
  {
    key: "rock-5",
    name: "Cluster Rock",
    type: "prop",
    icon: "fa-mountain",
    modelPath: "/models/ocean/rock_5.glb",
    fallbackGeometry: "box",
    defaultScale: 1.3,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x3b4a5a,
  },
];

// ─────────────────────────────────────────────────────────────
// MESHY FORMATIONS
// ─────────────────────────────────────────────────────────────
const formationItems: ObjectDefinition[] = [
  {
    key: "meshy-basalt-pinnacle",
    name: "Basalt Pinnacle",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/basalt_pinnacle.glb",
    fallbackGeometry: "cone",
    defaultScale: 2.0,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x2a3344,
  },
  {
    key: "meshy-coral-encrusted-rock",
    name: "Coral-Encrusted Rock",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/coral_encrusted_rock.glb",
    fallbackGeometry: "sphere",
    defaultScale: 1.5,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xdd7744,
  },
  {
    key: "meshy-coral-mountain",
    name: "Coral Mountain",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/coral_mountain.glb",
    fallbackGeometry: "cone",
    defaultScale: 2.5,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff7755,
  },
  {
    key: "meshy-neon-coral-summit",
    name: "Neon Coral Summit",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/neon_coral_summit.glb",
    fallbackGeometry: "cone",
    defaultScale: 2.2,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff44cc,
  },
  {
    key: "meshy-submerged-coral-citadel",
    name: "Submerged Coral Citadel",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/submerged_coral_citadel.glb",
    fallbackGeometry: "box",
    defaultScale: 3.0,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xcc5566,
  },
  {
    key: "meshy-sunlit-coral-arch",
    name: "Sunlit Coral Arch",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/sunlit_coral_arch.glb",
    fallbackGeometry: "cylinder",
    defaultScale: 2.0,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xffaa55,
  },
  {
    key: "meshy-underwater-coral-arch",
    name: "Underwater Coral Arch",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/underwater_coral_arch.glb",
    fallbackGeometry: "cylinder",
    defaultScale: 2.2,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xee8855,
  },
  {
    key: "meshy-underwater-rock-table",
    name: "Underwater Rock Table",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/underwater_rock_table.glb",
    fallbackGeometry: "box",
    defaultScale: 1.8,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x445566,
  },
  {
    key: "meshy-photorealistic-coral-0",
    name: "Photorealistic Coral A",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/photorealistic_coral_0.glb",
    fallbackGeometry: "sphere",
    defaultScale: 1.4,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff6655,
  },
  {
    key: "meshy-photorealistic-coral-1",
    name: "Photorealistic Coral B",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/photorealistic_coral_1.glb",
    fallbackGeometry: "sphere",
    defaultScale: 1.4,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xdd7766,
  },
  {
    key: "meshy-photorealistic-coral-2",
    name: "Photorealistic Coral C",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/photorealistic_coral_2.glb",
    fallbackGeometry: "sphere",
    defaultScale: 1.4,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xee8844,
  },
  {
    key: "meshy-photorealistic-coral-3",
    name: "Photorealistic Coral D",
    type: "prop",
    icon: "fa-gem",
    modelPath: "/models/ocean/meshy/photorealistic_coral_3.glb",
    fallbackGeometry: "sphere",
    defaultScale: 1.4,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0xff9966,
  },
];

const currentCompositionItems: ObjectDefinition[] = [
  {
    key: "meshy-sea-grass",
    name: "Sea Grass",
    type: "prop",
    icon: "fa-leaf",
    modelPath: "/models/ocean/meshy/sea_grass.glb",
    fallbackGeometry: "cone",
    defaultScale: 1,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x3d8f64,
  },
  {
    key: "meshy-tall-kelp",
    name: "Tall Kelp",
    type: "prop",
    icon: "fa-leaf",
    modelPath: "/models/ocean/meshy/tall_kelp.glb",
    fallbackGeometry: "cylinder",
    defaultScale: 1,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x23734c,
  },
  ...[
    ["ph-boulder-01", "Boulder", "/models/ocean/polyhaven/boulder_01.glb"],
    [
      "ph-coast-rocks-05",
      "Coast Rocks",
      "/models/ocean/polyhaven/coast_rocks_05.glb",
    ],
    ["ph-rock-07", "Reef Rock", "/models/ocean/polyhaven/rock_07.glb"],
    [
      "ph-sand-rocks",
      "Sand Rocks",
      "/models/ocean/polyhaven/sand_rocks_small_01.glb",
    ],
    ["ph-stone-01", "Seabed Stone", "/models/ocean/polyhaven/stone_01.glb"],
  ].map(([key, name, modelPath]) => ({
    key,
    name,
    type: "prop" as const,
    icon: "fa-mountain",
    modelPath,
    fallbackGeometry: "sphere" as const,
    defaultScale: 1,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x526270,
  })),
  ...[
    [
      "struct-coral-arch",
      "Coral Arch",
      "/models/ocean/structures/coral-arch.glb",
    ],
    [
      "struct-coral-bommie",
      "Coral Bommie",
      "/models/ocean/structures/coral-bommie.glb",
    ],
    [
      "struct-coral-tower",
      "Coral Tower",
      "/models/ocean/structures/coral-tower.glb",
    ],
    ["struct-reef-wall", "Reef Wall", "/models/ocean/structures/reef-wall.glb"],
  ].map(([key, name, modelPath]) => ({
    key,
    name,
    type: "prop" as const,
    icon: "fa-archway",
    modelPath,
    fallbackGeometry: "box" as const,
    defaultScale: 1,
    defaultHeight: 0,
    snapToGround: true,
    canRotate: true,
    canScale: true,
    color: 0x765c58,
  })),
];

// ─────────────────────────────────────────────────────────────
// CATALOG ASSEMBLY
// ─────────────────────────────────────────────────────────────
const categories: CatalogCategory[] = [
  { id: "corals", label: "Corals", icon: "fa-circle-nodes", items: coralItems },
  { id: "flora", label: "Flora", icon: "fa-leaf", items: floraItems },
  {
    id: "decorations",
    label: "Decorations",
    icon: "fa-star",
    items: decorationItems,
  },
  { id: "rocks", label: "Rocks", icon: "fa-mountain", items: rockItems },
  {
    id: "formations",
    label: "Formations",
    icon: "fa-gem",
    items: formationItems,
  },
  {
    id: "composition",
    label: "Current Composition",
    icon: "fa-layer-group",
    items: currentCompositionItems,
  },
];

const allItems = categories.flatMap((c) => c.items);

const catalog: ComposerCatalog = {
  categories,
  getDefinition(key: string) {
    return allItems.find((d) => d.key === key);
  },
  allItems() {
    return allItems;
  },
};

const surfaceRules: SurfaceRules = {
  isSurface(mesh: Mesh): boolean {
    const name = (mesh.name ?? "").toLowerCase();
    return (
      name.includes("terrain") ||
      name.includes("seabed") ||
      name.includes("ground")
    );
  },
  orientationMode: "upright",
  gridSize: null,
  surfaceOffset: 0.02,
};

const constraints: PlacementConstraints = {
  maxObjects: 400,
  minSpacing: 0.8,
  exclusionZones: [
    {
      center: [0, 0, 0],
      radius: 5,
      reason: "Performance stage — keep clear for performers",
    },
  ],
};

const nativeObjects = createMetadataSceneObjectAdapter({
  sceneId: "ocean",
  editableRoles: new Set([
    "coral",
    "flora",
    "rock",
    "reef-structure",
    "decoration",
  ]),
  lockedRoles: new Set(["terrain", "seabed", "stage", "water"]),
  editableNamePatterns: [
    /coral|kelp|seaweed|grass|anemone|starfish|urchin|shell|rock/i,
  ],
  lockedNamePatterns: [
    /terrain|seabed|ground|water|dais|stage|platform|light/i,
  ],
  editableInstancePatterns: [
    /coral|kelp|seaweed|grass|anemone|starfish|urchin|shell|rock/i,
  ],
});

const oceanPlugin: SceneComposerPlugin = {
  sceneId: "ocean",
  displayName: "Ocean Seabed",
  catalog,
  surfaceRules,
  getDefaults: () => [...OCEAN_PLACEMENTS],
  constraints,
  nativeObjects,
};

composerRegistry.register(oceanPlugin);

export { oceanPlugin };
