export const ANIMATION_CONSTANTS = {
  DEFAULT_CANVAS_RADIUS: 200,
  DEFAULT_PROP_SCALE: 0.4,
  DEFAULT_PATH_RADIUS_RATIO: 0.4,
  DEFAULT_CANVAS_WIDTH: 500,
  DEFAULT_CANVAS_HEIGHT: 500,

  GRID_VIEWBOX_SIZE: 950,
  GRID_CENTER: 475,
  GRID_HALFWAY_POINT_OFFSET: 151.5,

  DEFAULT_ANIMATION_SPEED: 1.0,
  MIN_ANIMATION_SPEED: 0.1,
  MAX_ANIMATION_SPEED: 3.0,
  SPEED_STEP: 0.1,

  STAFF_VIEWBOX_WIDTH: 252.8,
  STAFF_VIEWBOX_HEIGHT: 77.8,
  STAFF_CENTER_X: 126.4,
  STAFF_CENTER_Y: 38.9,
  STAFF_WIDTH: 80,
  STAFF_HEIGHT: 80,
  STAFF_THICKNESS: 5,
  STAFF_BORDER_RADIUS: 2,
  CENTER_DOT_RADIUS: 4,

  GRID_STROKE_WIDTH: 1,
  GRID_FONT_SIZE: 14,
  GRID_FONT_FAMILY: "sans-serif",
  GRID_LABEL_OFFSET: 5,

  TARGET_FPS: 60,
  FRAME_TIME_MS: 1000 / 60,

  RENDER_THROTTLE_MS: 16,
  DEBOUNCE_INPUT_MS: 300,
} as const;
