import { AVATAR_DEFINITIONS } from "@austencloud/scene-3d";
import type { CharacterDefinition, CharacterId } from "./character-model";

/**
 * A controlled body-proportion sweep for the staff-grip lab.
 *
 * The twelve deployed catalog rigs vary every dimension at once, so when one
 * fails the hug fit there is no way to say whether stature, arm length or
 * shoulder span caused it. Four of the twelve already fail. These ten bodies
 * are one licensed base rig (`ch12`, the catalog median for reach) with exactly
 * one dimension moved per body, so a failure names its own cause.
 *
 * Generated by `pnpm run characters:proportion-sweep`. The GLBs live under
 * `static/models/avatars/proportion-sweep/`, which is gitignored in full, so a
 * checkout without them simply has no sweep. Every entry is
 * `availability: "local-evaluation"` and none can reach a production build or
 * the deployed CDN catalog.
 *
 * The measured block is what the runtime reports, not what the parameters
 * intended: it is read off each GLB's authored rest pose through the same
 * `AvatarSkeletonBuilder` mapping and the same `performer-reach-measurements`
 * arithmetic the browser uses, so a body that claims to be tall and measures
 * median is caught rather than shipped.
 */
export interface ProportionSweepCharacter extends CharacterDefinition {
  /** The single dimension this body moves away from the median. */
  axis:
    | "none"
    | "stature"
    | "shoulderWidth"
    | "armLength"
    | "armSegmentRatio"
    | "torsoGirth";
  /** Multipliers handed to the Blender rescale stage; empty for the median. */
  parameters: Readonly<Record<string, number>>;
  /** What the solve actually measures off this body. Centimetres. */
  measured: {
    statureCm: number;
    upperArmCm: number;
    forearmCm: number;
    reachCm: number;
    shoulderWidthCm: number;
    /**
     * Lateral foot separation. Not a solve input, a tripwire. A Blender bake
     * that freezes the catalog rigs' Mixamo clip instead of their bind pose
     * collapses this onto the hip separation, and nothing else here notices.
     */
    footSeparationCm: number;
    hugLaneCm: number;
    hugForwardCm: number;
    /** Recommended length when it fits, otherwise the maximum that would. */
    staffCm: number;
    staffFits: boolean;
  };
}

export const PROPORTION_SWEEP_BASE_CHARACTER_ID = "ch12" as CharacterId;

export const PROPORTION_SWEEP_CHARACTERS: readonly ProportionSweepCharacter[] =
  [
    {
      id: "sweep-median" as CharacterId,
      name: "Median",
      modelPath: "/models/avatars/proportion-sweep/sweep-median.glb",
      description:
        "The control. Every other body is this one with a single dimension moved.",
      availability: "local-evaluation",
      axis: "none",
      parameters: {},
      measured: {
        statureCm: 160.4,
        upperArmCm: 26.98,
        forearmCm: 21.92,
        reachCm: 48.91,
        shoulderWidthCm: 39.77,
        footSeparationCm: 29.52,
        hugLaneCm: 10.54,
        hugForwardCm: 48.01,
        staffCm: 62.1,
        staffFits: true,
      },
    },
    {
      id: "sweep-stature-short" as CharacterId,
      name: "Stature short",
      modelPath: "/models/avatars/proportion-sweep/sweep-stature-short.glb",
      description:
        "Uniform 0.90 scale. Segment ratios are untouched, so the fit should scale linearly rather than change character.",
      availability: "local-evaluation",
      axis: "stature",
      parameters: { statureScale: 0.9 },
      measured: {
        statureCm: 144.4,
        upperArmCm: 24.29,
        forearmCm: 19.73,
        reachCm: 44.02,
        shoulderWidthCm: 35.79,
        footSeparationCm: 26.57,
        hugLaneCm: 9.48,
        hugForwardCm: 43.2,
        staffCm: 54.7,
        staffFits: false,
      },
    },
    {
      id: "sweep-stature-tall" as CharacterId,
      name: "Stature tall",
      modelPath: "/models/avatars/proportion-sweep/sweep-stature-tall.glb",
      description:
        "Uniform 1.10 scale. Pairs with the short body to show absolute size alone is not what breaks the solve.",
      availability: "local-evaluation",
      axis: "stature",
      parameters: { statureScale: 1.1 },
      measured: {
        statureCm: 176.5,
        upperArmCm: 29.68,
        forearmCm: 24.11,
        reachCm: 53.8,
        shoulderWidthCm: 43.75,
        footSeparationCm: 32.47,
        hugLaneCm: 11.59,
        hugForwardCm: 52.81,
        staffCm: 69.6,
        staffFits: true,
      },
    },
    {
      id: "sweep-shoulders-narrow" as CharacterId,
      name: "Shoulders narrow",
      modelPath: "/models/avatars/proportion-sweep/sweep-shoulders-narrow.glb",
      description:
        "Arm-chain roots drawn in to 0.85 span with reach held constant. Isolates shoulder span from every other dimension.",
      availability: "local-evaluation",
      axis: "shoulderWidth",
      parameters: { shoulderWidthScale: 0.85 },
      measured: {
        statureCm: 160.4,
        upperArmCm: 26.98,
        forearmCm: 21.92,
        reachCm: 48.91,
        shoulderWidthCm: 33.8,
        footSeparationCm: 29.52,
        hugLaneCm: 8.96,
        hugForwardCm: 48.26,
        staffCm: 65.9,
        staffFits: true,
      },
    },
    {
      id: "sweep-shoulders-broad" as CharacterId,
      name: "Shoulders broad",
      modelPath: "/models/avatars/proportion-sweep/sweep-shoulders-broad.glb",
      description:
        "Arm-chain roots pushed out to 1.15 span with reach held constant. The hug lane and the derived torso depth both widen while the arms stay the same length.",
      availability: "local-evaluation",
      axis: "shoulderWidth",
      parameters: { shoulderWidthScale: 1.15 },
      measured: {
        statureCm: 160.4,
        upperArmCm: 26.98,
        forearmCm: 21.92,
        reachCm: 48.91,
        shoulderWidthCm: 45.73,
        footSeparationCm: 29.52,
        hugLaneCm: 12.12,
        hugForwardCm: 47.71,
        staffCm: 58.3,
        staffFits: false,
      },
    },
    {
      id: "sweep-arms-short" as CharacterId,
      name: "Arms short",
      modelPath: "/models/avatars/proportion-sweep/sweep-arms-short.glb",
      description:
        "Both arm segments at 0.88 with stature and shoulder span fixed. Isolates arm length relative to stature.",
      availability: "local-evaluation",
      axis: "armLength",
      parameters: { upperArmScale: 0.88, forearmScale: 0.88 },
      measured: {
        statureCm: 160.4,
        upperArmCm: 23.75,
        forearmCm: 19.29,
        reachCm: 43.04,
        shoulderWidthCm: 39.77,
        footSeparationCm: 29.52,
        hugLaneCm: 10.54,
        hugForwardCm: 42.01,
        staffCm: 50.1,
        staffFits: false,
      },
    },
    {
      id: "sweep-arms-long" as CharacterId,
      name: "Arms long",
      modelPath: "/models/avatars/proportion-sweep/sweep-arms-long.glb",
      description:
        "Both arm segments at 1.12 with stature and shoulder span fixed. Pairs with the short-arm body across the fit boundary.",
      availability: "local-evaluation",
      axis: "armLength",
      parameters: { upperArmScale: 1.12, forearmScale: 1.12 },
      measured: {
        statureCm: 160.4,
        upperArmCm: 30.22,
        forearmCm: 24.55,
        reachCm: 54.78,
        shoulderWidthCm: 39.77,
        footSeparationCm: 29.52,
        hugLaneCm: 10.54,
        hugForwardCm: 53.97,
        staffCm: 74.1,
        staffFits: true,
      },
    },
    {
      id: "sweep-arms-elbow-high" as CharacterId,
      name: "Arms, elbow high",
      modelPath: "/models/avatars/proportion-sweep/sweep-arms-elbow-high.glb",
      description:
        "Long upper arm, short forearm, total reach held at the median. The solve consumes only the sum, so this body should measure a different elbow and an identical fit. A changed fit here would mean the solve is reading something it does not declare.",
      availability: "local-evaluation",
      axis: "armSegmentRatio",
      parameters: { upperArmScale: 1.25, forearmScale: 0.6928 },
      measured: {
        statureCm: 160.4,
        upperArmCm: 33.73,
        forearmCm: 15.19,
        reachCm: 48.92,
        shoulderWidthCm: 39.77,
        footSeparationCm: 29.52,
        hugLaneCm: 10.54,
        hugForwardCm: 48.02,
        staffCm: 62.2,
        staffFits: true,
      },
    },
    {
      id: "sweep-build-slight" as CharacterId,
      name: "Build slight",
      modelPath: "/models/avatars/proportion-sweep/sweep-build-slight.glb",
      description:
        "Chest thinned to 0.88. The solve derives torso depth from shoulder width rather than measuring the body, so this should not move the fit at all.",
      availability: "local-evaluation",
      axis: "torsoGirth",
      parameters: { torsoGirthScale: 0.88 },
      measured: {
        statureCm: 160.4,
        upperArmCm: 26.98,
        forearmCm: 21.92,
        reachCm: 48.91,
        shoulderWidthCm: 39.77,
        footSeparationCm: 29.52,
        hugLaneCm: 10.54,
        hugForwardCm: 48.01,
        staffCm: 62.1,
        staffFits: true,
      },
    },
    {
      id: "sweep-build-heavy" as CharacterId,
      name: "Build heavy",
      modelPath: "/models/avatars/proportion-sweep/sweep-build-heavy.glb",
      description:
        "Chest thickened to 1.20. Pairs with the slight build to demonstrate that a visibly deeper torso is invisible to the current staff fit.",
      availability: "local-evaluation",
      axis: "torsoGirth",
      parameters: { torsoGirthScale: 1.2 },
      measured: {
        statureCm: 160.4,
        upperArmCm: 26.98,
        forearmCm: 21.92,
        reachCm: 48.91,
        shoulderWidthCm: 39.77,
        footSeparationCm: 29.52,
        hugLaneCm: 10.54,
        hugForwardCm: 48.01,
        staffCm: 62.1,
        staffFits: true,
      },
    },
  ];

/**
 * Register the sweep with the catalog owner so the production load path can
 * resolve these ids.
 *
 * This mirrors how the lab already registers its intake rig: the sweep stays
 * out of the deployable catalog, and a local-only route opts in. Calling this
 * more than once is safe.
 */
export function registerProportionSweepCharacters(): readonly ProportionSweepCharacter[] {
  for (const character of PROPORTION_SWEEP_CHARACTERS) {
    if (AVATAR_DEFINITIONS.some(({ id }) => id === character.id)) continue;
    AVATAR_DEFINITIONS.push(character);
  }
  return PROPORTION_SWEEP_CHARACTERS;
}
