<!--
  Mandala Match — one mandala, pick the CHOREO CARD that made it.

  Question: a real performed sequence rendered as a mandala (SequenceMandala,
  ResizeObserver-sized like MandalaPane). Answers: real choreo cards
  (ChoreoCard — the same card faces the deck products print), one per
  candidate sequence, generated by generateSequenceMatchQuestion from the
  8-count catalog pool. Reading a mandala back to its notation is the whole
  skill; words on the cards are labels, not answers.

  No misconception-hint pass here: gap detection is letter-based and has no
  signal for whole-sequence matching.
-->
<script lang="ts">
  import { getHapticFeedback } from "$lib/shared/application/get-haptic-feedback";
  import type { HapticFeedback } from "$lib/shared/application/services/haptic-feedback";
  import { onDestroy, onMount } from "svelte";
  import { generateSequenceMatchQuestion } from "../../quiz/services/sequence-question-generator";
  import { QuizType } from "../../quiz/domain/enums/quiz-enums";
  import type { QuizAnswerOption, QuizQuestionData } from "../../quiz/domain/models/quiz-models";
  import type { SequenceData } from "$lib/shared/foundation/domain/models/sequence-data";
  import { simplifyRepeatedWord } from "$lib/shared/foundation/utils/word-simplifier";
  import QuizContainer from "../../quiz/components/shared/QuizContainer.svelte";
  import QuizLoadingState from "../../quiz/components/shared/QuizLoadingState.svelte";
  import QuizErrorState from "../../quiz/components/shared/QuizErrorState.svelte";
  import QuizPrompt from "../../quiz/components/shared/QuizPrompt.svelte";
  import QuizFeedbackBanner from "../../quiz/components/shared/QuizFeedbackBanner.svelte";
  import ScorePopAnimation from "../../quiz/components/shared/ScorePopAnimation.svelte";
  import SequenceMandala from "$lib/shared/mandala/components/SequenceMandala.svelte";
  import ChoreoCard from "$lib/features/choreo-card/components/ChoreoCard.svelte";
  import { reducedMotion } from "$lib/shared/transitions/motion";
  import { getArcadeSession } from "../state/arcade-session-state.svelte";
  import type { QuestionConstraints } from "../domain/arcade-types";

  let { constraints }: { constraints: QuestionConstraints } = $props();

  const session = getArcadeSession();
  let hapticService: HapticFeedback;

  let scorePopTimer: ReturnType<typeof setTimeout> | null = null;
  let hapticTimer: ReturnType<typeof setTimeout> | null = null;
  let nextQuestionTimer: ReturnType<typeof setTimeout> | null = null;

  onDestroy(() => {
    if (scorePopTimer !== null) clearTimeout(scorePopTimer);
    if (hapticTimer !== null) clearTimeout(hapticTimer);
    if (nextQuestionTimer !== null) clearTimeout(nextQuestionTimer);
  });

  let questionData = $state<QuizQuestionData | null>(null);
  let selectedAnswerId = $state<string | null>(null);
  let isAnswered = $state(false);
  let showFeedback = $state(false);
  let isInitialLoading = $state(true);
  let error = $state<string | null>(null);
  let showScorePop = $state(false);

  const levelNumber = $derived(
    session.phase.name === "playing" ? session.phase.level.levelNumber : 1
  );
  const animateMandala = !reducedMotion();

  let stageEl = $state<HTMLDivElement | undefined>();
  let stageSize = $state(280);

  $effect(() => {
    if (!stageEl) return;
    const observer = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (!entry) return;
      const { width, height } = entry.contentRect;
      stageSize = Math.max(120, Math.floor(Math.min(width, height)));
    });
    observer.observe(stageEl);
    return () => observer.disconnect();
  });

  let currentSequence = $derived(
    questionData?.questionContent as SequenceData | null
  );
  let correctWord = $derived.by(() => {
    const correct = questionData?.answerOptions.find((o) => o.isCorrect);
    const seq = correct?.content as SequenceData | undefined;
    return seq ? simplifyRepeatedWord(seq.word) : "";
  });
  let isCorrectAnswer = $derived(
    selectedAnswerId
      ? (questionData?.answerOptions.find((o) => o.id === selectedAnswerId)
          ?.isCorrect ?? false)
      : false
  );

  onMount(async () => {
    hapticService = getHapticFeedback();
    await loadQuestion();
  });

  async function loadQuestion() {
    error = null;
    try {
      questionData = await generateSequenceMatchQuestion(generateQuestionId(), {
        optionCount: constraints.optionCount,
        stepCount: constraints.stepCount,
        similarDistractors: levelNumber === 3,
        lessonType: QuizType.MANDALA_TO_CARD,
      });
      session.markQuestionShown();
    } catch (err) {
      console.error("Failed to load question:", err);
      error = err instanceof Error ? err.message : "Failed to load question";
    } finally {
      isInitialLoading = false;
    }
  }

  function generateQuestionId(): string {
    return `q_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
  }

  function handleCardPick(option: QuizAnswerOption) {
    if (isAnswered || !questionData) return;
    hapticService?.trigger("selection");
    selectedAnswerId = option.id;
    isAnswered = true;
    showFeedback = true;

    const isCorrect = option.isCorrect;
    if (isCorrect) {
      showScorePop = true;
      scorePopTimer = setTimeout(() => {
        showScorePop = false;
      }, 800);
    }

    hapticTimer = setTimeout(() => {
      hapticService?.trigger(isCorrect ? "success" : "error");
    }, 100);

    const picked = option.content as SequenceData;
    session.submitAnswer({
      isCorrect,
      questionData,
      selectedOptionId: option.id,
      selectedContent: simplifyRepeatedWord(picked.word),
      correctContent: correctWord,
      quizType: QuizType.MANDALA_TO_CARD,
      answeredAt: new Date(),
    });

    nextQuestionTimer = setTimeout(handleNextQuestion, 1600);
  }

  async function handleNextQuestion() {
    if (session.phase.name !== "playing") return;
    selectedAnswerId = null;
    isAnswered = false;
    showFeedback = false;
    await loadQuestion();
  }

  function cardState(option: QuizAnswerOption): "default" | "correct" | "incorrect" | "dimmed" {
    if (!isAnswered) return "default";
    if (option.isCorrect) return "correct";
    if (option.id === selectedAnswerId) return "incorrect";
    return "dimmed";
  }
</script>

{#if isInitialLoading}
  <QuizContainer>
    <QuizLoadingState />
  </QuizContainer>
{:else if error}
  <QuizContainer>
    <QuizErrorState {error} onRetry={loadQuestion} />
  </QuizContainer>
{:else if questionData && currentSequence}
  <QuizContainer>
    <QuizPrompt text="One mandala. Pick the card that made it." />

    <div class="quiz-content">
      <div class="stage-column">
        <div class="mandala-stage" bind:this={stageEl}>
          <SequenceMandala
            sequence={currentSequence}
            mode="gallery"
            size={stageSize}
            animate={animateMandala}
            animatePeriod={9}
            animateMin={100}
            animateMax={180}
            animateEasing="breathe"
            animateRotation={0}
          />
        </div>
        <ScorePopAnimation
          visible={showScorePop}
          score={1}
          streakCount={session.streak}
        />
        {#if showFeedback}
          <QuizFeedbackBanner
            isCorrect={isCorrectAnswer}
            correctMessage={`Correct! That card spells "${correctWord}"`}
            incorrectMessage={`The card that made it spells "${correctWord}"`}
            streakCount={session.streak}
          />
        {/if}
      </div>

      <div class="card-grid" class:six-up={(constraints.optionCount ?? 4) > 4}>
        {#each questionData.answerOptions as option (option.id)}
          <div class="card-slot state-{cardState(option)}">
            <ChoreoCard
              sequence={option.content as SequenceData}
              showQRCodes={false}
              onSelect={() => handleCardPick(option)}
            />
          </div>
        {/each}
      </div>
    </div>
  </QuizContainer>
{/if}

<style>
  .quiz-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1.25rem;
    width: 100%;
    max-width: 480px;
    flex: 1;
    min-height: 0;
  }

  .stage-column {
    container-type: size;
    position: relative;
    width: 100%;
    flex: 1;
    min-height: 180px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
  }

  .mandala-stage {
    position: relative;
    aspect-ratio: 1;
    inline-size: min(52cqh, 80cqw, 380px);
    min-inline-size: 140px;
    border-radius: 20px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: radial-gradient(
      circle,
      color-mix(in srgb, var(--game-accent, var(--theme-accent)) 14%, transparent),
      transparent 70%
    );
  }

  /* Height-filling grid: rows share the available height (1fr) and each card
     slot is the largest 2.5:3.5 card that fits its cell, so a 2×2 (or 3×2)
     block of tall choreo cards shrinks to fit instead of running off the
     bottom of the screen. Parent must be height-bounded (portrait flex below /
     desktop stretch) for this to clamp. */
  .card-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    grid-template-rows: repeat(2, 1fr);
    gap: 0.75rem;
    width: 100%;
    height: 100%;
    min-height: 0;
    place-content: center;
    flex: 1 1 auto;
  }

  .card-grid.six-up {
    grid-template-columns: repeat(3, 1fr);
  }

  /* Feedback grammar on whole cards: accent ring on the answer, red ring on
     a wrong pick, the rest fall back. ChoreoCard is its own button; the slot
     paints state around it without touching its internals. */
  .card-slot {
    position: relative;
    aspect-ratio: 2.5 / 3.5;
    max-width: 100%;
    max-height: 100%;
    height: 100%;
    margin: auto;
    border-radius: 14px;
    transition:
      opacity var(--duration-normal, 200ms) ease,
      box-shadow var(--duration-normal, 200ms) ease;
  }

  .card-slot.state-correct {
    box-shadow:
      0 0 0 2px var(--game-accent, #fbbf24),
      0 0 20px color-mix(in srgb, var(--game-accent, #fbbf24) 40%, transparent);
  }

  .card-slot.state-incorrect {
    box-shadow: 0 0 0 2px var(--semantic-error, #ef4444);
  }

  .card-slot.state-dimmed {
    opacity: 0.4;
  }

  /* Desktop: mandala left, cards right. */
  @media (min-width: 768px) {
    .quiz-content {
      flex-direction: row;
      align-items: stretch;
      max-width: 1000px;
      gap: 2rem;
    }

    .stage-column {
      flex: 1;
      min-height: 340px;
    }

    .card-grid {
      flex: 0 0 380px;
      align-content: center;
    }

    .card-grid.six-up {
      flex-basis: 480px;
    }
  }

  @media (min-width: 1440px) {
    .quiz-content {
      max-width: 1300px;
      gap: 2.5rem;
    }

    .card-grid {
      flex-basis: 460px;
    }

    .card-grid.six-up {
      flex-basis: 580px;
    }
  }

  @media (min-width: 2560px) {
    .quiz-content {
      max-width: clamp(1300px, 55vw, 1700px);
    }

    .mandala-stage {
      inline-size: min(56cqh, 80cqw, 560px);
    }

    .card-grid {
      flex-basis: 560px;
      gap: 1rem;
    }

    .card-grid.six-up {
      flex-basis: 700px;
    }
  }

  @media (prefers-reduced-motion: reduce) {
    .card-slot {
      transition: none;
    }
  }
</style>
