<!--
  Mandala Match — one mandala, pick the CHOREO CARD that made it.

  Question: a real performed sequence rendered as a mandala (SequenceMandala,
  ResizeObserver-sized like MandalaPane). Answers: real choreo cards
  (ChoreoCard — the same card faces the deck products print), one per
  candidate sequence, generated by generateSequenceMatchQuestion from the
  8-count catalog pool. Reading a mandala back to its notation is the whole
  skill; words on the cards are labels, not answers.

  No misconception-hint pass here: gap detection is letter-based and has no
  signal for whole-sequence matching.
-->
<script lang="ts">
  import { getHapticFeedback } from "$lib/shared/application/get-haptic-feedback";
  import type { HapticFeedback } from "$lib/shared/application/services/haptic-feedback";
  import { onDestroy, onMount } from "svelte";
  import { generateSequenceMatchQuestion } from "../../quiz/services/sequence-question-generator";
  import { QuizType } from "../../quiz/domain/enums/quiz-enums";
  import type { QuizAnswerOption, QuizQuestionData } from "../../quiz/domain/models/quiz-models";
  import type { SequenceData } from "$lib/shared/foundation/domain/models/sequence-data";
  import { simplifyRepeatedWord } from "$lib/shared/foundation/utils/word-simplifier";
  import QuizContainer from "../../quiz/components/shared/QuizContainer.svelte";
  import QuizLoadingState from "../../quiz/components/shared/QuizLoadingState.svelte";
  import QuizErrorState from "../../quiz/components/shared/QuizErrorState.svelte";
  import QuizPrompt from "../../quiz/components/shared/QuizPrompt.svelte";
  import QuizFeedbackBanner from "../../quiz/components/shared/QuizFeedbackBanner.svelte";
  import ScorePopAnimation from "../../quiz/components/shared/ScorePopAnimation.svelte";
  import SequenceMandala from "$lib/shared/mandala/components/SequenceMandala.svelte";
  import ChoreoCard from "$lib/features/choreo-card/components/ChoreoCard.svelte";
  import { reducedMotion } from "$lib/shared/transitions/motion";
  import { getArcadeSession } from "../state/arcade-session-state.svelte";
  import type { QuestionConstraints } from "../domain/arcade-types";

  let { constraints }: { constraints: QuestionConstraints } = $props();

  const session = getArcadeSession();
  let hapticService: HapticFeedback;

  let scorePopTimer: ReturnType<typeof setTimeout> | null = null;
  let hapticTimer: ReturnType<typeof setTimeout> | null = null;
  let nextQuestionTimer: ReturnType<typeof setTimeout> | null = null;

  onDestroy(() => {
    if (scorePopTimer !== null) clearTimeout(scorePopTimer);
    if (hapticTimer !== null) clearTimeout(hapticTimer);
    if (nextQuestionTimer !== null) clearTimeout(nextQuestionTimer);
  });

  let questionData = $state<QuizQuestionData | null>(null);
  let selectedAnswerId = $state<string | null>(null);
  let isAnswered = $state(false);
  let showFeedback = $state(false);
  let isInitialLoading = $state(true);
  let error = $state<string | null>(null);
  let showScorePop = $state(false);

  const levelNumber = $derived(
    session.phase.name === "playing" ? session.phase.level.levelNumber : 1
  );
  const animateMandala = !reducedMotion();

  let stageEl = $state<HTMLDivElement | undefined>();
  let stageSize = $state(280);

  $effect(() => {
    if (!stageEl) return;
    const observer = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (!entry) return;
      const { width, height } = entry.contentRect;
      stageSize = Math.max(120, Math.floor(Math.min(width, height)));
    });
    observer.observe(stageEl);
    return () => observer.disconnect();
  });

  /* Deterministic card sizing (mirrors MandalaOptionGrid): each card is the
     largest that fits its grid cell, capped so it sits at a natural size and
     centers rather than stretching to fill the column (which left giant white
     voids inside each card). The height/width ratio is MEASURED from the first
     rendered card (the wordcard renders to its natural image aspect — with no
     start-position row it's landscape, not poker portrait), so byHeight stops
     under-sizing the cards. Ratio-from-measurement converges: it's a constant
     of the card content, not of the chosen width. */
  const cardCount = $derived(constraints.optionCount ?? 4);
  let cardGridEl = $state<HTMLDivElement | undefined>();
  let cardWidth = $state(170);
  let cardCols = $state(2);
  let cardRatio = $state(0.75); // height / width — refined by measurement
  const CARD_GAP = 12; // px — matches gap in CSS
  const CARD_MAX = 380;

  $effect(() => {
    if (!cardGridEl) return;
    const n = cardCount;
    const measure = () => {
      if (!cardGridEl) return;
      const slot = cardGridEl.querySelector<HTMLElement>(".card-slot");
      if (slot && slot.clientWidth > 0 && slot.clientHeight > 0) {
        const r = slot.clientHeight / slot.clientWidth;
        if (Math.abs(r - cardRatio) > 0.02) cardRatio = r;
      }
      const w = cardGridEl.clientWidth;
      const h = cardGridEl.clientHeight;
      /* Adaptive columns: try every column count and keep whichever yields
         the biggest card. A narrow phone lands on 1 column (wide cards
         stacked), a folded Fold on 2×2, a desktop on a single 4-across row —
         no per-breakpoint layout forks. */
      let bestW = 0;
      let bestCols = Math.min(2, n);
      for (let cols = 1; cols <= n; cols++) {
        const rows = Math.ceil(n / cols);
        const byWidth = (w - (cols - 1) * CARD_GAP) / cols;
        const byHeight =
          h > 0 ? (h - (rows - 1) * CARD_GAP) / rows / cardRatio : Infinity;
        const candidate = Math.min(byWidth, byHeight, CARD_MAX);
        if (candidate > bestW + 0.5) {
          bestW = candidate;
          bestCols = cols;
        }
      }
      cardCols = bestCols;
      cardWidth = Math.max(96, bestW | 0);
    };
    const ro = new ResizeObserver(measure);
    ro.observe(cardGridEl);
    /* Also watch the first slot: its height changes when the card image
       finishes loading (async), which never resizes the grid itself — without
       this the measured ratio goes stale and the cards overflow. */
    let observedSlot: HTMLElement | null = null;
    const watchSlot = () => {
      const slot = cardGridEl?.querySelector<HTMLElement>(".card-slot") ?? null;
      if (slot && slot !== observedSlot) {
        if (observedSlot) ro.unobserve(observedSlot);
        ro.observe(slot);
        observedSlot = slot;
      }
    };
    const mo = new MutationObserver(() => watchSlot());
    mo.observe(cardGridEl, { childList: true });
    watchSlot();
    measure();
    return () => {
      ro.disconnect();
      mo.disconnect();
    };
  });

  let currentSequence = $derived(
    questionData?.questionContent as SequenceData | null
  );
  let correctWord = $derived.by(() => {
    const correct = questionData?.answerOptions.find((o) => o.isCorrect);
    const seq = correct?.content as SequenceData | undefined;
    return seq ? simplifyRepeatedWord(seq.word) : "";
  });
  let isCorrectAnswer = $derived(
    selectedAnswerId
      ? (questionData?.answerOptions.find((o) => o.id === selectedAnswerId)
          ?.isCorrect ?? false)
      : false
  );

  onMount(async () => {
    hapticService = getHapticFeedback();
    await loadQuestion();
  });

  async function loadQuestion() {
    error = null;
    try {
      questionData = await generateSequenceMatchQuestion(generateQuestionId(), {
        optionCount: constraints.optionCount,
        stepCount: constraints.stepCount,
        similarDistractors: levelNumber === 3,
        lessonType: QuizType.MANDALA_TO_CARD,
      });
      session.markQuestionShown();
    } catch (err) {
      console.error("Failed to load question:", err);
      error = err instanceof Error ? err.message : "Failed to load question";
    } finally {
      isInitialLoading = false;
    }
  }

  function generateQuestionId(): string {
    return `q_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
  }

  function handleCardPick(option: QuizAnswerOption) {
    if (isAnswered || !questionData) return;
    hapticService?.trigger("selection");
    selectedAnswerId = option.id;
    isAnswered = true;
    showFeedback = true;

    const isCorrect = option.isCorrect;
    if (isCorrect) {
      showScorePop = true;
      scorePopTimer = setTimeout(() => {
        showScorePop = false;
      }, 800);
    }

    hapticTimer = setTimeout(() => {
      hapticService?.trigger(isCorrect ? "success" : "error");
    }, 100);

    const picked = option.content as SequenceData;
    session.submitAnswer({
      isCorrect,
      questionData,
      selectedOptionId: option.id,
      selectedContent: simplifyRepeatedWord(picked.word),
      correctContent: correctWord,
      quizType: QuizType.MANDALA_TO_CARD,
      answeredAt: new Date(),
    });

    nextQuestionTimer = setTimeout(handleNextQuestion, 1600);
  }

  async function handleNextQuestion() {
    if (session.phase.name !== "playing") return;
    selectedAnswerId = null;
    isAnswered = false;
    showFeedback = false;
    await loadQuestion();
  }

  function cardState(option: QuizAnswerOption): "default" | "correct" | "incorrect" | "dimmed" {
    if (!isAnswered) return "default";
    if (option.isCorrect) return "correct";
    if (option.id === selectedAnswerId) return "incorrect";
    return "dimmed";
  }
</script>

{#if isInitialLoading}
  <QuizContainer>
    <QuizLoadingState />
  </QuizContainer>
{:else if error}
  <QuizContainer>
    <QuizErrorState {error} onRetry={loadQuestion} />
  </QuizContainer>
{:else if questionData && currentSequence}
  <QuizContainer>
    <QuizPrompt text="One mandala. Pick the card that made it." />

    <div class="quiz-content">
      <div class="stage-column">
        <div class="mandala-stage" bind:this={stageEl}>
          <SequenceMandala
            sequence={currentSequence}
            mode="gallery"
            size={stageSize}
            animate={animateMandala}
            animatePeriod={9}
            animateMin={100}
            animateMax={180}
            animateEasing="breathe"
            animateRotation={0}
          />
        </div>
        <ScorePopAnimation
          visible={showScorePop}
          score={1}
          streakCount={session.streak}
        />
        {#if showFeedback}
          <QuizFeedbackBanner
            isCorrect={isCorrectAnswer}
            correctMessage={`Correct! That card spells "${correctWord}"`}
            incorrectMessage={`The card that made it spells "${correctWord}"`}
            streakCount={session.streak}
          />
        {/if}
      </div>

      <div
        class="card-grid"
        class:six-up={(constraints.optionCount ?? 4) > 4}
        style="--cols: {cardCols}; --cardw: {cardWidth}px"
        bind:this={cardGridEl}
      >
        {#each questionData.answerOptions as option (option.id)}
          <div class="card-slot state-{cardState(option)}">
            <ChoreoCard
              sequence={option.content as SequenceData}
              showQRCodes={false}
              includeStartPosition={false}
              showWord={false}
              showNotes={false}
              showLoopGlyph={false}
              onSelect={() => handleCardPick(option)}
            />
          </div>
        {/each}
      </div>
    </div>
  </QuizContainer>
{/if}

<style>
  /* Stacked (foldable/tablet/phone): mandala over cards, both at natural
     height and centered together as a group — no growing flex regions that
     leave a dead band between them. */
  /* One layout everywhere: big mandala on top, cards below. The card grid's
     column count adapts in JS to whatever space is left, so there is no
     desktop row-split fork — a wide screen just gets one 4-across card row
     under a large mandala. */
  .quiz-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: clamp(1rem, 3svh, 2rem);
    width: 100%;
    max-width: 1600px;
    flex: 1;
    min-height: 0;
  }

  .stage-column {
    position: relative;
    width: 100%;
    flex: 0 0 auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
  }

  .mandala-stage {
    position: relative;
    aspect-ratio: 1;
    inline-size: min(46svh, 86vw, 620px);
    min-inline-size: 140px;
    border-radius: 20px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: radial-gradient(
      circle,
      color-mix(in srgb, var(--game-accent, var(--theme-accent)) 14%, transparent),
      transparent 70%
    );
  }

  /* Cards sized in JS (--cardw) to the largest natural 2.5:3.5 that fits the
     cell, then the block is centered. Bounded height comes from the flex
     parent (portrait) or stretch (desktop) so JS can shrink cards when the
     screen is short; it never stretches them to fill. */
  .card-grid {
    display: grid;
    grid-template-columns: repeat(var(--cols, 2), var(--cardw, 170px));
    gap: 12px;
    width: 100%;
    min-height: 0;
    place-content: center;
    /* Fill the space under the mandala so clientHeight is the space AVAILABLE
       (bounded by the parent), not the grid's own content — content-sized
       height made the JS byHeight measurement self-referential. */
    flex: 1 1 0;
  }

  /* Feedback grammar on whole cards: accent ring on the answer, red ring on
     a wrong pick, the rest fall back. ChoreoCard is its own button; the slot
     paints state around it without touching its internals. */
  /* Natural card aspect (wordcard renders to its own image ratio) — forcing a
     2.5:3.5 poker shape left big white voids above/below the content. Width is
     JS-sized to fit; height follows the content. */
  .card-slot {
    position: relative;
    width: var(--cardw, 170px);
    height: fit-content;
    border-radius: 14px;
    overflow: hidden;
    border: 1px solid rgba(255, 255, 255, 0.14);
    transition:
      opacity var(--duration-normal, 200ms) ease,
      box-shadow var(--duration-normal, 200ms) ease;
  }

  .card-slot.state-correct {
    box-shadow:
      0 0 0 2px var(--game-accent, #fbbf24),
      0 0 20px color-mix(in srgb, var(--game-accent, #fbbf24) 40%, transparent);
  }

  .card-slot.state-incorrect {
    box-shadow: 0 0 0 2px var(--semantic-error, #ef4444);
  }

  .card-slot.state-dimmed {
    opacity: 0.4;
  }

  /* The choreo card paints a white print background + border (paper face);
     inside the game the rendered image is dark, so the white shows as a hard
     frame around every option. Neutralize it — the slot owns the border. */
  .card-slot :global(.choreo-card) {
    --print-bg: transparent;
    border: none;
  }

  @media (prefers-reduced-motion: reduce) {
    .card-slot {
      transition: none;
    }
  }
</style>
