<!--
  ComposerQrDemo

  The QR bento cell: a real, scannable share code generated by the app's own
  QRCodeGenerator (same play-button styling every export carries), pointing
  at a live tka.run short code. Scan it with a phone and the sequence opens.
-->
<script lang="ts">
  import { onMount } from "svelte";

  const CODE = "006C";
  const URL = `https://tka.run/${CODE}`;

  let qrDataUrl = $state<string | null>(null);
  let failed = $state(false);

  onMount(async () => {
    try {
      // The app shell configures the short-code manager in DI; this page has
      // no shell, so wire the browse loader in before grabbing the generator
      // (generateForUrl never resolves codes, but the constructor needs it).
      const [{ getQRCodeGenerator }, { configureShortCodeManager }, { getBrowseLoader }] =
        await Promise.all([
          import("$lib/shared/qr/get-qr-code-generator"),
          import("$lib/shared/qr/get-short-code-manager"),
          import("$lib/shared/browse/get-browse-loader"),
        ]);
      configureShortCodeManager(getBrowseLoader());
      const result = await getQRCodeGenerator().generateForUrl(URL, { size: 220 });
      qrDataUrl = result.dataUrl;
    } catch {
      failed = true;
    }
  });
</script>

<div class="qr-demo">
  <div class="qr-stage">
    {#if qrDataUrl}
      <img src={qrDataUrl} alt="QR code linking to a live sequence at {URL}" width="164" height="164" />
    {:else if failed}
      <span class="qr-note">QR is shy right now.</span>
    {/if}
  </div>
  <a class="code-chip" href={URL} target="_blank" rel="noopener noreferrer">
    tka.run/{CODE}
    <i class="fas fa-arrow-up-right-from-square" aria-hidden="true"></i>
  </a>
  <p class="hint">Scan it with your phone. A real sequence opens, no app needed.</p>
</div>

<style>
  .qr-demo {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 1rem 0.8rem 0.2rem;
  }

  .qr-stage {
    width: 164px;
    height: 164px;
    display: grid;
    place-items: center;
    border-radius: 14px;
    background: #fff;
    overflow: hidden;
  }
  .qr-stage img {
    display: block;
  }
  .qr-note {
    color: oklch(0.4 0.02 270);
    font-size: 0.8rem;
  }

  .code-chip {
    display: inline-flex;
    align-items: center;
    gap: 0.45rem;
    min-height: 40px;
    margin-top: 0.75rem;
    padding: 0 0.9rem;
    font-size: 0.9rem;
    font-weight: 600;
    font-variant-numeric: tabular-nums;
    color: oklch(0.9 0.015 270);
    text-decoration: none;
    background: oklch(0.3 0.04 270 / 0.18);
    border: 1px solid oklch(0.5 0.06 270 / 0.3);
    border-radius: 11px;
    transition: background 140ms ease;
  }
  .code-chip:hover {
    background: oklch(0.34 0.05 270 / 0.28);
  }
  .code-chip i {
    font-size: 0.7rem;
    opacity: 0.7;
  }

  .hint {
    margin: 0.6rem 0 0;
    font-size: 0.78rem;
    color: oklch(0.62 0.02 270);
    text-align: center;
  }

  @media (prefers-reduced-motion: reduce) {
    .code-chip {
      transition: none;
    }
  }
</style>
