import { childSeed, makeRng } from "$lib/shared/foundation/utils/seeded-rng";
import { FLOW_FEST_MASTER_SEED } from "$lib/features/flow-fest-sim/domain/flow-fest-simulation-contract";
import type { ImportedTerrainDataV2 } from "$lib/shared/3d/procedural-engine/generation/real-terrain-zone";
import type {
  FlowFestRuntimeContract,
  FlowFestRuntimePoint,
  FlowFestRuntimeSegment,
} from "../flow-fest-graybox/flow-fest-runtime-contract";
import { sampleFlowFestTerrainWorldY } from "../flow-fest-graybox/flow-fest-terrain-host";
import {
  deriveFlowFestCanopyPeaks,
  uniqueFlowFestSurfaceSegments,
  type FlowFestCanopyEvidence,
} from "./flow-fest-site-fidelity";
import {
  allFlowFestCampPlanLines,
  flowFestCampPlanLineToRuntimeSegment,
  type FlowFestCampPlan,
} from "./flow-fest-camp-plan";

export const FLOW_FEST_FOREST_TREE_ASSETS = {
  "island-tree-01":
    "/models/flow-fest-sim/ecology/island-tree-01-flow-lod-512.glb",
  "island-tree-02":
    "/models/flow-fest-sim/ecology/island-tree-02-flow-lod-512.glb",
  "island-tree-03":
    "/models/flow-fest-sim/ecology/island-tree-03-flow-lod-512.glb",
  "tree-small-02":
    "/models/flow-fest-sim/ecology/tree-small-02-flow-lod-512.glb",
  "plantcatalog-aesculus-carnea":
    "/models/forest/trees/candidates/plantcatalog-r1/aesculus-carnea-ld-s23.glb",
  "plantcatalog-oak-urban":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-urban-ld-s13.glb",
  "plantcatalog-oak-colonised":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-colonised-ld-s29.glb",
  "plantcatalog-willow":
    "/models/forest/trees/candidates/plantcatalog-r1/salix-alba-ld-s11.glb",
  "plantcatalog-buckeye-31":
    "/models/forest/trees/candidates/plantcatalog-r1/aesculus-pavia-ld-s31.glb",
  "plantcatalog-buckeye-79":
    "/models/forest/trees/candidates/plantcatalog-r1/aesculus-pavia-ld-s79.glb",
  "plantcatalog-habitat-snag":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-dead-ld-s37.glb",
  "plantcatalog-oak-forest-41":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-forest-ld-s41.glb",
  "plantcatalog-oak-forest-67":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-forest-ld-s67.glb",
  "plantcatalog-oak-forest-89":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-forest-ld-s89.glb",
  "plantcatalog-oak-forest-101":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-forest-ld-s101.glb",
  "plantcatalog-oak-forest-113":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-forest-ld-s113.glb",
  "plantcatalog-oak-lone-57":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-lone-ld-s57.glb",
  "plantcatalog-oak-urban-71":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-urban-ld-s71.glb",
  "plantcatalog-oak-colonised-61":
    "/models/forest/trees/candidates/plantcatalog-r1/quercus-robur-colonised-ld-s61.glb",
  "plantcatalog-carnea-47":
    "/models/forest/trees/candidates/plantcatalog-r1/aesculus-carnea-ld-s47.glb",
  "plantcatalog-buckeye-103":
    "/models/forest/trees/candidates/plantcatalog-r1/aesculus-pavia-ld-s103.glb",
  "plantcatalog-willow-53":
    "/models/forest/trees/candidates/plantcatalog-r1/salix-alba-ld-s53.glb",
} as const;

/**
 * Every family carries its own mid and far tier, generated by
 * `scripts/geospatial/build_flow_fest_tree_lods.mjs`. The tier GLBs keep the
 * near asset's material names and UVs but no textures; the runtime re-binds
 * the near materials by name, so a tree keeps its identity — same silhouette,
 * same bark, same leaf atlas — at every distance.
 */
function deriveDistanceTierAssets(tier: "mid" | "far") {
  return Object.fromEntries(
    Object.keys(FLOW_FEST_FOREST_TREE_ASSETS).map((familyId) => [
      familyId,
      `/models/flow-fest-sim/ecology/distance-lod/${familyId}-${tier}.glb`,
    ])
  ) as Record<FlowFestForestTreeFamilyId, string>;
}

export const FLOW_FEST_FOREST_DISTANCE_TREE_ASSETS: Record<
  "mid" | "far",
  Record<FlowFestForestTreeFamilyId, string>
> = {
  mid: deriveDistanceTierAssets("mid"),
  far: deriveDistanceTierAssets("far"),
};

export const FLOW_FEST_FOREST_DISTANCE_LOD = {
  nearMaximumMeters: 55,
  midMaximumMeters: 130,
  grassNearMaximumMeters: 22,
  grassMidMaximumMeters: 40,
  grassMaximumMeters: 58,
  grassMidDensity: 0.5,
  grassFarDensity: 0.25,
  cameraPositionThresholdMeters: 0.75,
  cameraRotationThresholdRadians: 0.015,
} as const;

export const FLOW_FEST_FOREST_GRASS_ASSET =
  "/models/flow-fest-sim/ecology/forest-grass-prototypes.glb";

export const FLOW_FEST_FOREST_DISTANCE_GRASS_ASSETS = {
  mid: "/models/flow-fest-sim/ecology/distance-lod/grass/forest-grass-prototypes-mid.glb",
  far: "/models/flow-fest-sim/ecology/distance-lod/grass/forest-grass-prototypes-far.glb",
} as const;

export const FLOW_FEST_FOREST_GROUND_LIFE_ASSETS = {
  "damp-sedge-tussock": "/models/forest/ground-life/damp-sedge-tussock.glb",
  "woodland-hazel-shrub": "/models/forest/ground-life/woodland-hazel-shrub.glb",
} as const;

export type FlowFestForestTreeFamilyId =
  keyof typeof FLOW_FEST_FOREST_TREE_ASSETS;
export type FlowFestForestDistanceTreeFamilyId = FlowFestForestTreeFamilyId;
export const FLOW_FEST_PLANTFACTORY_TREE_FAMILIES = Object.keys(
  FLOW_FEST_FOREST_TREE_ASSETS
).filter((familyId) =>
  familyId.startsWith("plantcatalog-")
) as readonly FlowFestForestTreeFamilyId[];

/**
 * Trunk radius per metre of rendered tree height, measured from each family's
 * GLB geometry by `scripts/geospatial/build_flow_fest_tree_lods.mjs`: the 35th
 * percentile of horizontal vertex distance from the trunk axis in the 2–7%
 * height band. The buckeyes are multi-stem clumps, so their measured band is a
 * stem cluster, not a single bole — that width is real and walking through it
 * should be blocked.
 */
export const FLOW_FEST_FOREST_TRUNK_PROFILES: Record<
  FlowFestForestTreeFamilyId,
  number
> = {
  "island-tree-01": 0.054,
  "island-tree-02": 0.06,
  "island-tree-03": 0.143,
  // No measurable low band (canopy starts at the ground plane); estimated from
  // the visual trunk at typical rendered size.
  "tree-small-02": 0.035,
  "plantcatalog-aesculus-carnea": 0.101,
  "plantcatalog-oak-urban": 0.014,
  "plantcatalog-oak-colonised": 0.022,
  "plantcatalog-willow": 0.017,
  "plantcatalog-buckeye-31": 0.203,
  "plantcatalog-buckeye-79": 0.204,
  "plantcatalog-habitat-snag": 0.122,
  "plantcatalog-oak-forest-41": 0.018,
  "plantcatalog-oak-forest-67": 0.018,
  "plantcatalog-oak-forest-89": 0.015,
  "plantcatalog-oak-forest-101": 0.02,
  "plantcatalog-oak-forest-113": 0.015,
  "plantcatalog-oak-lone-57": 0.02,
  "plantcatalog-oak-urban-71": 0.014,
  "plantcatalog-oak-colonised-61": 0.018,
  "plantcatalog-carnea-47": 0.032,
  "plantcatalog-buckeye-103": 0.276,
  "plantcatalog-willow-53": 0.022,
};

/**
 * Material-name tokens that mark a tree or ground-life material as living
 * foliage rather than wood. Both spellings of leaf are required: every
 * Flow Fest island-tree family ships its canopy as `<family>_leaves`, which
 * does not contain the substring `leaf`.
 */
export const FLOW_FEST_FOREST_FOLIAGE_MATERIAL_TOKENS = [
  "leaf",
  "leaves",
  "foliage",
  "twig",
  "frond",
  "needle",
  "canopy",
  "blossom",
  "petal",
  "sedge",
  "hazel",
] as const;

/**
 * A tree material is foliage when its name says so, or when it is an
 * alpha-cutout card. Every foliage material in the shipped Flow Fest tree
 * families is authored as glTF `alphaMode: "MASK"`, which three.js loads as a
 * positive `alphaTest`; wood, bark, and branch materials are opaque.
 */
export function isFlowFestForestFoliageMaterial(material: {
  name?: string | null;
  alphaTest?: number;
}): boolean {
  const name = (material.name ?? "").toLowerCase();
  if (
    FLOW_FEST_FOREST_FOLIAGE_MATERIAL_TOKENS.some((token) =>
      name.includes(token)
    )
  ) {
    return true;
  }
  return (material.alphaTest ?? 0) > 0;
}

/**
 * Deterministic per-tree colour multiplier, applied through
 * `InstancedMesh.setColorAt` so it composes with the moment tint exactly like
 * the grass palette does. Foliage swings along a warm–cool axis (yellow-green
 * toward blue-green) with a value spread; bark takes a subtler value-only
 * jitter. Without this every tree in a family renders the same flat colour and
 * the canopy line reads as one merged mass.
 */
export function deriveFlowFestTreeInstanceTint(
  placement: { x: number; z: number },
  part: "foliage" | "bark"
): { r: number; g: number; b: number } {
  const rng = makeRng(
    childSeed(
      FLOW_FEST_MASTER_SEED,
      `forest-tree-tint:${placement.x}:${placement.z}`
    )
  );
  const warm = (rng() - 0.5) * 2;
  const foliageValue = 0.78 + rng() * 0.34;
  const barkValue = 0.88 + rng() * 0.2;
  if (part === "bark") {
    return { r: barkValue, g: barkValue, b: barkValue };
  }
  return {
    r: foliageValue * (1 + 0.11 * warm),
    g: foliageValue * (1 + 0.03 * warm),
    b: foliageValue * (1 - 0.13 * warm),
  };
}

export type FlowFestForestEcologyAssetState = "pending" | "ready" | "failed";

export interface FlowFestForestEcologyAssetEntry {
  key: string;
  url: string;
  state: FlowFestForestEcologyAssetState;
  message?: string | null;
}

export interface FlowFestForestEcologyAssetReport {
  status: "loading" | "ready" | "failed";
  expected: number;
  ready: number;
  pending: string[];
  failed: Array<{ key: string; url: string; message: string }>;
}

/**
 * Collapses the per-asset ledger into one honest status. A failed asset stays
 * failed even while siblings are still loading, so an absent forest can never
 * present itself as a scene that is merely slow.
 */
export function summarizeFlowFestForestEcologyAssets(
  entries: readonly FlowFestForestEcologyAssetEntry[]
): FlowFestForestEcologyAssetReport {
  const failed = entries
    .filter((entry) => entry.state === "failed")
    .map((entry) => ({
      key: entry.key,
      url: entry.url,
      message: entry.message ?? "Asset failed to load",
    }));
  const pending = entries
    .filter((entry) => entry.state === "pending")
    .map((entry) => entry.key);
  const ready = entries.filter((entry) => entry.state === "ready").length;
  return {
    status:
      failed.length > 0 ? "failed" : pending.length > 0 ? "loading" : "ready",
    expected: entries.length,
    ready,
    pending,
    failed,
  };
}

export type FlowFestForestGrassTier = "base" | "medium" | "high";
export type FlowFestForestGrassSpecies = "summer-sward" | "woodland-grass";
export type FlowFestForestGroundLifeSpecies =
  | "damp-sedge-tussock"
  | "woodland-hazel-shrub";

export interface FlowFestForestTreePlacement {
  x: number;
  y: number;
  z: number;
  rotation: number;
  scale: number;
  colorIndex: number;
  renderedHeightMeters: number;
  measuredHeightMeters: number;
  trunkHeightMeters: number;
  trunkRadiusMeters: number;
  crownRadiusMeters: number;
  familyId: FlowFestForestTreeFamilyId;
}

export interface FlowFestForestGrassPlacement {
  x: number;
  y: number;
  z: number;
  rotation: number;
  widthMeters: number;
  heightMeters: number;
  species: FlowFestForestGrassSpecies;
  tier: FlowFestForestGrassTier;
  colorIndex: number;
}

export interface FlowFestForestGroundLifePlacement {
  x: number;
  y: number;
  z: number;
  rotation: number;
  scale: number;
  species: FlowFestForestGroundLifeSpecies;
}

export interface FlowFestForestEcologyLayout {
  trees: FlowFestForestTreePlacement[];
  grass: FlowFestForestGrassPlacement[];
  groundLife: FlowFestForestGroundLifePlacement[];
  audit: {
    treeRouteIntrusions: number;
    grassRouteIntrusions: number;
    groundLifeRouteIntrusions: number;
    sourceTreeFamilies: number;
    plantFactoryTreePlacements: number;
    measuredCanopyPlacements: number;
    infillTreePlacements: number;
    grassPlacements: number;
    groundLifePlacements: number;
  };
}

const GRASS_GRID_METERS = 4;
const GRASS_ROUTE_CLEARANCE_METERS = 0.45;
const GROUND_LIFE_ROUTE_CLEARANCE_METERS = 1.2;

/**
 * Adapt the Forest Scene ecology to the measured campground.
 *
 * Forest owns the visual families and wind-ready grass strata. Flow Fest owns
 * every world coordinate: tree centers come from local LiDAR maxima, while
 * ground life is deterministically sampled inside the measured footprint and
 * cut away from every registered route.
 */
export function deriveFlowFestForestEcology(
  contract: FlowFestRuntimeContract,
  terrain: ImportedTerrainDataV2,
  canopy: FlowFestCanopyEvidence,
  campPlan: FlowFestCampPlan | null = null
): FlowFestForestEcologyLayout {
  const routes = mergeEcologyRoutes(contract, campPlan);
  const canopyPeaks = deriveFlowFestCanopyPeaks(
    contract,
    terrain,
    canopy
  ).filter((peak) => !pointNearRoutes(peak.x, peak.z, routes, 3.2));
  const trees = canopyPeaks.map((peak, index): FlowFestForestTreePlacement => {
    const rng = makeRng(
      childSeed(FLOW_FEST_MASTER_SEED, `forest-tree:${peak.x}:${peak.z}`)
    );
    const renderedHeightMeters = clamp(
      peak.measuredHeightMeters * (0.62 + rng() * 0.08),
      7.5,
      19
    );
    const groundY = sampleFlowFestTerrainWorldY(terrain, peak.x, peak.z);
    const familyId = chooseTreeFamily(
      renderedHeightMeters,
      groundY,
      peak.neighborhoodHighReturnRatio,
      peak.x,
      peak.z,
      index,
      rng
    );
    return buildTreePlacement(
      peak.x,
      groundY,
      peak.z,
      peak.measuredHeightMeters,
      renderedHeightMeters,
      familyId,
      rng
    );
  });
  const measuredCanopyPlacements = trees.length;
  appendCanopyInfillTrees(contract, terrain, canopy, routes, trees);
  const infillTreePlacements = trees.length - measuredCanopyPlacements;

  const grass: FlowFestForestGrassPlacement[] = [];
  const groundLife: FlowFestForestGroundLifePlacement[] = [];
  const bounds = contract.surfaceEvidenceProxy.activeBoundsWorldMeters;
  for (
    let gridZ = Math.ceil(bounds.minZ);
    gridZ <= Math.floor(bounds.maxZ);
    gridZ += GRASS_GRID_METERS
  ) {
    for (
      let gridX = Math.ceil(bounds.minX);
      gridX <= Math.floor(bounds.maxX);
      gridX += GRASS_GRID_METERS
    ) {
      const rng = makeRng(
        childSeed(FLOW_FEST_MASTER_SEED, `forest-floor:${gridX}:${gridZ}`)
      );
      const x = gridX + (rng() - 0.5) * 1.65;
      const z = gridZ + (rng() - 0.5) * 1.65;
      if (
        x < bounds.minX ||
        x > bounds.maxX ||
        z < bounds.minZ ||
        z > bounds.maxZ ||
        pointNearRoutes(x, z, routes, GRASS_ROUTE_CLEARANCE_METERS)
      ) {
        continue;
      }

      const canopyOffsetMeters = sampleCanopyOffsetMeters(
        terrain,
        canopy,
        x,
        z
      );
      const shaded = canopyOffsetMeters >= 4;
      const keepProbability = shaded ? 0.84 : 0.66;
      if (rng() > keepProbability) continue;
      const tierRoll = rng();
      const tier: FlowFestForestGrassTier =
        tierRoll < 0.58 ? "base" : tierRoll < 0.9 ? "medium" : "high";
      const species: FlowFestForestGrassSpecies = shaded
        ? "woodland-grass"
        : "summer-sward";
      const baseHeight = species === "woodland-grass" ? 0.42 : 0.32;
      grass.push({
        x,
        y: sampleFlowFestTerrainWorldY(terrain, x, z) + 0.012,
        z,
        rotation: rng() * Math.PI * 2,
        widthMeters: 0.2 + rng() * 0.17,
        heightMeters: baseHeight * (0.72 + rng() * 0.58),
        species,
        tier,
        colorIndex: Math.floor(rng() * 4),
      });

      if (
        shaded &&
        rng() < 0.008 &&
        !pointNearRoutes(x, z, routes, GROUND_LIFE_ROUTE_CLEARANCE_METERS)
      ) {
        groundLife.push({
          x,
          y: sampleFlowFestTerrainWorldY(terrain, x, z),
          z,
          rotation: rng() * Math.PI * 2,
          scale: 0.72 + rng() * 0.58,
          species:
            canopyOffsetMeters > 9 && rng() < 0.32
              ? "woodland-hazel-shrub"
              : "damp-sedge-tussock",
        });
      }
    }
  }
  appendRegisteredZoneGrass(contract, terrain, routes, grass);

  return {
    trees,
    grass,
    groundLife,
    audit: {
      treeRouteIntrusions: trees.filter((placement) =>
        pointNearRoutes(placement.x, placement.z, routes, 3.2)
      ).length,
      grassRouteIntrusions: grass.filter((placement) =>
        pointNearRoutes(
          placement.x,
          placement.z,
          routes,
          GRASS_ROUTE_CLEARANCE_METERS - 0.001
        )
      ).length,
      groundLifeRouteIntrusions: groundLife.filter((placement) =>
        pointNearRoutes(
          placement.x,
          placement.z,
          routes,
          GROUND_LIFE_ROUTE_CLEARANCE_METERS - 0.001
        )
      ).length,
      sourceTreeFamilies: new Set(trees.map((tree) => tree.familyId)).size,
      plantFactoryTreePlacements: trees.filter((tree) =>
        FLOW_FEST_PLANTFACTORY_TREE_FAMILIES.includes(tree.familyId)
      ).length,
      measuredCanopyPlacements,
      infillTreePlacements,
      grassPlacements: grass.length,
      groundLifePlacements: groundLife.length,
    },
  };
}

function buildTreePlacement(
  x: number,
  groundY: number,
  z: number,
  measuredHeightMeters: number,
  renderedHeightMeters: number,
  familyId: FlowFestForestTreeFamilyId,
  rng: () => number
): FlowFestForestTreePlacement {
  return {
    x,
    y: groundY,
    z,
    rotation: rng() * Math.PI * 2,
    scale: 1,
    colorIndex: 0,
    measuredHeightMeters,
    renderedHeightMeters,
    trunkHeightMeters: renderedHeightMeters * (0.68 + rng() * 0.05),
    // The collision trunk tracks the family's measured geometry, so a wide
    // island-tree-03 bole blocks the avatar at its rendered width instead of
    // at a one-size cylinder it visibly overhangs.
    trunkRadiusMeters: clamp(
      renderedHeightMeters * FLOW_FEST_FOREST_TRUNK_PROFILES[familyId],
      0.2,
      1.9
    ),
    crownRadiusMeters: clamp(
      renderedHeightMeters * (0.27 + rng() * 0.035),
      2.15,
      5.1
    ),
    familyId,
  };
}

const INFILL_GRID_METERS = 8;
const INFILL_MINIMUM_CANOPY_OFFSET_METERS = 5;
const INFILL_MINIMUM_TREE_SPACING_METERS = 4.5;
/** Fraction of qualifying grid cells that actually receive an infill tree. */
const INFILL_ACCEPTANCE = 0.62;

/**
 * The LiDAR peak detector only yields one tree per local canopy maximum, which
 * under-counts closed woodland: broad connected canopy reads as a single peak
 * and the stand renders sparse. This pass walks a jittered grid and plants a
 * tree wherever the canopy raster proves real overhead growth
 * ({@link INFILL_MINIMUM_CANOPY_OFFSET_METERS}) with no measured tree nearby —
 * so density returns only where the survey says trees actually are, never on
 * routes, zones, or open meadow.
 */
function appendCanopyInfillTrees(
  contract: FlowFestRuntimeContract,
  terrain: ImportedTerrainDataV2,
  canopy: FlowFestCanopyEvidence,
  routes: FlowFestRuntimeSegment[],
  trees: FlowFestForestTreePlacement[]
): void {
  const bounds = contract.surfaceEvidenceProxy.activeBoundsWorldMeters;
  const spacingSquared =
    INFILL_MINIMUM_TREE_SPACING_METERS * INFILL_MINIMUM_TREE_SPACING_METERS;
  for (
    let gridZ = Math.ceil(bounds.minZ);
    gridZ <= Math.floor(bounds.maxZ);
    gridZ += INFILL_GRID_METERS
  ) {
    for (
      let gridX = Math.ceil(bounds.minX);
      gridX <= Math.floor(bounds.maxX);
      gridX += INFILL_GRID_METERS
    ) {
      const rng = makeRng(
        childSeed(FLOW_FEST_MASTER_SEED, `forest-infill:${gridX}:${gridZ}`)
      );
      const x = gridX + (rng() - 0.5) * 6.4;
      const z = gridZ + (rng() - 0.5) * 6.4;
      if (x < bounds.minX || x > bounds.maxX) continue;
      if (z < bounds.minZ || z > bounds.maxZ) continue;
      const canopyOffsetMeters = sampleCanopyOffsetMeters(terrain, canopy, x, z);
      if (canopyOffsetMeters < INFILL_MINIMUM_CANOPY_OFFSET_METERS) continue;
      if (pointNearRoutes(x, z, routes, 3.2)) continue;
      if (pointInsideRegisteredZone(contract, x, z)) continue;
      if (
        trees.some((tree) => {
          const deltaX = tree.x - x;
          const deltaZ = tree.z - z;
          return deltaX * deltaX + deltaZ * deltaZ < spacingSquared;
        })
      ) {
        continue;
      }
      if (rng() > INFILL_ACCEPTANCE) continue;

      const renderedHeightMeters = clamp(
        canopyOffsetMeters * (0.62 + rng() * 0.08),
        7.5,
        19
      );
      const groundY = sampleFlowFestTerrainWorldY(terrain, x, z);
      // The gate already proved connected canopy overhead, so the infill point
      // sits inside a stand; the stand-density ratio reflects that.
      const familyId = chooseTreeFamily(
        renderedHeightMeters,
        groundY,
        0.78,
        x,
        z,
        trees.length,
        rng
      );
      trees.push(
        buildTreePlacement(
          x,
          groundY,
          z,
          canopyOffsetMeters,
          renderedHeightMeters,
          familyId,
          rng
        )
      );
    }
  }
}

function pointInsideRegisteredZone(
  contract: FlowFestRuntimeContract,
  x: number,
  z: number
): boolean {
  return contract.zones.some((zone) => {
    const radiusX = zone.radiusMeters ?? zone.searchRadiusXMeters ?? 0;
    const radiusZ = zone.radiusMeters ?? zone.searchRadiusZMeters ?? 0;
    if (radiusX <= 0 || radiusZ <= 0) return false;
    const normalizedX = (x - zone.center.x) / radiusX;
    const normalizedZ = (z - zone.center.z) / radiusZ;
    return normalizedX * normalizedX + normalizedZ * normalizedZ <= 1;
  });
}

function mergeEcologyRoutes(
  contract: FlowFestRuntimeContract,
  campPlan: FlowFestCampPlan | null
): FlowFestRuntimeSegment[] {
  const routes = uniqueFlowFestSurfaceSegments(contract);
  if (!campPlan) return routes;
  const planLines = allFlowFestCampPlanLines(campPlan);
  const byId = new Map(routes.map((route) => [route.id, route]));
  for (const line of planLines)
    byId.set(line.id, flowFestCampPlanLineToRuntimeSegment(line));
  return [...byId.values()];
}

function appendRegisteredZoneGrass(
  contract: FlowFestRuntimeContract,
  terrain: ImportedTerrainDataV2,
  routes: FlowFestRuntimeSegment[],
  grass: FlowFestForestGrassPlacement[]
): void {
  const spacingMeters = 1.05;
  for (const zone of contract.zones) {
    const radiusX = zone.radiusMeters ?? zone.searchRadiusXMeters ?? 0;
    const radiusZ = zone.radiusMeters ?? zone.searchRadiusZMeters ?? 0;
    if (radiusX <= 0 || radiusZ <= 0) continue;
    for (let localZ = -radiusZ; localZ <= radiusZ; localZ += spacingMeters) {
      for (let localX = -radiusX; localX <= radiusX; localX += spacingMeters) {
        for (let tuft = 0; tuft < 3; tuft += 1) {
          const rng = makeRng(
            childSeed(
              FLOW_FEST_MASTER_SEED,
              `zone-grass:${zone.id}:${localX.toFixed(2)}:${localZ.toFixed(2)}:${tuft}`
            )
          );
          const x = zone.center.x + localX + (rng() - 0.5) * 0.86;
          const z = zone.center.z + localZ + (rng() - 0.5) * 0.86;
          const normalizedX = (x - zone.center.x) / radiusX;
          const normalizedZ = (z - zone.center.z) / radiusZ;
          if (
            normalizedX * normalizedX + normalizedZ * normalizedZ > 1 ||
            pointNearRoutes(x, z, routes, GRASS_ROUTE_CLEARANCE_METERS) ||
            rng() > 0.9
          ) {
            continue;
          }
          const tierRoll = rng();
          grass.push({
            x,
            y: sampleFlowFestTerrainWorldY(terrain, x, z) + 0.012,
            z,
            rotation: rng() * Math.PI * 2,
            widthMeters: 0.12 + rng() * 0.1,
            heightMeters: 0.2 + rng() * 0.14,
            species: "summer-sward",
            tier:
              tierRoll < 0.62 ? "base" : tierRoll < 0.92 ? "medium" : "high",
            colorIndex: Math.floor(rng() * 4),
          });
        }
      }
    }
  }
}

/**
 * Habitat casting for the measured woodland. Ground height, rendered height,
 * and the LiDAR neighborhood's high-return ratio sort each placement into one
 * of four habitat sets; every set mixes PlantFactory species with the original
 * island families so no silhouette repeats wall-to-wall. Selection within a
 * set rotates by placement index plus a stable per-48m-cell phase, so a stand
 * reads as a community rather than a tiling pattern.
 */
const FLOW_FEST_DAMP_FAMILIES = [
  "plantcatalog-willow",
  "plantcatalog-oak-colonised",
  "plantcatalog-willow",
  "island-tree-02",
  "plantcatalog-willow-53",
] as const satisfies readonly FlowFestForestTreeFamilyId[];
const FLOW_FEST_UNDERSTORY_FAMILIES = [
  "plantcatalog-buckeye-31",
  "tree-small-02",
  "plantcatalog-buckeye-79",
  "plantcatalog-aesculus-carnea",
  "plantcatalog-buckeye-103",
  "plantcatalog-carnea-47",
] as const satisfies readonly FlowFestForestTreeFamilyId[];
const FLOW_FEST_STAND_FAMILIES = [
  "plantcatalog-oak-forest-41",
  "plantcatalog-oak-forest-67",
  "island-tree-01",
  "plantcatalog-oak-forest-89",
  "plantcatalog-oak-colonised",
  "island-tree-02",
  "plantcatalog-oak-forest-101",
  "plantcatalog-oak-forest-113",
  "plantcatalog-oak-colonised-61",
  // Open-grown crowns also read as stand edge. The measured site is nearly all
  // closed canopy, so a family seated only in the open set would draw a couple
  // of placements at most and effectively never render.
  "plantcatalog-oak-urban-71",
] as const satisfies readonly FlowFestForestTreeFamilyId[];
const FLOW_FEST_OPEN_FAMILIES = [
  "plantcatalog-oak-urban",
  "plantcatalog-aesculus-carnea",
  "island-tree-03",
  "plantcatalog-oak-forest-67",
  "island-tree-01",
  "plantcatalog-oak-lone-57",
  "plantcatalog-oak-urban-71",
  "plantcatalog-oak-colonised-61",
] as const satisfies readonly FlowFestForestTreeFamilyId[];

function chooseTreeFamily(
  renderedHeightMeters: number,
  groundY: number,
  neighborhoodHighReturnRatio: number,
  x: number,
  z: number,
  index: number,
  rng: () => number
): FlowFestForestTreeFamilyId {
  // Standing dead wood is habitat punctuation — rare, scattered, never a stand.
  if (rng() < 0.012) return "plantcatalog-habitat-snag";

  const families =
    groundY < 8.5
      ? FLOW_FEST_DAMP_FAMILIES
      : renderedHeightMeters < 10.2
        ? FLOW_FEST_UNDERSTORY_FAMILIES
        : neighborhoodHighReturnRatio > 0.72
          ? FLOW_FEST_STAND_FAMILIES
          : FLOW_FEST_OPEN_FAMILIES;
  const habitatRng = makeRng(
    childSeed(
      FLOW_FEST_MASTER_SEED,
      `forest-habitat:${Math.floor(x / 48)}:${Math.floor(z / 48)}`
    )
  );
  const habitatPhase = Math.floor(habitatRng() * families.length);
  const variation = rng() < 0.28 ? 1 : 0;
  return families[(index + habitatPhase + variation) % families.length]!;
}

function sampleCanopyOffsetMeters(
  terrain: ImportedTerrainDataV2,
  canopy: FlowFestCanopyEvidence,
  x: number,
  z: number
): number {
  const column = Math.round(
    ((x - terrain.worldBounds.minX) /
      (terrain.worldBounds.maxX - terrain.worldBounds.minX)) *
      (canopy.width - 1)
  );
  const row = Math.round(
    ((z - terrain.worldBounds.minZ) /
      (terrain.worldBounds.maxZ - terrain.worldBounds.minZ)) *
      (canopy.height - 1)
  );
  if (column < 0 || row < 0 || column >= canopy.width || row >= canopy.height) {
    return 0;
  }
  const value = canopy.offsetsCentimeters[row * canopy.width + column];
  return value == null || value === 65535 ? 0 : value / 100;
}

function pointNearRoutes(
  x: number,
  z: number,
  routes: FlowFestRuntimeSegment[],
  extraClearanceMeters: number
): boolean {
  return routes.some((route) => {
    const clearance = route.widthMeters / 2 + extraClearanceMeters;
    for (let index = 1; index < route.points.length; index += 1) {
      if (
        distanceToSegment(
          x,
          z,
          route.points[index - 1]!,
          route.points[index]!
        ) <= clearance
      ) {
        return true;
      }
    }
    return false;
  });
}

function distanceToSegment(
  x: number,
  z: number,
  start: FlowFestRuntimePoint,
  end: FlowFestRuntimePoint
): number {
  const deltaX = end.x - start.x;
  const deltaZ = end.z - start.z;
  const lengthSquared = deltaX * deltaX + deltaZ * deltaZ;
  if (lengthSquared === 0) return Math.hypot(x - start.x, z - start.z);
  const progress = Math.max(
    0,
    Math.min(
      1,
      ((x - start.x) * deltaX + (z - start.z) * deltaZ) / lengthSquared
    )
  );
  return Math.hypot(
    x - (start.x + deltaX * progress),
    z - (start.z + deltaZ * progress)
  );
}

function clamp(value: number, minimum: number, maximum: number): number {
  return Math.max(minimum, Math.min(maximum, value));
}
