import { childSeed, makeRng } from "$lib/shared/foundation/utils/seeded-rng";
import { FLOW_FEST_MASTER_SEED } from "$lib/features/flow-fest-sim/domain/flow-fest-simulation-contract";
import type { ImportedTerrainDataV2 } from "$lib/shared/3d/procedural-engine/generation/real-terrain-zone";
import type {
  FlowFestRuntimeContract,
  FlowFestRuntimePoint,
  FlowFestRuntimeSegment,
} from "../flow-fest-graybox/flow-fest-runtime-contract";
import { sampleFlowFestTerrainWorldY } from "../flow-fest-graybox/flow-fest-terrain-host";
import {
  deriveFlowFestCanopyPeaks,
  uniqueFlowFestSurfaceSegments,
  type FlowFestCanopyEvidence,
} from "./flow-fest-site-fidelity";
import {
  allFlowFestCampPlanLines,
  flowFestCampPlanLineToRuntimeSegment,
  type FlowFestCampPlan,
} from "./flow-fest-camp-plan";
import {
  FLOW_FEST_TREE_FAMILY_PLANS,
  flowFestTreeFamiliesForRole,
  flowFestTreeFamiliesForSpecies,
  flowFestTreeFamilyPlan,
  resolveFlowFestTreeFamilyId,
  type FlowFestTreeSpeciesPlan,
} from "./flow-fest-tree-species";

/**
 * Every tree in the sim is generated by `@dgreenheck/ez-tree` and baked to a
 * GLB at build time by `scripts/geospatial/build_flow_fest_eztree_species.ts`.
 * The roster IS the species catalog, so adding a species or a variant is one
 * edit in `flow-fest-tree-species.ts` plus a re-bake, never a hand-kept URL
 * table. This replaced 24 fixed GLBs (four island trees plus twenty
 * conditioned PlantFactory exports) that were reused site-wide and read as
 * repetition at ground level.
 */
export const FLOW_FEST_FOREST_TREE_ASSETS: Record<string, string> =
  Object.fromEntries(
    FLOW_FEST_TREE_FAMILY_PLANS.map((plan) => [
      plan.familyId,
      `/models/flow-fest-sim/ecology/species/${plan.familyId}.glb`,
    ])
  );

/**
 * Every family carries its own mid and far tier, generated by
 * `scripts/geospatial/build_flow_fest_tree_lods.mjs`. The tier GLBs keep the
 * near asset's material names and UVs but no textures; the runtime re-binds
 * the near materials by name, so a tree keeps its identity — same silhouette,
 * same bark, same leaf atlas — at every distance.
 */
function deriveDistanceTierAssets(tier: "mid" | "far") {
  return Object.fromEntries(
    Object.keys(FLOW_FEST_FOREST_TREE_ASSETS).map((familyId) => [
      familyId,
      `/models/flow-fest-sim/ecology/distance-lod/${familyId}-${tier}.glb`,
    ])
  ) as Record<FlowFestForestTreeFamilyId, string>;
}

export const FLOW_FEST_FOREST_DISTANCE_TREE_ASSETS: Record<
  "mid" | "far",
  Record<FlowFestForestTreeFamilyId, string>
> = {
  mid: deriveDistanceTierAssets("mid"),
  far: deriveDistanceTierAssets("far"),
};

/**
 * Tier seams are measured from the ride camera. At 55 m the near band held
 * only the handful of trees beside the road, so nearly every tree in a
 * ground-level frame was a mid-tier crown; 60 m keeps the first rank of the
 * woodland edge on the full asset, and 150 m holds the mid tier through the
 * ridge line before the far tier's card-thinned crowns take over. Pushing the
 * mid seam to 180 m moved several hundred ridge trees onto the mid asset and
 * cost more frame time than it returned in crown detail at that range.
 */
export const FLOW_FEST_FOREST_DISTANCE_LOD = {
  nearMaximumMeters: 60,
  midMaximumMeters: 150,
  grassNearMaximumMeters: 22,
  grassMidMaximumMeters: 40,
  grassMaximumMeters: 58,
  grassMidDensity: 0.5,
  grassFarDensity: 0.25,
  cameraPositionThresholdMeters: 0.75,
  cameraRotationThresholdRadians: 0.015,
} as const;

export const FLOW_FEST_FOREST_GRASS_ASSET =
  "/models/flow-fest-sim/ecology/forest-grass-prototypes.glb";

export const FLOW_FEST_FOREST_DISTANCE_GRASS_ASSETS = {
  mid: "/models/flow-fest-sim/ecology/distance-lod/grass/forest-grass-prototypes-mid.glb",
  far: "/models/flow-fest-sim/ecology/distance-lod/grass/forest-grass-prototypes-far.glb",
} as const;

export const FLOW_FEST_FOREST_GROUND_LIFE_ASSETS = {
  "damp-sedge-tussock": "/models/forest/ground-life/damp-sedge-tussock.glb",
  "woodland-hazel-shrub": "/models/forest/ground-life/woodland-hazel-shrub.glb",
} as const;

/**
 * A generated family id such as `eztree-white-oak-stand-b`. This is a plain
 * string, not a union over an asset table: the roster comes from the species
 * catalog and grows whenever a variant is added there, and the placement layer
 * may be handed a family id by the site layout plan. Membership is checked at
 * runtime against `FLOW_FEST_FOREST_TREE_ASSETS`.
 */
export type FlowFestForestTreeFamilyId = string;
export type FlowFestForestDistanceTreeFamilyId = FlowFestForestTreeFamilyId;

/**
 * Bole radius per metre of rendered tree height, measured by
 * `scripts/geospatial/build_flow_fest_eztree_species.ts` as the median radial
 * distance of trunk wood in a low band around the trunk axis, and printed by
 * that script ready to paste here. It is measured at generation time rather
 * than off the finished GLB because ez-tree sweeps the trunk as a small number
 * of long tapered rings: a narrow height band can fall entirely between two
 * rings and yield no samples at all.
 *
 * The collision cylinder reads this. A missing entry is a bake that never ran,
 * so the lookup throws rather than silently placing a tree you can walk
 * through.
 */
export const FLOW_FEST_FOREST_TRUNK_PROFILES: Record<string, number> = {
  "eztree-sugar-maple-stand-a": 0.0414,
  "eztree-sugar-maple-stand-b": 0.0467,
  "eztree-sugar-maple-stand-c": 0.0345,
  "eztree-sugar-maple-stand-d": 0.0369,
  "eztree-american-beech-stand-a": 0.0365,
  "eztree-american-beech-stand-b": 0.0338,
  "eztree-american-beech-stand-c": 0.0292,
  "eztree-white-oak-stand-a": 0.0456,
  "eztree-white-oak-stand-b": 0.0379,
  "eztree-white-oak-stand-c": 0.041,
  "eztree-white-oak-open-a": 0.0601,
  "eztree-white-oak-open-b": 0.0656,
  "eztree-black-walnut-stand-a": 0.0409,
  "eztree-black-walnut-stand-b": 0.0336,
  "eztree-black-walnut-stand-c": 0.0323,
  "eztree-black-walnut-open-a": 0.0419,
  "eztree-black-walnut-open-b": 0.0411,
  "eztree-shagbark-hickory-stand-a": 0.0296,
  "eztree-shagbark-hickory-stand-b": 0.0292,
  "eztree-shagbark-hickory-stand-c": 0.0272,
  "eztree-eastern-redcedar-open-a": 0.0854,
  "eztree-eastern-redcedar-open-b": 0.0834,
  "eztree-eastern-redcedar-open-c": 0.0954,
  "eztree-boxelder-understory-a": 0.0691,
  "eztree-boxelder-understory-b": 0.0304,
  "eztree-boxelder-understory-c": 0.0528,
  "eztree-boxelder-understory-d": 0.0514,
  "eztree-hophornbeam-understory-a": 0.0548,
  "eztree-hophornbeam-understory-b": 0.0371,
  "eztree-hophornbeam-understory-c": 0.0551,
  "eztree-hophornbeam-understory-d": 0.0399,
  "eztree-american-sycamore-damp-a": 0.0494,
  "eztree-american-sycamore-damp-b": 0.0348,
  "eztree-american-sycamore-damp-c": 0.0358,
  "eztree-silver-maple-damp-a": 0.0551,
  "eztree-silver-maple-damp-b": 0.0342,
  "eztree-silver-maple-damp-c": 0.0341,
  "eztree-standing-snag-a": 0.0448,
  "eztree-standing-snag-b": 0.0375,
};

function trunkRadiusRatio(familyId: string): number {
  const ratio = FLOW_FEST_FOREST_TRUNK_PROFILES[familyId];
  if (ratio === undefined) {
    throw new Error(
      `No measured trunk profile for tree family "${familyId}". Re-run scripts/geospatial/build_flow_fest_eztree_species.ts and paste its FLOW_FEST_FOREST_TRUNK_PROFILES block.`
    );
  }
  return ratio;
}

/**
 * Material-name tokens that mark a tree or ground-life material as living
 * foliage rather than wood. Both spellings of leaf are required: every
 * Flow Fest island-tree family ships its canopy as `<family>_leaves`, which
 * does not contain the substring `leaf`.
 */
export const FLOW_FEST_FOREST_FOLIAGE_MATERIAL_TOKENS = [
  "leaf",
  "leaves",
  "foliage",
  "twig",
  "frond",
  "needle",
  "canopy",
  "blossom",
  "petal",
  "sedge",
  "hazel",
] as const;

/**
 * A tree material is foliage when its name says so, or when it is an
 * alpha-cutout card. Every foliage material in the shipped Flow Fest tree
 * families is authored as glTF `alphaMode: "MASK"`, which three.js loads as a
 * positive `alphaTest`; wood, bark, and branch materials are opaque.
 */
export function isFlowFestForestFoliageMaterial(material: {
  name?: string | null;
  alphaTest?: number;
}): boolean {
  const name = (material.name ?? "").toLowerCase();
  if (
    FLOW_FEST_FOREST_FOLIAGE_MATERIAL_TOKENS.some((token) =>
      name.includes(token)
    )
  ) {
    return true;
  }
  return (material.alphaTest ?? 0) > 0;
}

/**
 * Deterministic per-tree colour multiplier, applied through
 * `InstancedMesh.setColorAt` so it composes with the moment tint exactly like
 * the grass palette does. Foliage swings along a warm–cool axis (yellow-green
 * toward blue-green) with a value spread; bark takes a subtler value-only
 * jitter. Without this every tree in a family renders the same flat colour and
 * the canopy line reads as one merged mass.
 */
export function deriveFlowFestTreeInstanceTint(
  placement: { x: number; z: number },
  part: "foliage" | "bark"
): { r: number; g: number; b: number } {
  const rng = makeRng(
    childSeed(
      FLOW_FEST_MASTER_SEED,
      `forest-tree-tint:${placement.x}:${placement.z}`
    )
  );
  const warm = (rng() - 0.5) * 2;
  const foliageValue = 0.78 + rng() * 0.34;
  const barkValue = 0.88 + rng() * 0.2;
  if (part === "bark") {
    return { r: barkValue, g: barkValue, b: barkValue };
  }
  return {
    r: foliageValue * (1 + 0.11 * warm),
    g: foliageValue * (1 + 0.03 * warm),
    b: foliageValue * (1 - 0.13 * warm),
  };
}

export type FlowFestForestEcologyAssetState = "pending" | "ready" | "failed";

export interface FlowFestForestEcologyAssetEntry {
  key: string;
  url: string;
  state: FlowFestForestEcologyAssetState;
  message?: string | null;
}

export interface FlowFestForestEcologyAssetReport {
  status: "loading" | "ready" | "failed";
  expected: number;
  ready: number;
  pending: string[];
  failed: Array<{ key: string; url: string; message: string }>;
}

/**
 * Collapses the per-asset ledger into one honest status. A failed asset stays
 * failed even while siblings are still loading, so an absent forest can never
 * present itself as a scene that is merely slow.
 */
export function summarizeFlowFestForestEcologyAssets(
  entries: readonly FlowFestForestEcologyAssetEntry[]
): FlowFestForestEcologyAssetReport {
  const failed = entries
    .filter((entry) => entry.state === "failed")
    .map((entry) => ({
      key: entry.key,
      url: entry.url,
      message: entry.message ?? "Asset failed to load",
    }));
  const pending = entries
    .filter((entry) => entry.state === "pending")
    .map((entry) => entry.key);
  const ready = entries.filter((entry) => entry.state === "ready").length;
  return {
    status:
      failed.length > 0 ? "failed" : pending.length > 0 ? "loading" : "ready",
    expected: entries.length,
    ready,
    pending,
    failed,
  };
}

export type FlowFestForestGrassTier = "base" | "medium" | "high";
export type FlowFestForestGrassSpecies = "summer-sward" | "woodland-grass";
export type FlowFestForestGroundLifeSpecies =
  | "damp-sedge-tussock"
  | "woodland-hazel-shrub";

export interface FlowFestForestTreePlacement {
  x: number;
  y: number;
  z: number;
  rotation: number;
  scale: number;
  colorIndex: number;
  renderedHeightMeters: number;
  measuredHeightMeters: number;
  trunkHeightMeters: number;
  trunkRadiusMeters: number;
  crownRadiusMeters: number;
  familyId: FlowFestForestTreeFamilyId;
}

export interface FlowFestForestGrassPlacement {
  x: number;
  y: number;
  z: number;
  rotation: number;
  widthMeters: number;
  heightMeters: number;
  species: FlowFestForestGrassSpecies;
  tier: FlowFestForestGrassTier;
  colorIndex: number;
}

export interface FlowFestForestGroundLifePlacement {
  x: number;
  y: number;
  z: number;
  rotation: number;
  scale: number;
  species: FlowFestForestGroundLifeSpecies;
}

export interface FlowFestForestEcologyLayout {
  trees: FlowFestForestTreePlacement[];
  /**
   * The measured woodland OUTSIDE the site, kept in its own list.
   *
   * These render through the same distance tiers as the site trees, so walking
   * toward the property line does not reveal a wall of far-tier cards. They are
   * separate because everything that treats a tree as part of the venue reads
   * `trees`: collision bodies, leaf litter on the ground surface, and the
   * entrance-fixture clearance. Scenery a kilometre out earns none of that.
   */
  backdropTrees: FlowFestForestTreePlacement[];
  grass: FlowFestForestGrassPlacement[];
  groundLife: FlowFestForestGroundLifePlacement[];
  audit: {
    treeRouteIntrusions: number;
    grassRouteIntrusions: number;
    groundLifeRouteIntrusions: number;
    sourceTreeFamilies: number;
    sourceTreeSpecies: number;
    measuredCanopyPlacements: number;
    infillTreePlacements: number;
    backdropTreePlacements: number;
    grassPlacements: number;
    groundLifePlacements: number;
  };
}

/**
 * Options for one derivation. Everything here is a site-layout input; the
 * ecology's own habitat casting is the default when none is supplied.
 */
export interface FlowFestForestEcologyOptions {
  /**
   * THE PER-INSTANCE SPECIES SEAM.
   *
   * The tree LAYOUT — which species stands where, derived over the registered
   * orthophoto — is owned outside this module. Implement
   * `FlowFestTreeSpeciesPlan.resolve` and pass the plan here; it is asked
   * about every tree, measured peak and canopy infill alike, and may answer
   * with a species id, a form id, or an exact family id plus an optional
   * trunk height. Returning `null` for a tree means "no opinion", and that
   * tree falls back to habitat casting.
   */
  readonly speciesPlan?: FlowFestTreeSpeciesPlan | null;
}

const GRASS_GRID_METERS = 4;
const GRASS_ROUTE_CLEARANCE_METERS = 0.45;
const GROUND_LIFE_ROUTE_CLEARANCE_METERS = 1.2;

/**
 * Adapt the Forest Scene ecology to the measured campground.
 *
 * Forest owns the visual families and wind-ready grass strata. Flow Fest owns
 * every world coordinate: tree centers come from local LiDAR maxima, while
 * ground life is deterministically sampled inside the measured footprint and
 * cut away from every registered route.
 */
export function deriveFlowFestForestEcology(
  contract: FlowFestRuntimeContract,
  terrain: ImportedTerrainDataV2,
  canopy: FlowFestCanopyEvidence,
  campPlan: FlowFestCampPlan | null = null,
  options: FlowFestForestEcologyOptions = {}
): FlowFestForestEcologyLayout {
  const speciesPlan = options.speciesPlan ?? null;
  const routes = mergeEcologyRoutes(contract, campPlan);
  const canopyPeaks = deriveFlowFestCanopyPeaks(
    contract,
    terrain,
    canopy
  ).filter((peak) => !pointNearRoutes(peak.x, peak.z, routes, 3.2));
  const trees = canopyPeaks.map((peak, index): FlowFestForestTreePlacement => {
    const rng = makeRng(
      childSeed(FLOW_FEST_MASTER_SEED, `forest-tree:${peak.x}:${peak.z}`)
    );
    const renderedHeightMeters = clamp(
      peak.measuredHeightMeters * (0.62 + rng() * 0.08),
      7.5,
      19
    );
    const groundY = sampleFlowFestTerrainWorldY(terrain, peak.x, peak.z);
    const cast = castTreeFamily({
      speciesPlan,
      index,
      x: peak.x,
      z: peak.z,
      groundY,
      renderedHeightMeters,
      neighborhoodHighReturnRatio: peak.neighborhoodHighReturnRatio,
      rng,
    });
    return buildTreePlacement(
      peak.x,
      groundY,
      peak.z,
      peak.measuredHeightMeters,
      renderedHeightMeters,
      cast,
      rng
    );
  });
  const measuredCanopyPlacements = trees.length;
  appendCanopyInfillTrees(contract, terrain, canopy, routes, trees, speciesPlan);
  const infillTreePlacements = trees.length - measuredCanopyPlacements;
  const backdropTrees = deriveBackdropTrees(
    contract,
    terrain,
    canopy,
    speciesPlan
  );

  const grass: FlowFestForestGrassPlacement[] = [];
  const groundLife: FlowFestForestGroundLifePlacement[] = [];
  const bounds = contract.surfaceEvidenceProxy.activeBoundsWorldMeters;
  for (
    let gridZ = Math.ceil(bounds.minZ);
    gridZ <= Math.floor(bounds.maxZ);
    gridZ += GRASS_GRID_METERS
  ) {
    for (
      let gridX = Math.ceil(bounds.minX);
      gridX <= Math.floor(bounds.maxX);
      gridX += GRASS_GRID_METERS
    ) {
      const rng = makeRng(
        childSeed(FLOW_FEST_MASTER_SEED, `forest-floor:${gridX}:${gridZ}`)
      );
      const x = gridX + (rng() - 0.5) * 1.65;
      const z = gridZ + (rng() - 0.5) * 1.65;
      if (
        x < bounds.minX ||
        x > bounds.maxX ||
        z < bounds.minZ ||
        z > bounds.maxZ ||
        pointNearRoutes(x, z, routes, GRASS_ROUTE_CLEARANCE_METERS)
      ) {
        continue;
      }

      const canopyOffsetMeters = sampleCanopyOffsetMeters(
        terrain,
        canopy,
        x,
        z
      );
      const shaded = canopyOffsetMeters >= 4;
      const keepProbability = shaded ? 0.84 : 0.66;
      if (rng() > keepProbability) continue;
      const tierRoll = rng();
      const tier: FlowFestForestGrassTier =
        tierRoll < 0.58 ? "base" : tierRoll < 0.9 ? "medium" : "high";
      const species: FlowFestForestGrassSpecies = shaded
        ? "woodland-grass"
        : "summer-sward";
      const baseHeight = species === "woodland-grass" ? 0.42 : 0.32;
      grass.push({
        x,
        y: sampleFlowFestTerrainWorldY(terrain, x, z) + 0.012,
        z,
        rotation: rng() * Math.PI * 2,
        widthMeters: 0.2 + rng() * 0.17,
        heightMeters: baseHeight * (0.72 + rng() * 0.58),
        species,
        tier,
        colorIndex: Math.floor(rng() * 4),
      });

      if (
        shaded &&
        rng() < 0.008 &&
        !pointNearRoutes(x, z, routes, GROUND_LIFE_ROUTE_CLEARANCE_METERS)
      ) {
        groundLife.push({
          x,
          y: sampleFlowFestTerrainWorldY(terrain, x, z),
          z,
          rotation: rng() * Math.PI * 2,
          scale: 0.72 + rng() * 0.58,
          species:
            canopyOffsetMeters > 9 && rng() < 0.32
              ? "woodland-hazel-shrub"
              : "damp-sedge-tussock",
        });
      }
    }
  }
  appendRegisteredZoneGrass(contract, terrain, routes, grass);

  return {
    trees,
    backdropTrees,
    grass,
    groundLife,
    audit: {
      treeRouteIntrusions: trees.filter((placement) =>
        pointNearRoutes(placement.x, placement.z, routes, 3.2)
      ).length,
      grassRouteIntrusions: grass.filter((placement) =>
        pointNearRoutes(
          placement.x,
          placement.z,
          routes,
          GRASS_ROUTE_CLEARANCE_METERS - 0.001
        )
      ).length,
      groundLifeRouteIntrusions: groundLife.filter((placement) =>
        pointNearRoutes(
          placement.x,
          placement.z,
          routes,
          GROUND_LIFE_ROUTE_CLEARANCE_METERS - 0.001
        )
      ).length,
      sourceTreeFamilies: new Set(trees.map((tree) => tree.familyId)).size,
      // Families answer "how many distinct models"; species answers "how many
      // distinct kinds of tree". A site rendered from four seeds of one oak
      // would pass the family count and still look like a plantation.
      sourceTreeSpecies: new Set(
        trees.map(
          (tree) => flowFestTreeFamilyPlan(tree.familyId)?.speciesId ?? "unknown"
        )
      ).size,
      measuredCanopyPlacements,
      infillTreePlacements,
      backdropTreePlacements: backdropTrees.length,
      grassPlacements: grass.length,
      groundLifePlacements: groundLife.length,
    },
  };
}

const BACKDROP_MINIMUM_SPACING_METERS = 10;

/**
 * The measured woodland beyond the property line.
 *
 * Austen, 2026-09-03: "when I look off of the land the trees are nonexistent."
 * The land was never bare — the LiDAR canopy raster covers a full square
 * kilometre and 38.9% of its samples outside the site clear the tall-canopy
 * threshold, against 43.8% inside. Only the site was ever sampled, because
 * every ecology pass reads `activeBoundsWorldMeters`. This one reads the whole
 * raster and subtracts the window the site pass already covered.
 *
 * Spacing is looser than the site's 7.5 m because these trees exist to close
 * the horizon, not to be walked through: the nearest is 150 m from anywhere a
 * player stands, and the ridge lines read as continuous canopy well before the
 * stems resolve. Registered routes and zones are not consulted — none of them
 * reach out here, and the per-sample segment distance is what makes the site
 * pass expensive.
 */
function deriveBackdropTrees(
  contract: FlowFestRuntimeContract,
  terrain: ImportedTerrainDataV2,
  canopy: FlowFestCanopyEvidence,
  speciesPlan: FlowFestTreeSpeciesPlan | null
): FlowFestForestTreePlacement[] {
  return deriveFlowFestCanopyPeaks(contract, terrain, canopy, {
    bounds: terrain.worldBounds,
    excludeBounds: contract.surfaceEvidenceProxy.activeBoundsWorldMeters,
    minimumSpacingMeters: BACKDROP_MINIMUM_SPACING_METERS,
    avoidRegisteredSurfaces: false,
  }).map((peak, index) => {
    const rng = makeRng(
      childSeed(FLOW_FEST_MASTER_SEED, `forest-backdrop:${peak.x}:${peak.z}`)
    );
    const renderedHeightMeters = clamp(
      peak.measuredHeightMeters * (0.62 + rng() * 0.08),
      7.5,
      19
    );
    const groundY = sampleFlowFestTerrainWorldY(terrain, peak.x, peak.z);
    const cast = castTreeFamily({
      speciesPlan,
      index,
      x: peak.x,
      z: peak.z,
      groundY,
      renderedHeightMeters,
      neighborhoodHighReturnRatio: peak.neighborhoodHighReturnRatio,
      rng,
    });
    return buildTreePlacement(
      peak.x,
      groundY,
      peak.z,
      peak.measuredHeightMeters,
      renderedHeightMeters,
      cast,
      rng
    );
  });
}

function buildTreePlacement(
  x: number,
  groundY: number,
  z: number,
  measuredHeightMeters: number,
  renderedHeightMeters: number,
  cast: {
    familyId: FlowFestForestTreeFamilyId;
    trunkHeightMeters: number | null;
  },
  rng: () => number
): FlowFestForestTreePlacement {
  const familyId = cast.familyId;
  const proceduralTrunkHeight = renderedHeightMeters * (0.68 + rng() * 0.05);
  return {
    x,
    y: groundY,
    z,
    rotation: rng() * Math.PI * 2,
    scale: 1,
    colorIndex: 0,
    measuredHeightMeters,
    renderedHeightMeters,
    // This is the COLLISION cylinder's height, not the clear bole under the
    // crown; the visible bole is baked into the family's geometry. A layout
    // that measured a real trunk supplies it here, clamped so a bad row in the
    // layout data cannot produce a knee-high or floating collider.
    trunkHeightMeters: clamp(
      cast.trunkHeightMeters ?? proceduralTrunkHeight,
      1.5,
      renderedHeightMeters
    ),
    // The collision trunk tracks the family's measured bole, so a thick-boled
    // redcedar blocks the avatar at its rendered width instead of at a
    // one-size cylinder it visibly overhangs.
    trunkRadiusMeters: clamp(
      renderedHeightMeters * trunkRadiusRatio(familyId),
      0.2,
      1.9
    ),
    crownRadiusMeters: clamp(
      renderedHeightMeters * (0.27 + rng() * 0.035),
      2.15,
      5.1
    ),
    familyId,
  };
}

const INFILL_GRID_METERS = 8;
const INFILL_MINIMUM_CANOPY_OFFSET_METERS = 5;
const INFILL_MINIMUM_TREE_SPACING_METERS = 4.5;
/** Fraction of qualifying grid cells that actually receive an infill tree. */
const INFILL_ACCEPTANCE = 0.62;

/**
 * The LiDAR peak detector only yields one tree per local canopy maximum, which
 * under-counts closed woodland: broad connected canopy reads as a single peak
 * and the stand renders sparse. This pass walks a jittered grid and plants a
 * tree wherever the canopy raster proves real overhead growth
 * ({@link INFILL_MINIMUM_CANOPY_OFFSET_METERS}) with no measured tree nearby —
 * so density returns only where the survey says trees actually are, never on
 * routes, zones, or open meadow.
 */
function appendCanopyInfillTrees(
  contract: FlowFestRuntimeContract,
  terrain: ImportedTerrainDataV2,
  canopy: FlowFestCanopyEvidence,
  routes: FlowFestRuntimeSegment[],
  trees: FlowFestForestTreePlacement[],
  speciesPlan: FlowFestTreeSpeciesPlan | null
): void {
  const bounds = contract.surfaceEvidenceProxy.activeBoundsWorldMeters;
  const spacingSquared =
    INFILL_MINIMUM_TREE_SPACING_METERS * INFILL_MINIMUM_TREE_SPACING_METERS;
  for (
    let gridZ = Math.ceil(bounds.minZ);
    gridZ <= Math.floor(bounds.maxZ);
    gridZ += INFILL_GRID_METERS
  ) {
    for (
      let gridX = Math.ceil(bounds.minX);
      gridX <= Math.floor(bounds.maxX);
      gridX += INFILL_GRID_METERS
    ) {
      const rng = makeRng(
        childSeed(FLOW_FEST_MASTER_SEED, `forest-infill:${gridX}:${gridZ}`)
      );
      const x = gridX + (rng() - 0.5) * 6.4;
      const z = gridZ + (rng() - 0.5) * 6.4;
      if (x < bounds.minX || x > bounds.maxX) continue;
      if (z < bounds.minZ || z > bounds.maxZ) continue;
      const canopyOffsetMeters = sampleCanopyOffsetMeters(terrain, canopy, x, z);
      if (canopyOffsetMeters < INFILL_MINIMUM_CANOPY_OFFSET_METERS) continue;
      if (pointNearRoutes(x, z, routes, 3.2)) continue;
      if (pointInsideRegisteredZone(contract, x, z)) continue;
      if (
        trees.some((tree) => {
          const deltaX = tree.x - x;
          const deltaZ = tree.z - z;
          return deltaX * deltaX + deltaZ * deltaZ < spacingSquared;
        })
      ) {
        continue;
      }
      if (rng() > INFILL_ACCEPTANCE) continue;

      const renderedHeightMeters = clamp(
        canopyOffsetMeters * (0.62 + rng() * 0.08),
        7.5,
        19
      );
      const groundY = sampleFlowFestTerrainWorldY(terrain, x, z);
      // The gate already proved connected canopy overhead, so the infill point
      // sits inside a stand; the stand-density ratio reflects that.
      const cast = castTreeFamily({
        speciesPlan,
        index: trees.length,
        x,
        z,
        groundY,
        renderedHeightMeters,
        neighborhoodHighReturnRatio: 0.78,
        rng,
      });
      trees.push(
        buildTreePlacement(
          x,
          groundY,
          z,
          canopyOffsetMeters,
          renderedHeightMeters,
          cast,
          rng
        )
      );
    }
  }
}

function pointInsideRegisteredZone(
  contract: FlowFestRuntimeContract,
  x: number,
  z: number
): boolean {
  return contract.zones.some((zone) => {
    const radiusX = zone.radiusMeters ?? zone.searchRadiusXMeters ?? 0;
    const radiusZ = zone.radiusMeters ?? zone.searchRadiusZMeters ?? 0;
    if (radiusX <= 0 || radiusZ <= 0) return false;
    const normalizedX = (x - zone.center.x) / radiusX;
    const normalizedZ = (z - zone.center.z) / radiusZ;
    return normalizedX * normalizedX + normalizedZ * normalizedZ <= 1;
  });
}

function mergeEcologyRoutes(
  contract: FlowFestRuntimeContract,
  campPlan: FlowFestCampPlan | null
): FlowFestRuntimeSegment[] {
  const routes = uniqueFlowFestSurfaceSegments(contract);
  if (!campPlan) return routes;
  const planLines = allFlowFestCampPlanLines(campPlan);
  const byId = new Map(routes.map((route) => [route.id, route]));
  for (const line of planLines)
    byId.set(line.id, flowFestCampPlanLineToRuntimeSegment(line));
  return [...byId.values()];
}

function appendRegisteredZoneGrass(
  contract: FlowFestRuntimeContract,
  terrain: ImportedTerrainDataV2,
  routes: FlowFestRuntimeSegment[],
  grass: FlowFestForestGrassPlacement[]
): void {
  const spacingMeters = 1.05;
  for (const zone of contract.zones) {
    const radiusX = zone.radiusMeters ?? zone.searchRadiusXMeters ?? 0;
    const radiusZ = zone.radiusMeters ?? zone.searchRadiusZMeters ?? 0;
    if (radiusX <= 0 || radiusZ <= 0) continue;
    for (let localZ = -radiusZ; localZ <= radiusZ; localZ += spacingMeters) {
      for (let localX = -radiusX; localX <= radiusX; localX += spacingMeters) {
        for (let tuft = 0; tuft < 3; tuft += 1) {
          const rng = makeRng(
            childSeed(
              FLOW_FEST_MASTER_SEED,
              `zone-grass:${zone.id}:${localX.toFixed(2)}:${localZ.toFixed(2)}:${tuft}`
            )
          );
          const x = zone.center.x + localX + (rng() - 0.5) * 0.86;
          const z = zone.center.z + localZ + (rng() - 0.5) * 0.86;
          const normalizedX = (x - zone.center.x) / radiusX;
          const normalizedZ = (z - zone.center.z) / radiusZ;
          if (
            normalizedX * normalizedX + normalizedZ * normalizedZ > 1 ||
            pointNearRoutes(x, z, routes, GRASS_ROUTE_CLEARANCE_METERS) ||
            rng() > 0.9
          ) {
            continue;
          }
          const tierRoll = rng();
          grass.push({
            x,
            y: sampleFlowFestTerrainWorldY(terrain, x, z) + 0.012,
            z,
            rotation: rng() * Math.PI * 2,
            widthMeters: 0.12 + rng() * 0.1,
            heightMeters: 0.2 + rng() * 0.14,
            species: "summer-sward",
            tier:
              tierRoll < 0.62 ? "base" : tierRoll < 0.92 ? "medium" : "high",
            colorIndex: Math.floor(rng() * 4),
          });
        }
      }
    }
  }
}

/**
 * Habitat casting for the measured woodland. Ground height, rendered height,
 * and the LiDAR neighborhood's high-return ratio sort each placement into a
 * habitat pool; the families in each pool come straight from the species
 * catalog, so a species added there is cast automatically and no list here can
 * drift out of sync with what was actually baked.
 *
 * A catalog role names a form's ecological home. A pool names which forms this
 * particular site casts in one habitat. They are related but not the same
 * axis, and collapsing them was wrong in two directions: the open-grown role
 * held seven families competing for the eleven sparse-neighborhood placements
 * this closed woodlot produces, so three of them never rendered at all, and
 * the understory role holds exactly one species, so every one of the 237
 * small trees came out a boxelder.
 *
 * The high-return ratio is the light measurement that separates them. Eastern
 * redcedar is the shade-intolerant pioneer of Ohio and Indiana fencerows and
 * old-field margins at ten to fifteen metres, so it is cast where the canopy
 * neighborhood is open. Boxelder is the disturbed-ground volunteer that
 * tolerates a closed neighborhood, so it takes the suppressed small trees.
 * White oak and black walnut keep their wide-crowned open-grown forms for the
 * full-height trees standing clear of the stand.
 *
 * Selection within a pool rotates by placement index plus a stable
 * per-48m-cell phase, so a stand reads as a community rather than a tiling
 * pattern. With 35 generated families across 12 forms — each form calibrated
 * to its own crown spread and clear bole, each variant a different ez-tree
 * seed — no two neighbours share a silhouette.
 */
const FLOW_FEST_DAMP_FAMILIES = flowFestTreeFamiliesForRole("damp");
const FLOW_FEST_STAND_FAMILIES = flowFestTreeFamiliesForRole("stand");
const FLOW_FEST_SNAG_FAMILIES = flowFestTreeFamiliesForRole("snag");

/** Small trees under a closed neighborhood: the disturbed-ground volunteer. */
const FLOW_FEST_SUPPRESSED_FAMILIES =
  flowFestTreeFamiliesForRole("understory");

/** Small trees with light: the light-demanding margin and fencerow pioneer. */
const FLOW_FEST_SCRUB_MARGIN_FAMILIES =
  flowFestTreeFamiliesForSpecies("eastern-redcedar");

/**
 * Full-height trees with room to spread. Derived by set difference so that
 * adding another open-grown form to the catalog reaches this pool without a
 * second list to maintain, while the redcedar forms stay with the light-gap
 * small trees where their ten-to-fifteen-metre stature actually stands.
 */
const FLOW_FEST_OPEN_GROWN_FAMILIES = flowFestTreeFamiliesForRole("open").filter(
  (familyId) => !FLOW_FEST_SCRUB_MARGIN_FAMILIES.includes(familyId)
);

/**
 * A 5x5 LiDAR window, so the ratio moves in steps of 0.04. Above this the
 * neighborhood reads as continuous canopy; at or below it there is a gap.
 */
const CLOSED_NEIGHBORHOOD_RATIO = 0.72;

/**
 * Standing dead wood is habitat punctuation — rare, scattered, never a stand.
 * The snag families are generated with a zero leaf count, so they render as
 * bare wood rather than a live crown on a dead trunk.
 */
const SNAG_PROBABILITY = 0.012;

function chooseTreeFamily(
  renderedHeightMeters: number,
  groundY: number,
  neighborhoodHighReturnRatio: number,
  x: number,
  z: number,
  index: number,
  rng: () => number
): FlowFestForestTreeFamilyId {
  const closedNeighborhood =
    neighborhoodHighReturnRatio > CLOSED_NEIGHBORHOOD_RATIO;
  const families =
    rng() < SNAG_PROBABILITY
      ? FLOW_FEST_SNAG_FAMILIES
      : groundY < 8.5
        ? FLOW_FEST_DAMP_FAMILIES
        : renderedHeightMeters < 10.2
          ? closedNeighborhood
            ? FLOW_FEST_SUPPRESSED_FAMILIES
            : FLOW_FEST_SCRUB_MARGIN_FAMILIES
          : closedNeighborhood
            ? FLOW_FEST_STAND_FAMILIES
            : FLOW_FEST_OPEN_GROWN_FAMILIES;
  const habitatRng = makeRng(
    childSeed(
      FLOW_FEST_MASTER_SEED,
      `forest-habitat:${Math.floor(x / 48)}:${Math.floor(z / 48)}`
    )
  );
  const habitatPhase = Math.floor(habitatRng() * families.length);
  const variation = rng() < 0.28 ? 1 : 0;
  return families[(index + habitatPhase + variation) % families.length]!;
}

/**
 * One tree's casting decision: which generated family renders here, and
 * whether the site layout dictated a trunk height for it.
 *
 * The species plan is consulted first and habitat casting is the fallback, so
 * a layout that has an opinion about one grove still gets ecologically sane
 * trees everywhere else. An assignment naming something the catalog does not
 * contain is a layout bug and throws rather than silently reverting to
 * habitat casting — a silently ignored species id is exactly the failure that
 * would make a derived layout look correct while rendering the wrong woodland.
 */
function castTreeFamily(input: {
  speciesPlan: FlowFestTreeSpeciesPlan | null;
  index: number;
  x: number;
  z: number;
  groundY: number;
  renderedHeightMeters: number;
  neighborhoodHighReturnRatio: number;
  rng: () => number;
}): { familyId: FlowFestForestTreeFamilyId; trunkHeightMeters: number | null } {
  const assignment =
    input.speciesPlan?.resolve({
      index: input.index,
      x: input.x,
      z: input.z,
      groundY: input.groundY,
      renderedHeightMeters: input.renderedHeightMeters,
    }) ?? null;

  if (assignment) {
    const familyId = resolveFlowFestTreeFamilyId(
      assignment.speciesId,
      input.index
    );
    if (!familyId) {
      throw new Error(
        `Flow Fest species plan assigned "${assignment.speciesId}" at (${input.x}, ${input.z}), which is not a species, form, or family in flow-fest-tree-species.ts.`
      );
    }
    return {
      familyId,
      trunkHeightMeters: assignment.trunkHeightMeters ?? null,
    };
  }

  return {
    familyId: chooseTreeFamily(
      input.renderedHeightMeters,
      input.groundY,
      input.neighborhoodHighReturnRatio,
      input.x,
      input.z,
      input.index,
      input.rng
    ),
    trunkHeightMeters: null,
  };
}

function sampleCanopyOffsetMeters(
  terrain: ImportedTerrainDataV2,
  canopy: FlowFestCanopyEvidence,
  x: number,
  z: number
): number {
  const column = Math.round(
    ((x - terrain.worldBounds.minX) /
      (terrain.worldBounds.maxX - terrain.worldBounds.minX)) *
      (canopy.width - 1)
  );
  const row = Math.round(
    ((z - terrain.worldBounds.minZ) /
      (terrain.worldBounds.maxZ - terrain.worldBounds.minZ)) *
      (canopy.height - 1)
  );
  if (column < 0 || row < 0 || column >= canopy.width || row >= canopy.height) {
    return 0;
  }
  const value = canopy.offsetsCentimeters[row * canopy.width + column];
  return value == null || value === 65535 ? 0 : value / 100;
}

function pointNearRoutes(
  x: number,
  z: number,
  routes: FlowFestRuntimeSegment[],
  extraClearanceMeters: number
): boolean {
  return routes.some((route) => {
    const clearance = route.widthMeters / 2 + extraClearanceMeters;
    for (let index = 1; index < route.points.length; index += 1) {
      if (
        distanceToSegment(
          x,
          z,
          route.points[index - 1]!,
          route.points[index]!
        ) <= clearance
      ) {
        return true;
      }
    }
    return false;
  });
}

function distanceToSegment(
  x: number,
  z: number,
  start: FlowFestRuntimePoint,
  end: FlowFestRuntimePoint
): number {
  const deltaX = end.x - start.x;
  const deltaZ = end.z - start.z;
  const lengthSquared = deltaX * deltaX + deltaZ * deltaZ;
  if (lengthSquared === 0) return Math.hypot(x - start.x, z - start.z);
  const progress = Math.max(
    0,
    Math.min(
      1,
      ((x - start.x) * deltaX + (z - start.z) * deltaZ) / lengthSquared
    )
  );
  return Math.hypot(
    x - (start.x + deltaX * progress),
    z - (start.z + deltaZ * progress)
  );
}

function clamp(value: number, minimum: number, maximum: number): number {
  return Math.max(minimum, Math.min(maximum, value));
}
