/**
 * Round-trip loop-detection audit across ALL FIVE detector implementations,
 * grounded on REAL generated loops.
 *
 * Fixtures: tests/fixtures/loop-audit/real-loop-fixtures.json — generated by
 * scripts/generate-loop-audit-fixtures.mjs, which drives the exact production
 * pipeline (Diamond CSV dataset -> SequenceBuilder beam search with LOOP seam
 * targeting -> executeLOOPSpec). This is the same path behind MCP
 * `generate_sequence loopType=...` and the app's circular generation, so the
 * loops are canonical instances of their LOOPType — no hand-built-partial
 * artifacts (the engine-side harness's known trust boundary).
 *
 * Detectors under audit (numbering from the 2026-07-03 handoff):
 *   #1 functional detectLOOPFromSteps   (engine; backs MCP detect_loop_pattern
 *                                        + scripts/import-sequence.cjs)
 *   #2 class loopDetectorClass          (engine)
 *   #3 app class LOOPDetector           (src/lib/shared/create — hydration,
 *                                        public-index-syncer, QR routes)
 *   #4 loop-labeler pipeline            (src/lib/features/loop-labeler)
 *   #5 .cjs labelers                    (scripts/auto-label-loops.cjs +
 *                                        scripts/validate-loop-detection.cjs)
 *
 * The audit soft-collects a recovery table and prints it once. The hard
 * assertions at the bottom lock the per-detector verdicts confirmed on real
 * loops (see docs/superpowers/handoffs/2026-07-03-loop-detection-audit-handoff.md
 * §5 and the completion note in the spec).
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

// #1 + #2 — engine detectors
import {
  detectLOOPFromSteps,
  loopDetectorClass,
} from "@tka/sequence-engine/loop";

// #3 — app class detector (hydration path)
import { loopDetector as appLoopDetector } from "$lib/shared/create/services/loop-detector";
import type { SequenceData } from "$lib/shared/foundation/domain/models/sequence-data";

// #4 — loop-labeler pipeline
import { loopDetector as labelerLoopDetector } from "$lib/features/loop-labeler/services/loop-detector";
import type { SequenceEntry } from "$lib/shared/loop-labeler/domain/sequence-models";

// #5 — .cjs labelers (CommonJS scripts; exported for this harness)
const require = createRequire(import.meta.url);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../../..");

const autoLabelCjs = require(path.join(repoRoot, "scripts/auto-label-loops.cjs"));

const validateCjs = require(path.join(repoRoot, "scripts/validate-loop-detection.cjs"));

// Fixtures

interface FixtureMotion {
  motionType: string;
  startLocation: string;
  endLocation: string;
  rotationDirection: string;
  startOrientation: string;
  endOrientation: string;
}

interface FixtureStep {
  id?: string;
  stepNumber: number;
  letter: string | null;
  startPosition: string;
  endPosition: string;
  motions: { left: FixtureMotion; right: FixtureMotion };
}

interface FixtureSample {
  loopType: string;
  seedWord: string;
  derivedWord: string;
  letterStepCount: number;
  steps: FixtureStep[];
}

const FIXTURES: Record<string, FixtureSample[]> = JSON.parse(
  readFileSync(
    path.join(repoRoot, "tests/fixtures/loop-audit/real-loop-fixtures.json"),
    "utf8",
  ),
);

// Adapters — each detector takes a different input shape

/** #1/#2: fixtures are already engine SequenceStep-shaped. */
function toEngineSteps(sample: FixtureSample): FixtureStep[] {
  return sample.steps;
}

/** #3: SequenceData with StepData-like steps (letter steps only). */
function toSequenceData(sample: FixtureSample): SequenceData {
  const letterSteps = sample.steps
    .filter((s) => s.stepNumber > 0)
    .map((s) => ({
      id: s.id ?? `step-${s.stepNumber}`,
      stepNumber: s.stepNumber,
      duration: 1,
      letter: s.letter,
      startPosition: s.startPosition,
      endPosition: s.endPosition,
      motions: {
        left: { ...s.motions.left, color: "blue" },
        right: { ...s.motions.right, color: "red" },
      },
    }));

  return {
    id: "loop-audit",
    name: "loop-audit",
    word: sample.seedWord + sample.derivedWord,
    steps: letterSteps,
    thumbnails: [],
  } as unknown as SequenceData;
}

/** #4/#5: SequenceEntry with fullMetadata.sequence RawStepData beats. */
function toSequenceEntry(sample: FixtureSample): SequenceEntry {
  const start = sample.steps.find((s) => s.stepNumber === 0)!;
  const raw = [
    {
      beat: 0,
      sequenceStartPosition: start.startPosition,
      endPos: start.endPosition,
    },
    ...sample.steps
      .filter((s) => s.stepNumber > 0)
      .map((s) => ({
        beat: s.stepNumber,
        letter: s.letter ?? "",
        startPos: s.startPosition,
        endPos: s.endPosition,
        leftAttributes: {
          motionType: s.motions.left.motionType,
          startLoc: s.motions.left.startLocation,
          endLoc: s.motions.left.endLocation,
          propRotDir: s.motions.left.rotationDirection,
        },
        rightAttributes: {
          motionType: s.motions.right.motionType,
          startLoc: s.motions.right.startLocation,
          endLoc: s.motions.right.endLocation,
          propRotDir: s.motions.right.rotationDirection,
        },
      })),
  ];

  return {
    id: "loop-audit",
    word: sample.seedWord + sample.derivedWord,
    isCircular: true,
    loopType: null,
    thumbnails: [],
    sequenceLength: sample.letterStepCount,
    gridMode: "diamond",
    fullMetadata: { sequence: raw },
  } as SequenceEntry;
}

// ---------------------------------------------------------------------------
// Component extraction per detector (normalized to sorted primitive ids)
// ---------------------------------------------------------------------------

const PRIMITIVES = [
  "rotated",
  "mirrored",
  "flipped",
  "swapped",
  "inverted",
  "rewound",
] as const;

/** Flatten tokens like "mirrored+swapped+inverted" into primitive ids. */
function normalize(tokens: readonly string[]): string[] {
  const out = new Set<string>();
  for (const token of tokens) {
    for (const prim of PRIMITIVES) {
      if (token.includes(prim)) out.add(prim);
    }
  }
  return [...out].sort();
}

function functionalComponents(sample: FixtureSample): string[] {
  return normalize(detectLOOPFromSteps(toEngineSteps(sample) as never).components);
}

function engineClassComponents(sample: FixtureSample): string[] {
  const r = loopDetectorClass.detectLOOPType(toEngineSteps(sample) as never);
  if (!r.spec?.left) return [];
  return normalize([...r.spec.left.components.keys()].map(String));
}

function appClassComponents(sample: FixtureSample): string[] {
  const r = appLoopDetector.detectLOOPType(toSequenceData(sample));
  if (!r.isCircular || !r.loopType) return [];
  return normalize([String(r.loopType)]);
}

function labelerComponents(sample: FixtureSample): string[] {
  const r = labelerLoopDetector.detectLOOP(toSequenceEntry(sample));
  return normalize(r.components.map(String));
}

function autoLabelComponents(sample: FixtureSample): string[] {
  const r = autoLabelCjs.detectLOOPType(toSequenceEntry(sample));
  return normalize((r.components ?? []).map(String));
}

function validateCjsComponents(sample: FixtureSample): string[] {
  const r = validateCjs.detectLOOPType(toSequenceEntry(sample));
  return normalize((r.components ?? []).map(String));
}

const DETECTORS = {
  "1-functional": functionalComponents,
  "2-engine-class": engineClassComponents,
  "3-app-class": appClassComponents,
  "4-loop-labeler": labelerComponents,
  "5a-auto-label": autoLabelComponents,
  "5b-validate": validateCjsComponents,
} as const;

type DetectorId = keyof typeof DETECTORS;

// ---------------------------------------------------------------------------
// Expectations
// ---------------------------------------------------------------------------

const EXPECTED: Record<string, string[]> = {
  rotated: ["rotated"],
  mirrored: ["mirrored"],
  flipped: ["flipped"],
  swapped: ["swapped"],
  inverted: ["inverted"],
  swapped_inverted: ["inverted", "swapped"],
  rotated_inverted: ["inverted", "rotated"],
  mirrored_swapped: ["mirrored", "swapped"],
  mirrored_inverted: ["inverted", "mirrored"],
  rotated_swapped: ["rotated", "swapped"],
  mirrored_rotated: ["mirrored", "rotated"],
  mirrored_inverted_rotated: ["inverted", "mirrored", "rotated"],
  mirrored_swapped_inverted: ["inverted", "mirrored", "swapped"],
  mirrored_rotated_inverted_swapped: [
    "inverted",
    "mirrored",
    "rotated",
    "swapped",
  ],
  rewound: ["rewound"],
};

const setEq = (a: string[], b: string[]) =>
  a.length === b.length && a.every((x, i) => x === b[i]);
const isSubset = (a: string[], b: string[]) => a.every((x) => b.includes(x));

type Verdict = "PASS" | "PARTIAL" | "EXTRA" | "FAIL";

/**
 * PASS    — exact component recovery
 * PARTIAL — recovered a non-empty strict subset (missed components)
 * EXTRA   — recovered all expected plus false positives
 * FAIL    — wrong or empty
 */
function verdict(actual: string[], expected: string[]): Verdict {
  if (setEq(actual, expected)) return "PASS";
  if (actual.length > 0 && isSubset(actual, expected)) return "PARTIAL";
  if (isSubset(expected, actual)) return "EXTRA";
  return "FAIL";
}

// ---------------------------------------------------------------------------
// The audit
// ---------------------------------------------------------------------------

interface Row {
  type: string;
  sample: number;
  detector: DetectorId;
  expected: string;
  actual: string;
  verdict: Verdict;
}

function runAudit(): Row[] {
  const rows: Row[] = [];
  for (const [type, samples] of Object.entries(FIXTURES)) {
    const expected = EXPECTED[type]!;
    samples.forEach((sample, i) => {
      for (const [id, fn] of Object.entries(DETECTORS)) {
        let actual: string[];
        try {
          actual = fn(sample);
        } catch (e) {
          rows.push({
            type,
            sample: i,
            detector: id as DetectorId,
            expected: expected.join("+"),
            actual: `ERROR: ${(e as Error).message.slice(0, 60)}`,
            verdict: "FAIL",
          });
          return;
        }
        rows.push({
          type,
          sample: i,
          detector: id as DetectorId,
          expected: expected.join("+"),
          actual: actual.join("+") || "(none)",
          verdict: verdict(actual, expected),
        });
      }
    });
  }
  return rows;
}

/** Majority verdict for a (type, detector) cell across samples. */
function cellVerdicts(rows: Row[]): Map<string, { verdicts: Verdict[]; actuals: string[] }> {
  const cells = new Map<string, { verdicts: Verdict[]; actuals: string[] }>();
  for (const r of rows) {
    const key = `${r.type}|${r.detector}`;
    const cell = cells.get(key) ?? { verdicts: [], actuals: [] };
    cell.verdicts.push(r.verdict);
    cell.actuals.push(r.actual);
    cells.set(key, cell);
  }
  return cells;
}

describe("real-loop detector audit (all 5 detectors)", () => {
  const rows = runAudit();
  const cells = cellVerdicts(rows);

  it("prints the recovery table", () => {
    /* eslint-disable no-console */
    console.log(
      "\n=========== REAL-LOOP RECOVERY TABLE (production-generated fixtures) ===========",
    );
    const header = `${"LOOPType".padEnd(36)} ${"detector".padEnd(15)} ${"expected".padEnd(28)} sample actuals -> verdicts`;
    console.log(header);
    console.log("-".repeat(header.length));
    const printed = new Set<string>();
    for (const r of rows) {
      const key = `${r.type}|${r.detector}`;
      if (printed.has(key)) continue;
      printed.add(key);
      const cell = cells.get(key)!;
      console.log(
        `${r.type.padEnd(36)} ${r.detector.padEnd(15)} ${r.expected.padEnd(28)} [${cell.actuals.join(" | ")}] -> ${cell.verdicts.join(",")}`,
      );
    }
    const tally: Record<Verdict, number> = { PASS: 0, PARTIAL: 0, EXTRA: 0, FAIL: 0 };
    for (const r of rows) tally[r.verdict]++;
    console.log(
      `\nTotals across ${rows.length} (type x sample x detector) runs: ` +
        `PASS=${tally.PASS} PARTIAL=${tally.PARTIAL} EXTRA=${tally.EXTRA} FAIL=${tally.FAIL}`,
    );
    /* eslint-enable no-console */
    expect(rows.length).toBeGreaterThan(0);
  });

  // -------------------------------------------------------------------------
  // REGRESSION LOCKS (2026-07-05 audit verdicts).
  //
  // Detectors #1/#2 are locked in the engine package
  // (packages/sequence-engine/tests/loop/detection/real-loop-recovery.test.ts).
  // Here we lock the app-side detectors. Documented gaps (the .cjs labelers'
  // missing swapped_inverted / mirrored_inverted-inversion / rewound paths and
  // the loop-labeler's nested-rotation partials) are intentionally NOT
  // asserted, so fixing them later cannot break this suite.
  // -------------------------------------------------------------------------

  function lock(detector: DetectorId, type: string, sampleIdx: number, expected: string[]) {
    const sample = FIXTURES[type]![sampleIdx]!;
    expect(DETECTORS[detector](sample), `${detector} on ${type}[${sampleIdx}]`).toEqual(expected);
  }

  function lockAllSamples(detector: DetectorId, type: string, expected: string[]) {
    FIXTURES[type]!.forEach((_, i) => lock(detector, type, i, expected));
  }

  it("#3 app-class matches the canonical engine detector on seamless loops", () => {
    // #3 delegates detection to the engine's pair-relation detector; its own
    // circularity gate is stricter (position AND orientation closure).
    lockAllSamples("3-app-class", "rotated", ["rotated"]);
    lockAllSamples("3-app-class", "mirrored", ["mirrored"]);
    lockAllSamples("3-app-class", "flipped", ["flipped"]);
    lockAllSamples("3-app-class", "inverted", ["inverted"]);
    lockAllSamples("3-app-class", "rotated_inverted", ["inverted", "rotated"]);
    lockAllSamples("3-app-class", "mirrored_inverted", ["inverted", "mirrored"]);
    lockAllSamples("3-app-class", "mirrored_rotated", ["mirrored", "rotated"]);
    lockAllSamples("3-app-class", "mirrored_inverted_rotated", ["inverted", "mirrored", "rotated"]);
    lockAllSamples("3-app-class", "rewound", ["rewound"]);
    // Orientation-closed samples of the swap family (the others are gated).
    lock("3-app-class", "swapped", 1, ["swapped"]);
    lock("3-app-class", "swapped", 2, ["swapped"]);
    lock("3-app-class", "swapped_inverted", 1, ["inverted", "swapped"]);
    lock("3-app-class", "mirrored_swapped", 0, ["mirrored", "swapped"]);
    lock("3-app-class", "mirrored_swapped", 1, ["mirrored", "swapped"]);
  });

  it("#3 gate: loops whose orientations do not close are NOT stamped", () => {
    // These samples close positionally but end with orientations flipped
    // in->out (generator emits halved swap-family loops without orientation
    // parity). isSeamlesslyLoopable must keep rejecting them — hydration only
    // stamps loopType on seamless loops.
    for (const [type, idx] of [
      ["swapped", 0],
      ["swapped_inverted", 0],
      ["swapped_inverted", 2],
      ["mirrored_swapped", 2],
      ["rotated_swapped", 1],
      ["rotated_swapped", 2],
    ] as const) {
      const r = appLoopDetector.detectLOOPType(toSequenceData(FIXTURES[type]![idx]!));
      expect(r.isCircular, `${type}[${idx}] must fail the seamless gate`).toBe(false);
    }
  });

  it("#4 loop-labeler: canonical types recover exactly (incl. the rewound-drop fix)", () => {
    lockAllSamples("4-loop-labeler", "rotated", ["rotated"]);
    lockAllSamples("4-loop-labeler", "mirrored", ["mirrored"]);
    lockAllSamples("4-loop-labeler", "flipped", ["flipped"]);
    lockAllSamples("4-loop-labeler", "swapped", ["swapped"]);
    lockAllSamples("4-loop-labeler", "inverted", ["inverted"]);
    lockAllSamples("4-loop-labeler", "swapped_inverted", ["inverted", "swapped"]);
    lockAllSamples("4-loop-labeler", "rotated_inverted", ["inverted", "rotated"]);
    lockAllSamples("4-loop-labeler", "mirrored_swapped", ["mirrored", "swapped"]);
    lockAllSamples("4-loop-labeler", "mirrored_inverted", ["inverted", "mirrored"]);
    // The fix: a pure rewound loop used to fall through to the freeform
    // fallback and lose its (correct) rewound candidate.
    lockAllSamples("4-loop-labeler", "rewound", ["rewound"]);
  });

  it("#4 loop-labeler: nested inner rotation is recovered (2026-07-12 fix)", () => {
    // The former "nested-rotation partials" gap: the inner rotation completes
    // its full cycle within each half, so seam-pair comparison never saw it.
    // detectNestedRotation recovers it from the closed first half.
    lockAllSamples("4-loop-labeler", "mirrored_inverted_rotated", [
      "inverted",
      "mirrored",
      "rotated",
    ]);
    // Sample 2 over-detects (pre-existing EXTRA, unrelated) — lock 0 and 1.
    lock("4-loop-labeler", "mirrored_rotated", 0, ["mirrored", "rotated"]);
    lock("4-loop-labeler", "mirrored_rotated", 1, ["mirrored", "rotated"]);
    // Samples 1-2 recover (none) — swap-family generator orientation-parity
    // issue documented in the 2026-07-05 audit, not a detection gap.
    lock("4-loop-labeler", "mirrored_rotated_inverted_swapped", 0, [
      "inverted",
      "mirrored",
      "rotated",
      "swapped",
    ]);
  });

  it("#5 .cjs labelers: solid coverage stays solid", () => {
    for (const d of ["5a-auto-label", "5b-validate"] as const) {
      lockAllSamples(d, "rotated", ["rotated"]);
      lockAllSamples(d, "mirrored", ["mirrored"]);
      lockAllSamples(d, "flipped", ["flipped"]);
      lockAllSamples(d, "inverted", ["inverted"]);
      lockAllSamples(d, "mirrored_swapped", ["mirrored", "swapped"]);
    }
    lockAllSamples("5a-auto-label", "rotated_inverted", ["inverted", "rotated"]);
    lockAllSamples("5a-auto-label", "swapped", ["swapped"]);
  });
});
