<script lang="ts">
  import Seo from "$lib/shared/components/Seo.svelte";
  import YutaCapLiveDemo from "./_components/YutaCapLiveDemo.svelte";
  import "$lib/shared/landing/styles/public-editorial.css";

  const TITLE = "CAPs: Continuous Assembly Patterns | The Kinetic Alphabet";
  const DESCRIPTION =
    "The history and mathematics of CAPs: coined on the Home of Poi forums in 2009, built on a trochoid framework, and still shaping how spinners think about cyclic patterns.";
  const URL = "https://tkaflowarts.com/notation/caps";

  const THREAD_URL =
    "https://www.homeofpoi.com/en/community/forums/topics/891193/What-are-CAP-s";

  // Filled from the verified modern-media research pass. Each id is a YouTube
  // video id confirmed alive via oembed at authoring time.
  type MediaItem = {
    id: string;
    title: string;
    creator: string;
    year: string;
    note: string;
  };
  const MODERN_MEDIA: MediaItem[] = [
    {
      id: "DyK42suXQUk",
      title: "Tech Poi Blog #213: What is a CAP?",
      creator: "DrexFactor Poi",
      year: "2011",
      note: "The definitional explainer, addressing the community debate head on.",
    },
    {
      id: "B-o3E7Ix5uM",
      title: "Basic Poi Dancing Tutorial: C-CAPs",
      creator: "DrexFactor Poi",
      year: "2012",
      note: "The tutorial that put the C-CAP into standard vocabulary.",
    },
    {
      id: "UBx2IZVzSVA",
      title: "Poi Flowers: Learning CAPs (Capped Antispin Patterns)",
      creator: "Nick Woolsey · PlayPoi",
      year: "2016",
      note: "The canonical learner's treatment, and the source of that acronym expansion.",
    },
    {
      id: "Lh5wtTddhEE",
      title: "Charlie's 9-Square Theory for Poi #3",
      creator: "Charlie",
      year: "~2015",
      note: "The geometry that formalized how 8-step CAPs are built.",
    },
    {
      id: "dBn6kz_7huc",
      title: "How to do 8-Step CAPs for Poi: 1-minute tutorial",
      creator: "DrexFactor Poi",
      year: "2017",
      note: "The 8-step CAP in sixty seconds.",
    },
    {
      id: "Chf9IAhqp7M",
      title: "Poi CAPs Tutorial: Basic C-CAPs",
      creator: "DrexFactor Poi",
      year: "2020",
      note: "The modern remake of the classic C-CAP lesson.",
    },
  ];

  // Own recreations of the thread's pattern illustrations, generated by
  // scripts/generate-caps-trochoids.mjs from the exact parameters Damien
  // posted. The originals he hotlinked belong to mathcurve.com.
  const PATTERNS: { file: string; label: string; kind: string }[] = [
    { file: "rosette-1-4.svg", label: "1 4 ; 1 1", kind: "Inspin rosette" },
    { file: "rosette-1-neg6.svg", label: "1 -6 ; 1 1", kind: "Antispin rosette" },
    { file: "cycloid-1-4.svg", label: "1 4 ; 1 1/5", kind: "Cycloid" },
    { file: "antispin-1-neg3.svg", label: "1 -3 ; 1 1", kind: "Three-petal antispin" },
    { file: "cycloid-1-neg3.svg", label: "1 -3 ; 1 1/2", kind: "Antispin cycloid" },
    { file: "pattern-2-neg5.svg", label: "2 -5 ; 1 1", kind: "Two arm turns" },
    { file: "pattern-3-2.svg", label: "3 2 ; 1 1", kind: "Three arm turns" },
  ];
</script>

<Seo title={TITLE} description={DESCRIPTION} canonical={URL} ogType="article">
  {@html `<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": "CAPs: Continuous Assembly Patterns",
    "url": "${URL}",
    "description": "${DESCRIPTION}",
    "inLanguage": "en-US",
    "author": { "@type": "Person", "name": "Austen Cloud", "url": "https://tkaflowarts.com/about" },
    "publisher": { "@type": "Organization", "name": "The Kinetic Alphabet", "url": "https://tkaflowarts.com/" }
  }
  </script>`}
  {@html `<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://tkaflowarts.com/" },
      { "@type": "ListItem", "position": 2, "name": "Notation", "item": "https://tkaflowarts.com/notation" },
      { "@type": "ListItem", "position": 3, "name": "CAPs", "item": "${URL}" }
    ]
  }
  </script>`}
</Seo>

<div class="editorial">
  <a class="back-link" href="/notation">← Flow Arts Notation</a>

  <header class="editorial-header">
    <h1 class="page-title">CAPs: Continuous Assembly Patterns</h1>
    <p class="page-subtitle">
      Before this site formalized LOOPs, poi spinners were already composing
      cyclic patterns. They named the idea first. This is their story, told the
      way it deserves: with the pattern spinning.
    </p>
  </header>

  <!-- HERO: the Yuta CAP, drawn live by a club -->
  <section class="editorial-section" style="--accent: #38bdf8">
    <div class="cap-hero">
      <div class="cap-hero-stage">
        <YutaCapLiveDemo />
      </div>
      <div class="cap-hero-copy prose">
        <span class="section-kicker">One pattern, two fragments</span>
        <p>
          This is a CAP: a closed pattern assembled from fragments of simpler
          ones. The club here is drawing the one the whole idea grew around.
          Half a cycle of isolation, half a cycle of antispin, joined into a
          single curve that repeats forever.
        </p>
        <p class="cap-credit">
          Spinners saw this pattern in Yuta's spinning and took it apart on a
          forum. Notation and construction: Damien (posting as Zaltymbunk),
          <a href={THREAD_URL}>Home of Poi, 2009</a>.
        </p>
      </div>
    </div>
  </section>

  <!-- BREAK IT DOWN -->
  <section class="editorial-section" style="--accent: #a78bfa">
    <span class="section-kicker">Break it down</span>
    <h2 class="section-title">Four steps, two fragments</h2>
    <div class="prose">
      <p>Slow the animation down and the curve splits cleanly in half.</p>
    </div>
    <ul class="bullet-list">
      <li>
        <strong>The isolation half.</strong> The hand carries the club from
        east to south, then south to west. Zero turns: the club keeps pointing
        away from center the whole way, so the tip sweeps a wide, even arc.
      </li>
      <li>
        <strong>The antispin half.</strong> The hand retraces from west to
        south, then south to east, and the club adds one full turn on each
        step. That extra rotation against the hand's arc flowers the trace
        into petals.
      </li>
      <li>
        <strong>The join.</strong> End where you started, pointing the way you
        started, and the curve closes. A closed curve repeats forever. That is
        the whole trick, and it works for any pair of fragments that meet
        cleanly.
      </li>
    </ul>
    <div class="cap-lens-duo">
      <figure class="cap-lens">
        <img
          src="/caps/yuta-cap.svg"
          alt="The Yuta CAP drawn as a continuous curve: an isolation arc joined to antispin petals"
          width="360"
          height="360"
          loading="lazy"
        />
        <figcaption>
          The full trace, redrawn from Damien's published parameters:
          <code>1 0 ; 1 3/4 ; 1/2</code> assembled with
          <code>-1 4 ; 1 3/4 ; 1/2</code>.
        </figcaption>
      </figure>
      <figure class="cap-lens">
        <img
          src="/caps/original/cap-yuta-halfcycle.jpg"
          alt="Damien's original 2009 plot of the Yuta CAP with the two fragments in two colors"
          width="360"
          height="308"
          loading="lazy"
        />
        <figcaption>
          Damien's original 2009 plot of the same pattern, fragments in two
          colors. <a href={THREAD_URL}>From the origin thread</a>.
        </figcaption>
      </figure>
    </div>
  </section>

  <!-- HOW TKA REFLECTS IT -->
  <section class="editorial-section" style="--accent: #fbbf24">
    <span class="section-kicker">What came before, reflected</span>
    <h2 class="section-title">The Kinetic Alphabet reads the same movement</h2>
    <div class="prose">
      <p>
        CAPs read paths: the shape a prop tip draws through space, composed one
        hand at a time and overlaid. The Kinetic Alphabet arrived at the same
        infinity from the other side. It reads steps: whole-body snapshots of
        both hands at once, chained into speakable words. The four steps the
        club performs above are exactly what TKA writes down as letters, and
        its <a href="/notation/loops">LOOP algebra</a> is the machinery for
        closing step chains into cycles that repeat forever, the same craving
        CAPs answered in 2009.
      </p>
      <p>
        Neither system contains the other. Damien himself drew the matching
        distinction inside his own framework: serial assembly (CAPs) against
        parallel superposition (hybrids). They are parallel discoveries about
        the same infinity, seventeen years apart in their telling.
      </p>
    </div>
  </section>

  <!-- THE STORY -->
  <section class="editorial-section" style="--accent: #f472b6">
    <span class="section-kicker">The story</span>
    <h2 class="section-title">Named on a forum, built at a burn</h2>
    <div class="prose">
      <p>
        At Burning Man 2007, a group of spinners at OMCC, including Alien Jon,
        Noel, Greg, Jordan, and Zan, started pulling apart what made complex
        poi patterns work. A French spinner named Damien showed up with his own
        explorations of composite cyclic patterns. Back on the Home of Poi
        forums, in a thread analyzing Yuta's spinning, Damien coined the term:
        Continuous Assembly Patterns. Alien Jon said it plainly in the origin
        thread: "I got the term from Damien."
      </p>
      <p>
        The definition he gave was broad and precise at once. A CAP is cyclic,
        and it is the assembly of two or more elementary patterns, each
        iterated one or more times. Not a move. A way of building moves out of
        fragments of simpler ones.
      </p>
      <p>
        The community argued about it, the way every good community argues
        about names. One poster thought these were called "pac men." Another
        pointed out that a cap is obviously a type of small hat. DrexFactor
        defended the term with a comparison to mathematics: umbrella words
        bundle concepts, give learners a map, and predict patterns nobody has
        performed yet. Over the following years, everyday usage narrowed "cap"
        to one famous member of the family: the C-CAP, the alternation of an
        extension arc with antispin petals. The broad idea stayed broader than
        its name.
      </p>
      <p>
        The origin thread is still up, seventeen years later. As of July 2026
        it has no Internet Archive snapshot. The diagrams on this page preserve
        its mathematics with credit to the people who made them.
      </p>
    </div>
  </section>

  <!-- THE ORIGINAL MATH, KEPT LIGHT -->
  <section class="editorial-section" style="--accent: #34d399">
    <span class="section-kicker">The original math</span>
    <h2 class="section-title">Damien's model, kept light</h2>
    <div class="section-duo">
      <div class="prose duo-copy">
        <p>
          The idea arrived with a full model: shoulder, hand, and prop tip on
          nested circles, two frequencies for a pattern's shape, two radii for
          its scale, and a final fraction to take part of a cycle instead of
          the whole. Every elementary pattern gets a short name like
          <code>θ1&nbsp;θ2&nbsp;;&nbsp;ρ1&nbsp;ρ2&nbsp;;&nbsp;d</code>. The
          drawings below are redrawn from his exact parameters, and they
          explain the system better than the algebra ever could. We will leave
          it at that.
        </p>
        <p class="cap-credit">
          Original model diagram: Damien (Zaltymbunk),
          <a href={THREAD_URL}>Home of Poi, 2009</a>, preserved from
          imageshotel.org.
        </p>
      </div>
      <figure class="cap-figure duo-demo">
        <img
          src="/caps/original/model.jpg"
          alt="Damien's original 2009 diagram: shoulder O, hand M, prop extremity E on nested circles with theta and rho annotations"
          width="427"
          height="305"
          loading="lazy"
        />
        <figcaption>
          The original 2009 model diagram. O is the shoulder, M the hand
          ("Main" in French), E the prop tip.
        </figcaption>
      </figure>
    </div>

    <div class="cap-pattern-grid">
      {#each PATTERNS as p (p.file)}
        <figure class="cap-pattern">
          <img
            src="/caps/{p.file}"
            alt="{p.kind} traced as an animated curve, notation {p.label}"
            width="220"
            height="220"
            loading="lazy"
          />
          <figcaption>
            <code>{p.label}</code>
            <span>{p.kind}</span>
          </figcaption>
        </figure>
      {/each}
    </div>
    <p class="cap-credit cap-grid-credit">
      Curves redrawn from the parameters in the origin thread. The animated
      originals Damien linked were hosted by
      <a href="https://www.mathcurve.com">mathcurve.com</a> (Robert Ferréol's
      encyclopedia of remarkable mathematical forms).
    </p>
  </section>

  <!-- THE PEOPLE -->
  <section class="editorial-section" style="--accent: #38bdf8">
    <span class="section-kicker">The people</span>
    <h2 class="section-title">Credit where it started</h2>
    <div class="cap-people">
      <article class="cap-person">
        <h3>Damien <span class="cap-person-alias">French_Saltimbanque · Zaltymbunk</span></h3>
        <p>
          Coined the term and built the mathematics. Forum title: Trochoïd
          Master. From Angers, France. His posts define the elementary
          pattern, the notation, rosettes, cycloids, the wrap table, and the
          feasibility rules, then assemble them into CAPs.
        </p>
        <p class="cap-person-links">
          <a class="resource-chip" href={THREAD_URL}>The origin thread</a>
          <a class="resource-chip" href="https://drexfactor.com/reference/math_caps">The Math of CAPs</a>
        </p>
      </article>
      <article class="cap-person">
        <h3>Alien Jon</h3>
        <p>
          Took the term from Damien and gave it its philosophy: CAPs as a way
          of thinking about movement, not a move. Part of the Burning Man 2007
          group where the ideas germinated. Co-created Encyclo-poi-dia Vol. 2,
          which carried a full CAP chapter.
        </p>
      </article>
      <article class="cap-person">
        <h3>Nick Woolsey <span class="cap-person-alias">PlayPoi</span></h3>
        <p>
          Brought CAPs to learners. His 2016 tutorial "Learning CAPs (Capped
          Antispin Patterns)" is where many spinners met the concept, and the
          source of that expansion of the acronym.
        </p>
        <p class="cap-person-links">
          <a class="resource-chip" href="https://playpoi.com/learn/learning-caps-capped-antispin-patterns/">PlayPoi tutorial</a>
        </p>
      </article>
      <article class="cap-person">
        <h3>Charlie Cushing</h3>
        <p>
          Extended the theory: the 8-step CAP and 9-Square Theory. DrexFactor's
          double staff recipe credits him directly: "The idea comes to us from
          Charlie's 9-square theory."
        </p>
        <p class="cap-person-links">
          <a class="resource-chip" href="https://www.drexfactor.com/weirdscience/2016/09/27/tutorial_double_staff_8_step_cap_recipe">8-Step CAP recipe</a>
        </p>
      </article>
      <article class="cap-person">
        <h3>Drex <span class="cap-person-alias">DrexFactor</span></h3>
        <p>
          Documented the family for over a decade: the Tech Poi Blog series,
          the 2012 C-CAPs tutorial, the 8-step recipe, and the hosting of
          Damien's Math of CAPs as a permanent reference.
        </p>
        <p class="cap-person-links">
          <a class="resource-chip" href="https://drexfactor.com/index.php?q=weirdscience%2F2012%2F08%2F21%2Fbasic_poi_dancing_tutorial_c_caps">C-CAPs tutorial</a>
        </p>
      </article>
    </div>
    <p class="prose cap-people-footnote">
      Also in the room at Burning Man 2007: Noel Yee and Jordan Campbell, whose
      Transition Theory work describes the mechanism that joins pattern
      fragments, and Greg and Zan of the OMCC crew.
    </p>
  </section>

  <!-- MODERN MEDIA -->
  {#if MODERN_MEDIA.length > 0}
    <section class="editorial-section" style="--accent: #a78bfa">
      <span class="section-kicker">Since then</span>
      <h2 class="section-title">CAPs on video, 2009 to now</h2>
      <div class="cap-media-grid">
        {#each MODERN_MEDIA as m (m.id)}
          <figure class="cap-media">
            <iframe
              src="https://www.youtube-nocookie.com/embed/{m.id}"
              title="{m.title} — {m.creator}"
              loading="lazy"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
            <figcaption>
              <strong>{m.title}</strong>
              <span>{m.creator} · {m.year}</span>
              <span class="cap-media-note">{m.note}</span>
            </figcaption>
          </figure>
        {/each}
      </div>
      <p class="prose cap-media-footnote">
        Charlie's series runs about ten parts:
        <a href="https://www.youtube.com/playlist?list=PLDE05D5E593C54AED">the full 9-Square Theory playlist</a>.
        Alien Jon's original pattern playlist, linked from the origin thread,
        no longer resolves. Link rot is part of why this page exists.
      </p>
    </section>
  {/if}

  <!-- SOURCES -->
  <section class="editorial-section" style="--accent: #94a3b8">
    <span class="section-kicker">Sources</span>
    <h2 class="section-title">Read the originals</h2>
    <ul class="bullet-list">
      <li>
        <a href={THREAD_URL}>"What are CAP's?"</a> — Home of Poi forums, ca.
        2009. The origin discussion: the coinage attribution, Damien's full
        framework posts, and the community debate.
      </li>
      <li>
        <a href="https://drexfactor.com/reference/math_caps">The Math of CAPs</a>
        — Damien's framework, preserved as a DrexFactor reference.
      </li>
      <li>
        <a href="https://drexfactor.com/index.php?q=weirdscience%2F2012%2F08%2F21%2Fbasic_poi_dancing_tutorial_c_caps">Basic Poi Dancing Tutorial: C-CAPs</a>
        — DrexFactor, 2012. The narrowed usage, documented.
      </li>
      <li>
        <a href="https://playpoi.com/learn/learning-caps-capped-antispin-patterns/">Learning CAPs (Capped Antispin Patterns)</a>
        — Nick Woolsey, PlayPoi, 2016.
      </li>
      <li>
        <a href="https://www.drexfactor.com/weirdscience/2016/09/27/tutorial_double_staff_8_step_cap_recipe">Double Staff 8-Step CAP Recipe</a>
        — DrexFactor, 2016, crediting Charlie's 9-Square Theory.
      </li>
      <li>
        Encyclo-poi-dia Vol. 2 — Alien Jon and Zan Moore. Print-era CAP
        chapter, referenced in the origin thread.
      </li>
    </ul>
  </section>

  <!-- CTA -->
  <section class="editorial-section">
    <div class="cta-card">
      <div class="prose">
        <p>
          TKA's contribution to the same craving is the LOOP algebra: six
          transformations, composable and speakable.
        </p>
      </div>
      <a class="cta-button" href="/notation/loops">Explore the LOOP algebra</a>
    </div>
  </section>
</div>

<style>
  code {
    font-variant-numeric: tabular-nums;
    background: color-mix(in srgb, currentColor 8%, transparent);
    border-radius: 4px;
    padding: 0.05em 0.35em;
    white-space: nowrap;
  }

  /* Hero: the live stage takes the larger column; copy sits beside it. */
  .cap-hero {
    display: grid;
    grid-template-columns: minmax(320px, 640px) 1fr;
    gap: clamp(1.5rem, 4vw, 3.5rem);
    align-items: center;
  }
  .cap-hero-stage {
    width: 100%;
  }
  .cap-credit {
    font-size: 0.85rem;
    opacity: 0.75;
  }

  .cap-figure {
    margin: 0;
  }
  .cap-figure img {
    width: 100%;
    height: auto;
    border-radius: 8px;
  }
  .cap-figure figcaption,
  .cap-pattern figcaption,
  .cap-lens figcaption {
    font-size: 0.85rem;
    opacity: 0.8;
    margin-top: 0.5rem;
    line-height: 1.45;
  }

  .cap-pattern-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    gap: 1.25rem;
    margin-top: 2rem;
  }
  .cap-pattern {
    margin: 0;
    text-align: center;
  }
  .cap-pattern img {
    width: 100%;
    height: auto;
    aspect-ratio: 1;
  }
  .cap-pattern figcaption {
    display: flex;
    flex-direction: column;
    gap: 0.15rem;
  }
  .cap-grid-credit {
    margin-top: 1.25rem;
  }

  .cap-people {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
  }
  .cap-person h3 {
    margin: 0 0 0.5rem;
    font-size: 1.05rem;
  }
  .cap-person-alias {
    display: block;
    font-size: 0.8rem;
    font-weight: 400;
    opacity: 0.65;
    margin-top: 0.15rem;
  }
  .cap-person p {
    margin: 0 0 0.75rem;
    font-size: 0.95rem;
    line-height: 1.55;
  }
  .cap-person-links {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
  }
  .cap-people-footnote {
    margin-top: 1.5rem;
  }

  .cap-lens-duo {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: 2rem;
    margin-top: 1.5rem;
  }
  .cap-lens {
    margin: 0;
  }
  .cap-lens img {
    width: 100%;
    height: auto;
    border-radius: 8px;
  }

  .cap-media-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
    gap: 1.5rem;
  }
  .cap-media {
    margin: 0;
  }
  .cap-media iframe {
    width: 100%;
    aspect-ratio: 16 / 9;
    border: 0;
    border-radius: 8px;
  }
  .cap-media figcaption {
    display: flex;
    flex-direction: column;
    gap: 0.15rem;
    margin-top: 0.5rem;
    font-size: 0.85rem;
  }
  .cap-media-note {
    opacity: 0.7;
  }

  @media (max-width: 767px) {
    .cap-hero {
      grid-template-columns: 1fr;
    }
  }
</style>
