import type { EffectsPreset } from "../effects-preset";

export const BUILT_IN_BUBBLES_PRESETS: EffectsPreset[] = [
  {
    id: "bubbles-classic",
    name: "Classic",
    description: "Default balanced soap bubbles.",
    effectType: "bubbles",
    builtIn: true,
    previewColors: ["#c8e0ff", "#ffffff"],
    patch: {
      bubbles: {
        palette: "soap",
        ambientEmission: 0.3,
        motionEmission: 0.5,
        intensity: 0.6,
        sizeJitter: 0.4,
        buoyancy: 0.5,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "bubbles-fizz",
    name: "Fizz",
    description: "Constant champagne effervescence, small uniform bubbles.",
    effectType: "bubbles",
    builtIn: true,
    previewColors: ["#f4e8c8", "#fff8e0"],
    patch: {
      bubbles: {
        palette: "champagne",
        ambientEmission: 0.6,
        motionEmission: 0.5,
        intensity: 0.5,
        sizeJitter: 0.2,
        buoyancy: 0.9,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "bubbles-dream",
    name: "Dream",
    description: "Large slow swells with wide size range.",
    effectType: "bubbles",
    builtIn: true,
    previewColors: ["#c8e0ff", "#e8f4ff"],
    patch: {
      bubbles: {
        palette: "soap",
        ambientEmission: 0.5,
        motionEmission: 0.2,
        intensity: 0.9,
        sizeJitter: 0.7,
        buoyancy: 0.3,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "bubbles-iridescent",
    name: "Iridescent",
    description: "Oil-slick rainbow rim that shifts over lifetime.",
    effectType: "bubbles",
    builtIn: true,
    previewColors: ["#ff80d0", "#80d0ff"],
    patch: {
      bubbles: {
        palette: "oil",
        ambientEmission: 0.4,
        motionEmission: 0.4,
        intensity: 0.7,
        sizeJitter: 0.5,
        buoyancy: 0.5,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "bubbles-acid",
    name: "Acid Fizz",
    description: "Corrosive fizz, pairs with acid water.",
    effectType: "bubbles",
    builtIn: true,
    previewColors: ["#b8ff6f", "#98e860"],
    patch: {
      bubbles: {
        palette: "acid",
        ambientEmission: 0.5,
        motionEmission: 0.6,
        intensity: 0.6,
        sizeJitter: 0.3,
        buoyancy: 0.8,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "bubbles-spirit",
    name: "Spirit",
    description: "Ghostly halos drifting upward.",
    effectType: "bubbles",
    builtIn: true,
    previewColors: ["#c0fff4", "#a0f8e0"],
    patch: {
      bubbles: {
        palette: "spirit",
        ambientEmission: 0.6,
        motionEmission: 0.3,
        intensity: 0.4,
        sizeJitter: 0.6,
        buoyancy: 0.4,
        trackingMode: "both_ends",
      },
    },
  },
];
