import type { EffectsPreset } from "../effects-preset";

export const BUILT_IN_PETALS_PRESETS: EffectsPreset[] = [
  {
    id: "petals-classic",
    name: "Classic",
    description: "Balanced cherry blossom - soft pink sway.",
    effectType: "petals",
    builtIn: true,
    previewColors: ["#ffd0e0", "#ffc0d8"],
    patch: {
      petals: {
        palette: "blossom",
        ambientEmission: 0.5,
        motionEmission: 0.4,
        intensity: 0.6,
        swayAmplitude: 0.6,
        fallSpeed: 0.4,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "petals-storm",
    name: "Storm",
    description: "Chaotic autumn fall - wide sway, heavy drop.",
    effectType: "petals",
    builtIn: true,
    previewColors: ["#d84820", "#c88020"],
    patch: {
      petals: {
        palette: "autumn",
        ambientEmission: 0.8,
        motionEmission: 0.6,
        intensity: 0.7,
        swayAmplitude: 0.8,
        fallSpeed: 0.7,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "petals-jungle",
    name: "Jungle Drift",
    description: "Heavy green leaves with deliberate drift.",
    effectType: "petals",
    builtIn: true,
    previewColors: ["#408840", "#60a050"],
    patch: {
      petals: {
        palette: "jungle",
        ambientEmission: 0.4,
        motionEmission: 0.3,
        intensity: 0.7,
        swayAmplitude: 0.5,
        fallSpeed: 0.5,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "petals-ember",
    name: "Ember Ash",
    description: "Burnt leaves with flickering ember rims.",
    effectType: "petals",
    builtIn: true,
    previewColors: ["#606060", "#ff6020"],
    patch: {
      petals: {
        palette: "ash",
        ambientEmission: 0.3,
        motionEmission: 0.7,
        intensity: 0.5,
        swayAmplitude: 0.7,
        fallSpeed: 0.5,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "petals-gilded",
    name: "Gilded",
    description: "Rare slow metallic gold leaves.",
    effectType: "petals",
    builtIn: true,
    previewColors: ["#ffd060", "#c89020"],
    patch: {
      petals: {
        palette: "gold",
        ambientEmission: 0.2,
        motionEmission: 0.4,
        intensity: 0.9,
        swayAmplitude: 0.4,
        fallSpeed: 0.2,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "petals-tornado",
    name: "Tornado",
    description: "Extreme sway - spin chaos of autumn leaves.",
    effectType: "petals",
    builtIn: true,
    previewColors: ["#c86828", "#d84820"],
    patch: {
      petals: {
        palette: "autumn",
        ambientEmission: 0.4,
        motionEmission: 1.0,
        intensity: 0.6,
        swayAmplitude: 1.0,
        fallSpeed: 0.8,
        trackingMode: "both_ends",
      },
    },
  },
];
