import type { EffectsPreset } from "../effects-preset";

export const BUILT_IN_FROST_PRESETS: EffectsPreset[] = [
  {
    id: "frost-classic",
    name: "Classic",
    description: "Balanced snowflakes + cold aura - blue-white ice.",
    effectType: "frost",
    builtIn: true,
    previewColors: ["#a0d8ff", "#e0f4ff"],
    patch: {
      frost: {
        palette: "glacial",
        ambientEmission: 0.4,
        motionEmission: 0.5,
        intensity: 0.6,
        crystallinity: 0.7,
        spreadRate: 0.5,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "frost-breath",
    name: "Breath",
    description: "Cold haze only, no snowflakes - visible exhale.",
    effectType: "frost",
    builtIn: true,
    previewColors: ["#d0e8f0", "#f0f8ff"],
    patch: {
      frost: {
        palette: "breath",
        ambientEmission: 0.7,
        motionEmission: 0.3,
        intensity: 0.4,
        crystallinity: 0.0,
        spreadRate: 0.0,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "frost-flash-freeze",
    name: "Flash Freeze",
    description: "Fast snowflake spread on motion - sudden ice coating.",
    effectType: "frost",
    builtIn: true,
    previewColors: ["#a0d8ff", "#ffffff"],
    patch: {
      frost: {
        palette: "glacial",
        ambientEmission: 0.2,
        motionEmission: 0.9,
        intensity: 0.8,
        crystallinity: 1.0,
        spreadRate: 1.0,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "frost-black-ice",
    name: "Black Ice",
    description: "Subtle dark frost - nearly invisible menace.",
    effectType: "frost",
    builtIn: true,
    previewColors: ["#202830", "#405060"],
    patch: {
      frost: {
        palette: "black_ice",
        ambientEmission: 0.3,
        motionEmission: 0.6,
        intensity: 0.5,
        crystallinity: 0.6,
        spreadRate: 0.6,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "frost-aurora",
    name: "Aurora",
    description: "Glowing iridescent snowflakes - northern lights on ice.",
    effectType: "frost",
    builtIn: true,
    previewColors: ["#60ff80", "#ff60c0"],
    patch: {
      frost: {
        palette: "aurora",
        ambientEmission: 0.5,
        motionEmission: 0.4,
        intensity: 0.7,
        crystallinity: 0.8,
        spreadRate: 0.5,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "frost-cursed",
    name: "Cursed",
    description: "Dark purple snowflakes - corrupted ice.",
    effectType: "frost",
    builtIn: true,
    previewColors: ["#4020a0", "#8060d0"],
    patch: {
      frost: {
        palette: "cursed",
        ambientEmission: 0.3,
        motionEmission: 0.5,
        intensity: 0.7,
        crystallinity: 0.9,
        spreadRate: 0.4,
        trackingMode: "both_ends",
      },
    },
  },
];
