import type { EffectsPreset } from "../effects-preset";

export const BUILT_IN_SILK_PRESETS: EffectsPreset[] = [
  {
    id: "silk-classic",
    name: "Classic",
    description: "Balanced satin ribbon - smooth flow.",
    effectType: "silk",
    builtIn: true,
    previewColors: ["#c0c0d0", "#ffffff"],
    patch: {
      silk: {
        palette: "satin",
        intensity: 0.7,
        width: 0.5,
        duration: 0.5,
        flutter: 0.3,
        tautness: 0.5,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "silk-streamer",
    name: "Streamer",
    description: "Long iridescent ribbon - maximum flutter.",
    effectType: "silk",
    builtIn: true,
    previewColors: ["#c080ff", "#80d0ff"],
    patch: {
      silk: {
        palette: "ethereal",
        intensity: 0.6,
        width: 0.7,
        duration: 0.8,
        flutter: 0.7,
        tautness: 0.3,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "silk-whip",
    name: "Whip",
    description: "Short dark streak - snaps taut on fast moves.",
    effectType: "silk",
    builtIn: true,
    previewColors: ["#101020", "#404060"],
    patch: {
      silk: {
        palette: "shadow",
        intensity: 0.8,
        width: 0.4,
        duration: 0.3,
        flutter: 0.1,
        tautness: 0.9,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "silk-royal",
    name: "Royal",
    description: "Wide gold ribbon - regal, ceremonial.",
    effectType: "silk",
    builtIn: true,
    previewColors: ["#a07000", "#ffd700"],
    patch: {
      silk: {
        palette: "gold_leaf",
        intensity: 0.8,
        width: 0.7,
        duration: 0.6,
        flutter: 0.2,
        tautness: 0.4,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "silk-inferno",
    name: "Inferno",
    description: "Glowing ember ribbon - additive fire trail.",
    effectType: "silk",
    builtIn: true,
    previewColors: ["#ff6000", "#ffcc00"],
    patch: {
      silk: {
        palette: "ember",
        intensity: 0.9,
        width: 0.5,
        duration: 0.5,
        flutter: 0.4,
        tautness: 0.7,
        trackingMode: "both_ends",
      },
    },
  },
  {
    id: "silk-phantom",
    name: "Phantom",
    description: "Faint dark ribbon - long ghostly trail.",
    effectType: "silk",
    builtIn: true,
    previewColors: ["#101020", "#404060"],
    patch: {
      silk: {
        palette: "shadow",
        intensity: 0.3,
        width: 0.6,
        duration: 0.9,
        flutter: 0.5,
        tautness: 0.2,
        trackingMode: "both_ends",
      },
    },
  },
];
