import type { SmokePalette } from "$lib/shared/effects/domain/smoke-palettes";
import type { SmokeVolumeProfile3D } from "$lib/shared/effects/translators/webgl3d-types";

const PROFILES: Record<SmokePalette["id"], Readonly<SmokeVolumeProfile3D>> = {
  incense: {
    injectionRadiusWorld: 0.065,
    density: 1.08,
    dissipation: 0.18,
    temperature: 0.42,
    vorticity: 0.44,
    lateralSpread: 0.035,
    expansion: 0.018,
    extinction: 3.4,
    scattering: 0.62,
    detailWarp: 0.42,
    hueShift: 0,
  },
  fog: {
    injectionRadiusWorld: 0.22,
    density: 0.92,
    dissipation: 0.12,
    temperature: 0.08,
    vorticity: 0.22,
    lateralSpread: 0.34,
    expansion: 0.2,
    extinction: 3.2,
    scattering: 0.78,
    detailWarp: 0.3,
    hueShift: 0,
  },
  genie: {
    injectionRadiusWorld: 0.1,
    density: 1.42,
    dissipation: 0.78,
    temperature: 1.05,
    vorticity: 1.25,
    lateralSpread: 0.16,
    expansion: 0.28,
    extinction: 3.6,
    scattering: 0.88,
    detailWarp: 0.95,
    hueShift: 1,
  },
  cursed: {
    injectionRadiusWorld: 0.11,
    density: 1.58,
    dissipation: 0.24,
    temperature: 0.22,
    vorticity: 0.76,
    lateralSpread: 0.11,
    expansion: 0.09,
    extinction: 5.6,
    scattering: 0.24,
    detailWarp: 0.72,
    hueShift: 0,
  },
  spirit: {
    injectionRadiusWorld: 0.095,
    density: 0.86,
    dissipation: 0.16,
    temperature: 0.32,
    vorticity: 0.4,
    lateralSpread: 0.12,
    expansion: 0.08,
    extinction: 2.2,
    scattering: 0.94,
    detailWarp: 0.52,
    hueShift: 0,
  },
  campfire: {
    injectionRadiusWorld: 0.12,
    density: 1.35,
    dissipation: 0.16,
    temperature: 0.95,
    vorticity: 0.62,
    lateralSpread: 0.14,
    expansion: 0.18,
    extinction: 4.6,
    scattering: 0.55,
    detailWarp: 0.68,
    hueShift: 0,
  },
  custom: {
    injectionRadiusWorld: 0.19,
    density: 1,
    dissipation: 0.1,
    temperature: 0.35,
    vorticity: 0.5,
    lateralSpread: 0.25,
    expansion: 0.22,
    extinction: 3.2,
    scattering: 0.7,
    detailWarp: 0.55,
    hueShift: 0,
  },
};

export function resolveSmokeVolumeProfile3D(
  palette: SmokePalette
): Readonly<SmokeVolumeProfile3D> {
  return PROFILES[palette.id];
}
