/**
 * Per-visit demo sequence — every visitor gets a freshly generated rotated
 * LOOP instead of a canonical baked example, and the hero's dice button
 * rerolls it in place. Nothing on the page treats any particular sequence
 * as special.
 *
 * This module is the routing seam. The roll itself lives in
 * per-visit-demo-core.ts and normally runs in a Worker
 * (per-visit-demo.worker.ts): the attract act regenerates forever, and the
 * first roll of a page session was measured at 572 ms wall clock containing a
 * 135 ms blocking task on /composer. Off-thread, that cost is zero frames.
 * When no Worker exists — SSR, jsdom, a caller supplying its own `random`
 * (functions cannot be structured-cloned) — the same core runs in-process,
 * chunked so no single task exceeds one build.
 *
 * The baked fixture ($lib/shared/landing/data/demo-sequence.json) is itself
 * one of these draws, generated by this exact preset and committed. It remains
 * only as the fallback when generation itself fails, as HomeHero's
 * pre-hydration frame, and as the static sequence for the notation prop pages.
 */
import type { SequenceData } from "$lib/shared/foundation/domain/models/sequence-data";
import demoJson from "$lib/shared/landing/data/demo-sequence.json";
import {
  rollPerVisitDemo,
  type PerVisitDemoOptions,
} from "$lib/shared/landing/data/per-visit-demo-core";
import { rollInWorker } from "$lib/shared/landing/data/per-visit-demo-worker-client";

export const FALLBACK_DEMO = demoJson as unknown as SequenceData;

export async function generatePerVisitDemo(
  options?: PerVisitDemoOptions
): Promise<SequenceData> {
  // An injected `random` is a function, which the structured clone algorithm
  // cannot carry. Those callers (deterministic level-selection tests) keep the
  // in-process path, where the injected source still governs the draw.
  if (!options?.random) {
    const viaWorker = await rollInWorker({
      ...(options?.propType ? { propType: options.propType } : {}),
      ...(options?.startPosition
        ? { startPosition: options.startPosition }
        : {}),
    });
    if (viaWorker.status === "ok") return viaWorker.sequence;
    // "failed" means the roll genuinely produced nothing — the same outcome the
    // in-process path reports, so take the fallback rather than paying twice.
    if (viaWorker.status === "failed") return FALLBACK_DEMO;
  }

  try {
    return (await rollPerVisitDemo(options)) ?? FALLBACK_DEMO;
  } catch (e) {
    console.error(
      "[per-visit-demo] generation failed, using baked fallback:",
      e
    );
    return FALLBACK_DEMO;
  }
}
