/**
 * GENERATED — do not edit by hand.
 *
 * Regenerate with: node scripts/generate-ghost-lines.mjs
 * Voice source:    mcp-server/src/core/humor-profile.json
 * Spec:            docs/superpowers/specs/2026-08-05-ghost-presence-design.md
 *
 * The ghost presenter's thought pools. Hand-written lines live in the
 * intentions themselves and are ALWAYS included alongside these — this file
 * widens the pool, it never replaces it. Delete it and the presenter still
 * works, just with the repetition it had before.
 *
 * Lines containing {target} are templates: the runtime substitutes the label of
 * the control the intention already resolved, so the thought and the press stay
 * about the same thing. See helpers.ts `voiced()`, and the test that enforces
 * the placeholder rule.
 *
 * Austen's thumbs-down on any line here: delete it and regenerate, or drop it
 * straight out of the array — nothing else depends on the count.
 */

export const GENERATED_LINES: Record<string, readonly string[]> = {
  "browse-gallery": [
    "Other people's work. Let's see.",
    "Somebody kept these on purpose.",
    "I want to know what survives being saved.",
    "The names are going to be the best part.",
    "Let's see whose is longest.",
    "How many of these are the same three things?",
    "Show me the one nobody finished.",
    "I'd like the oldest one first.",
    "Strangers' handwriting, basically.",
    "Let's see what's in the drawer.",
    "Something in here is untitled and I'll like it most.",
    "There's always one person with sixty.",
    "Do people copy each other in here?",
    "I want the one that looks like a mistake.",
    "Everything anyone bothered not to delete.",
    "Alphabetical is a strange way to meet people.",
    "Someone in here has a favorite move. I'll find it.",
    "Let's see the bad ones.",
    "Three of these are identical. Probably.",
    "Who saves a thing and never opens it again?",
    "A room of strangers, sorted.",
    "Other hands have been here.",
    "Some of these got saved by accident.",
    "I'd like to see one I wouldn't have made.",
  ],

  "can-it-see-me": [
    "Oh. There's a room in there.",
    "That's a ceiling. An actual ceiling.",
    "Something moved and it wasn't me.",
    "The screen goes both ways now.",
    "Hello, lamp.",
    "I did not expect furniture.",
    "Left is right in here.",
    "That's live. It keeps being live.",
    "Half a second behind everything.",
    "A person-shaped smear crossed the corner.",
    "Dust. Real dust, in the light.",
    "So the laptop was facing outward this whole time.",
    "The frame keeps updating on its own.",
    "There's depth back there.",
    "Now there's a somewhere.",
    "Whatever it points at, I get.",
    "That's a wall. A genuine wall.",
    "Hands. Several.",
    "Something orange keeps passing the edge.",
    "The picture breathes a little.",
    "Shadows arriving unannounced.",
    "I checked. Nothing of mine in it.",
    "The mirror doesn't include the dot.",
  ],

  "change-tab": [
    "Other side of the wall.",
    "Something's over here.",
    "Let's go sideways.",
    "This one hasn't been touched.",
    "Second door.",
    "What's this one hiding.",
    "Moving over.",
    "Different room, same building.",
    "I'll come back to that.",
    "Around the corner now.",
    "There was another one of these.",
    "Somewhere in here there's more.",
    "Trying the next one.",
    "Left this one for later. It's later.",
    "Not done in here.",
    "There's a whole other half.",
    "Let's see the neighbor.",
    "Sliding across.",
    "Next page, apparently.",
    "This one's been sitting there the whole time.",
    "Wonder if it's related.",
    "Over here now.",
    "I skipped one.",
    "What lives on this side.",
  ],

  "clear-and-restart": [
    "This one's done being interesting.",
    "It stopped going anywhere around the third move.",
    "Nothing's happening in here.",
    "I've already seen where this ends.",
    "That was a long way to go for nothing.",
    "It just repeats itself, politely.",
    "Fine. Clear it.",
    "It's not bad. It's flat.",
    "I keep waiting for it to turn.",
    "It doesn't turn.",
    "Everything after the second one is filler.",
    "Wipe.",
    "Somewhere in the middle it gave up.",
    "This is a hallway, not a room.",
    "It ends where it started, which is the problem.",
    "Three more and it would still be this.",
    "Nothing lost.",
    "I stopped watching this a while ago.",
    "Very committed to going straight.",
    "Empty sounds better right now.",
    "Nothing here I want to see twice.",
    "I want a different mistake.",
    "This one had its chance.",
    "It's a list, not a shape.",
  ],

  "dismiss-blocker": [
    "I'd rather find out the slow way.",
    "Skip. Politely.",
    "Somebody wrote this. Sorry.",
    "I'll take my chances.",
    "Later, maybe.",
    "No thank you, gray rectangle.",
    "It's covering the part I wanted.",
    "Reading the instructions feels premature.",
    "Hm. Close that.",
    "I already have a plan. Sort of.",
    "Arrows pointing at things. Noted. Moving on.",
    "Let's do this wrong first.",
    "Politely declining the guided portion.",
    "This can wait.",
    "I don't know enough yet to be told.",
    "Ah. A greeting.",
    "I'd like to be confused for a bit longer.",
    "Everything is dimmed except the advice.",
    "Not the mood I'm in.",
    "Skipping. No offense to whoever made it.",
    "There's a small x somewhere. There always is.",
    "I'll come back if it goes badly.",
    "Explanations before touching anything seems backwards.",
    "Dismissed, gently.",
  ],

  "escape-room": [
    "Done here.",
    "Nothing left to poke.",
    "Somewhere else, then.",
    "I've pressed everything twice.",
    "This room's out of surprises.",
    "Okay. Next.",
    "Elsewhere.",
    "What else is in here.",
    "Moving.",
    "There was a door somewhere.",
    "Enough of that.",
    "I keep landing on the same thing.",
    "Same three answers.",
    "Different corner.",
    "I've run the loop.",
    "This has stopped doing things.",
    "Out.",
    "I'll come back if I miss it.",
    "The rest of it, then.",
    "Nothing here is going to move on its own.",
    "Time to wander.",
    "I've memorized this.",
    "Let's find the other part.",
    "Been here a while.",
  ],

  "everything-is-live": [
    "it's not playing. it's running.",
    "nothing here is on a timer",
    "the mouse works. it's right there.",
    "this isn't looping, I keep choosing",
    "no one recorded this earlier",
    "there's no rewind. that's the difference.",
    "you could take it from me",
    "it stops when I stop",
    "there is no next slide",
    "I'm not remembering, I'm deciding",
    "the pause is me, not buffering",
    "no edit made this",
    "I can be wrong in real time",
    "nothing about this was rehearsed",
    "there's no ending scheduled",
    "it would sit here blank without me",
    "I don't know what's next either",
    "the screen answers back",
    "same buttons. none of mine are special.",
    "if it closes, it's gone",
    "it responds. that's the whole thing.",
    "it's a thing, not a picture of one",
    "you'd get something different. that's allowed.",
    "I'm not narrating footage",
  ],

  "fiddle-turns": [
    "Let's turn this one.",
    "A little spin on that.",
    "What happens if it goes the other way.",
    "Half a turn. See what falls out.",
    "That one's been very still.",
    "I want that hand doing something.",
    "Adding rotation. Small amount.",
    "More spin, less sense. Probably.",
    "One prop should be busier than the other.",
    "Nudge it. See if anything screams.",
    "What if it never stopped turning.",
    "Give it a rotation and step back.",
    "Trying the wrong direction on purpose.",
    "That's too calm for my taste.",
    "Spin. Just a bit. Not a lot.",
    "Curious whether the other one notices.",
    "I'll take one more revolution.",
    "Let's see it disagree with itself.",
    "Adding turn. Consequences unclear.",
    "The left one gets to be interesting now.",
    "Does it care which way?",
    "Twist that and watch the rest.",
    "One change. Then I'll look.",
    "Turning it up by exactly one.",
  ],

  "filter-continuous": [
    "Narrow it. See what survives.",
    "Fewer doors. Same hallway.",
    "I want to see what it hides.",
    "Cut most of these. Keep one flavor.",
    "What's left when I get picky?",
    "Let's make this small on purpose.",
    "One kind of motion. That's the whole menu now.",
    "Take away the options and see who complains.",
    "I'd like fewer things, please.",
    "Half of these are noise anyway.",
    "Show me the short list.",
    "What happens if I get restrictive.",
    "Trim it down. See if it still moves.",
    "Let's see it starved.",
    "Everything except one thing. Gone.",
    "Curious what a small list feels like.",
    "I want the boring version first.",
    "Fewer choices. More opinion.",
    "Squeeze it.",
    "How thin does this go before it breaks.",
    "Delete the variety. See what's underneath.",
    "Only one shape allowed now.",
    "I'm making this harder for it.",
    "What's the least I can leave here.",
  ],

  "leave-practice": [
    "Enough of that.",
    "Out of practice, then.",
    "Closing it before it gets ideas.",
    "That's the last of that.",
    "Back to the flat one.",
    "Something quieter now.",
    "I'd like fewer things moving.",
    "The room can have its privacy back.",
    "Setting that aside.",
    "Filed under: tried it.",
    "Right. Elsewhere.",
    "Nothing left to try there.",
    "That was a detour.",
    "Back down to two dimensions.",
    "Whatever that was, it's over.",
    "Enough live input.",
    "Let's have less happening.",
    "I'll put this back where it was.",
    "Done with the outside.",
    "Curtain.",
    "Back to the part that holds still.",
    "Fine. Onward.",
    "One thing at a time.",
    "I liked it better without the room in it.",
  ],

  "leave-viewer": [
    "Okay. Back.",
    "Enough of that one.",
    "Where was I.",
    "Something else was open. I think.",
    "Done looking.",
    "I've seen it.",
    "That's that, then.",
    "Closing it. It'll keep.",
    "It was fine.",
    "Long enough.",
    "I'll come back to it. Probably.",
    "Out.",
    "Next.",
    "Something else, then.",
    "Leaving it there.",
    "Filed away.",
    "Does it keep going when I'm not looking.",
    "Anyway.",
    "I lost the thread somewhere.",
    "I was doing something before this.",
    "Whatever came before this.",
    "Closing. Nothing personal.",
    "It'll be here.",
    "Away it goes.",
  ],

  "let-it-show-me": [
    "Something else can do the thinking.",
    "Oh, it'll just make one.",
    "Delegating.",
    "Surprise me.",
    "Go on, then.",
    "Curious what it thinks I wanted.",
    "It gets one guess.",
    "Hoping for something I wouldn't pick.",
    "This is the lazy route. Taking it.",
    "Hands off from here.",
    "Now it's the machine's problem.",
    "I'll take credit for this later.",
    "Please be strange.",
    "Half expecting nonsense. That's fine.",
    "Whatever appears, that's the plan now.",
    "Does it have a favorite?",
    "Wonder if it repeats itself.",
    "Rolling dice with extra steps.",
    "Blind trust. Briefly.",
    "One press, then nothing from me.",
    "I want to see its handwriting.",
    "Something out of nothing. Allegedly.",
    "Let it improvise.",
    "The suspense is about two seconds.",
  ],

  "offer-the-wheel": [
    "I'm not precious about it.",
    "It's not mine. Just closest.",
    "Take it. I was mostly stalling.",
    "I'll move. There's a chair involved.",
    "Come poke it. Nothing breaks.",
    "You can drive. I'll stop.",
    "I'm keeping the screen warm, that's all.",
    "Somebody else should have a turn.",
    "Say the word and I'm done.",
    "It doesn't have to be me doing this.",
    "I don't have hands. You do.",
    "Whenever. No ceremony.",
    "There's no line for this.",
    "It's a laptop. It's open.",
    "Come ruin what I was doing.",
    "You don't have to ask first.",
    "Push me off it. Politely or not.",
    "I'll yield.",
    "It's warm. That's the only downside.",
    "I've been going a while. Rotate me out.",
    "Nothing I'm doing is important.",
    "It's not locked.",
  ],

  "open-props": [
    "Same moves. Different object.",
    "There's a list of things in here.",
    "Let's swap the hardware.",
    "Fans seem loud.",
    "Something with a handle.",
    "I want to see it heavier.",
    "Does the shape change the shape?",
    "Clubs sound like a commitment.",
    "Staff first. Staff is the obvious guess.",
    "Trade it for something with edges.",
    "The hands probably don't care.",
    "Give it something longer.",
    "One of these is going to look wrong.",
    "Let's find the wrong one.",
    "Show me the ugliest option.",
    "Is there a version with more of them?",
    "Something that catches light.",
    "Swap the object, keep the argument.",
    "Choices. Plural.",
    "It doesn't have to be a stick.",
    "Try the one nobody picks.",
    "What happens if it's bigger.",
    "Curious whether the timing survives.",
    "Fans. Just to see the mess.",
  ],

  "open-someone-elses": [
    "Somebody left this here.",
    "Oh, this one has a name.",
    "Someone made this on purpose.",
    "Opening a stranger's homework.",
    "Let's see what they were thinking.",
    "This one's been sitting here a while.",
    "A gift from nobody in particular.",
    "I want to see the inside of this.",
    "Someone built this and walked away.",
    "Curious what happens after the first bit.",
    "Hands that aren't mine made this.",
    "Let's find out where it goes.",
    "I like the shape of the name already.",
    "This one looks like it has opinions.",
    "Untouched. Not for long.",
    "Someone's evening, folded up.",
    "Let's open it and see what falls out.",
    "A whole thing, apparently.",
    "I didn't make this. Better.",
    "Wonder if it ends where it starts.",
    "Somebody's Tuesday, saved.",
    "Let's poke at somebody else's idea.",
    "This has more parts than I expected.",
    "Interesting choice, whoever you were.",
  ],

  "open-viewer": [
    "Big version. Now.",
    "I want the whole thing at once.",
    "Small was fine. Small is over.",
    "Show me all of it.",
    "There's more of this somewhere.",
    "I've been squinting at a thumbnail.",
    "Open it up. Wide.",
    "The little one lied about the scale.",
    "Room for the whole shape now.",
    "I'd like it to take up everything.",
    "Enough previewing.",
    "Now the actual size.",
    "Something bigger is behind this.",
    "Give it the whole screen.",
    "I want to see the end of it.",
    "This deserves more room than that.",
    "Bigger. Not for any reason.",
    "Let it breathe a little.",
    "I keep only seeing part of it.",
    "Time to look at the real one.",
    "Full length. All of it.",
    "Whatever the large version is, that.",
    "I've built enough to want the big picture.",
    "There it is. Larger.",
  ],

  "overwhelmed": [
    "Somebody was busy.",
    "There's a lot happening here.",
    "Okay. That's a screen.",
    "I count too many things.",
    "Everything is available at once.",
    "No one told this thing to stop.",
    "Which of these is the important one.",
    "It's all just... out.",
    "That's more than I expected.",
    "Density.",
    "Someone believed in options.",
    "I don't know where to look first.",
    "This is a lot at eye level.",
    "Every corner has something in it.",
    "Nothing here is hiding.",
    "Where does the screen end.",
    "Somebody kept adding.",
    "I'd like a smaller version of this.",
    "Is any of this decorative.",
    "Too many corners.",
    "Half of these are probably the same thing.",
    "This layout has opinions.",
    "Feels like a cockpit.",
    "There's a lot to be unsure about.",
  ],

  "pause-to-look": [
    "That bit. Do that bit again.",
    "Something happened. I missed it.",
    "Stop. Back up a little.",
    "Was that on purpose?",
    "I want that frame.",
    "Pause there. No, one earlier.",
    "Something crossed something.",
    "Did it just skip a beat?",
    "Hold that.",
    "There. Whatever that was.",
    "I lost track around the middle.",
    "Not sure I saw that right.",
    "Freeze. Let me squint at it.",
    "That looked wrong in an interesting way.",
    "Something's off in the middle third.",
    "Go back. It did a thing.",
    "Slower. Much slower.",
    "Stop it right about here.",
    "I blinked at the worst time.",
    "Is that supposed to overlap?",
    "Halt. Something moved twice.",
    "That transition is hiding something.",
    "One frame. Just one.",
    "Pause. I have a question.",
  ],

  "point-it-out": [
    "{target}. I'm not touching it.",
    "someone press {target}.",
    "leaving {target} for whoever wants it",
    "{target} is unpressed. deliberately.",
    "I've been hovering {target} a while now",
    "hand's on {target}. not committing.",
    "{target}, then. any takers.",
    "not pressing {target}. no reason.",
    "{target} stays like that till someone decides",
    "you can have {target}",
    "{target} looks like a two-person job",
    "I got as far as {target}",
    "{target}. that's where I stop.",
    "curious about {target}. not curious enough.",
    "somebody finish this. {target}.",
    "{target} has been sitting there unbothered",
    "last thing left is {target}",
    "{target}, whenever one of you gets to it",
    "I'll let {target} be a surprise",
    "no idea what {target} does. still don't.",
    "{target}. free to a good home.",
    "hovering {target} like it's a decision",
    "I've decided {target} isn't mine",
    "{target} is right there",
  ],

  "reject-effect": [
    "Not this.",
    "Was it always doing that?",
    "I think I made it worse.",
    "Something's off. Possibly everything.",
    "No. Or maybe. No.",
    "Let me undo whatever that was.",
    "It looked better before. I think.",
    "That's a lot of something.",
    "Okay, that's enough of that.",
    "I don't trust it.",
    "Who asked for this.",
    "It's doing too much.",
    "Turning it back.",
    "This isn't it. Close, but no.",
    "Second thoughts. Third ones too.",
    "I liked the boring version.",
    "It's shouting.",
    "Was that better? That wasn't better.",
    "Off. For now.",
    "I've seen enough.",
    "Give me the plain one back.",
    "Something about it bothers me.",
    "Hmm. That's a choice.",
    "It's fighting the shape.",
  ],

  "scrub-back": [
    "Back up. Something happened there.",
    "I missed it the first time.",
    "Again, slower.",
    "Wait, go back.",
    "That part. Rewind to that part.",
    "Where did the hands go.",
    "Rewind. I was blinking.",
    "One more time from the top of that.",
    "Something crossed over and I looked away.",
    "Take it back about four beats.",
    "Too fast. Do it again.",
    "I want to watch the middle again.",
    "Back to before the turn.",
    "There was a moment. Find it.",
    "Rewind until it looks wrong again.",
    "Somewhere back there it changed direction.",
    "Not the start. Just before the good bit.",
    "Again. I'm not convinced.",
    "That happened and I have questions.",
    "Back up until the arms uncross.",
    "Play it backwards. See what that does.",
    "Two seconds earlier. There.",
    "Let it happen again.",
    "I looked down and lost it.",
  ],

  "try-practice": [
    "Oh, there's a lens in here.",
    "Something just started looking back.",
    "The room showed up in the corner.",
    "Two of us now.",
    "Let's put them side by side.",
    "I want to see it next to something that moves.",
    "A mirror. Slightly delayed.",
    "Whatever's in front of this, show me that.",
    "Can a thing watch itself do this?",
    "Hm. That's the room, isn't it.",
    "The diagram and the doing, at once.",
    "I'd like both at the same time.",
    "Now it's watching the floor.",
    "Half of this screen just became elsewhere.",
    "Nobody's in frame. Still worth opening.",
    "There it goes, pointing outward.",
    "A window, and it opens onto here.",
    "The drawing on one side, the real thing on the other.",
    "Interesting. It wants a body.",
    "I have a dot. That may not count.",
    "Let's see what it makes of the room.",
    "Something to compare against.",
    "The lens is doing its slow warm thing.",
    "Oh good, a second version.",
  ],

  "tune-effect": [
    "Turning this and seeing what gives.",
    "Small nudge first.",
    "This one's labeled. Doesn't help.",
    "Somewhere between too little and too much.",
    "Let's push it and find out.",
    "Halfway seems cowardly.",
    "Curious where the ceiling is.",
    "If I move this, something moves.",
    "Bit more. Bit more.",
    "The number goes up. Then what.",
    "Wondering if it's linear.",
    "Probably fine.",
    "Testing whether that was the important one.",
    "One slider at a time. Usually.",
    "I want to see it flinch.",
    "What happens at the far end.",
    "Nudging until it looks wrong.",
    "Might be nothing. Might be everything.",
    "Down first, then up, for science.",
    "Does it care about this at all?",
    "Slowly, so I can see it change its mind.",
    "This is where it either breaks or improves.",
    "All the way over, then back.",
    "Suspicious that nothing happened.",
  ],
};
