/**
 * Scopes 98.css under .retro-shell so it doesn't leak into the main app.
 *
 * Reads 98.css from node_modules, prefixes every selector with `.retro-shell`,
 * and writes the result to src/lib/features/retro/styles/98-scoped.css.
 *
 * Run: node scripts/scope-98css.cjs
 * Re-run if 98.css is updated (npm update 98.css).
 */
const postcss = require("postcss");
const fs = require("fs");
const path = require("path");

const INPUT = path.join(__dirname, "../node_modules/98.css/dist/98.css");
const OUTPUT = path.join(
	__dirname,
	"../src/lib/features/retro/styles/98-scoped.css",
);

const PREFIX = ".retro-shell";

/** Selectors that should NOT be scoped (they're global by nature). */
const SKIP_PREFIXING = new Set(["body", "html", ":root"]);

function prefixSelector(selector) {
	// Don't prefix pseudo-element selectors on their own (scrollbar etc.)
	// These need the prefix prepended to the whole thing
	const parts = selector.split(",").map((s) => s.trim());

	return parts
		.map((part) => {
			// Skip empty
			if (!part) return part;

			// Handle body — scope it to .retro-shell itself
			if (part === "body") return PREFIX;

			// Handle selectors starting with body (e.g. "body.foo")
			if (part.startsWith("body ")) return `${PREFIX} ${part.slice(5)}`;
			if (part.startsWith("body.")) return `${PREFIX}${part.slice(4)}`;

			// Handle pseudo-element scrollbar selectors
			if (part.startsWith("::-webkit-scrollbar")) {
				return `${PREFIX} ${part}`;
			}
			if (part.startsWith("::")) {
				return `${PREFIX} ${part}`;
			}

			// Skip global selectors that shouldn't be scoped
			const base = part.split(/[\s:.#[>+~]/, 1)[0];
			if (SKIP_PREFIXING.has(base)) return part;

			return `${PREFIX} ${part}`;
		})
		.join(", ");
}

async function main() {
	const css = fs.readFileSync(INPUT, "utf8");
	const root = postcss.parse(css);

	root.walk((node) => {
		if (node.type === "rule") {
			node.selector = prefixSelector(node.selector);
		}
	});

	const header = `/*
 * 98.css — Scoped under .retro-shell
 *
 * AUTO-GENERATED by scripts/scope-98css.cjs
 * Do not edit manually. Re-run the script if 98.css updates.
 *
 * Original: 98.css v0.1.21 (MIT) — https://github.com/jdan/98.css
 */\n\n`;

	const output = header + root.toString();
	fs.writeFileSync(OUTPUT, output);
	console.log(`Scoped 98.css written to ${path.relative(process.cwd(), OUTPUT)}`);
}

main().catch((err) => {
	console.error("Failed to scope 98.css:", err);
	process.exit(1);
});
