<script lang="ts">
  import { onMount } from "svelte";
  import { generatePropSvg } from "$lib/shared/animation-engine/services/svg-generator";

  interface ReviewFan {
    id: "fire-bare" | "fire-covered" | "lotus";
    name: string;
    note: string;
    preview: string;
    renderKey: "fan__fire_bare" | "fan__fire_covered" | "fan__lotus";
  }

  const fans: readonly ReviewFan[] = [
    {
      id: "fire-bare",
      name: "DoodleGrip Fire · bare",
      note: "Measured five-wick crown, curved outside rails, welded lattice, and DoodleGrip shell.",
      preview: "/images/props/build-previews/fan-fire-bare-complete.webp",
      renderKey: "fan__fire_bare",
    },
    {
      id: "fire-covered",
      name: "DoodleGrip Fire · covered",
      note: "The fitted crescent sleeve follows the real wick crown instead of replacing it with dots.",
      preview: "/images/props/build-previews/fan-fire-covered-complete.webp",
      renderKey: "fan__fire_covered",
    },
    {
      id: "lotus",
      name: "Home of Poi Medium Lotus",
      note: "Ten traced petal rails, Russian grip geometry, and five independently measured Kevlar rolls.",
      preview: "/images/props/build-previews/fan-lotus-bare-complete.webp?v=6",
      renderKey: "fan__lotus",
    },
  ];

  type MotionRenders = Record<
    ReviewFan["id"],
    { blue: string; red: string } | null
  >;

  let renders = $state<MotionRenders>({
    "fire-bare": null,
    "fire-covered": null,
    lotus: null,
  });
  let loadError = $state<string | null>(null);

  onMount(() => {
    const objectUrls: string[] = [];
    let active = true;

    function svgUrl(svg: string): string {
      const url = URL.createObjectURL(
        new Blob([svg], { type: "image/svg+xml;charset=utf-8" })
      );
      objectUrls.push(url);
      return url;
    }

    async function loadProductionRenders(): Promise<void> {
      try {
        for (const fan of fans) {
          const [blue, red] = await Promise.all([
            generatePropSvg(fan.renderKey, "#35a8ff", "dark"),
            generatePropSvg(fan.renderKey, "#ff334f", "dark"),
          ]);
          if (!active) return;
          renders = {
            ...renders,
            [fan.id]: { blue: svgUrl(blue.svg), red: svgUrl(red.svg) },
          };
        }
      } catch (error) {
        if (active) {
          loadError =
            error instanceof Error ? error.message : "The 2D render failed.";
        }
      }
    }

    void loadProductionRenders();
    return () => {
      active = false;
      objectUrls.forEach((url) => URL.revokeObjectURL(url));
    };
  });
</script>

<main class="review-page">
  <header>
    <p class="eyebrow">2D ↔ 3D fidelity gate</p>
    <h1>The same physical fans, flattened cleanly</h1>
    <p class="intro">
      The left side is the current 3D source. The right side is generated by the
      production 2D renderer, with motion color on the frame and physical
      materials preserved on the wicks and cover.
    </p>
  </header>

  {#if loadError}
    <p class="error" role="alert">{loadError}</p>
  {/if}

  <section class="fan-list" aria-label="Fire fan fidelity comparisons">
    {#each fans as fan (fan.id)}
      <article class="fan-card">
        <div class="card-heading">
          <div>
            <span
              >{fan.id === "lotus"
                ? "Traced vector build"
                : "Measured product build"}</span
            >
            <h2>{fan.name}</h2>
          </div>
          <p>{fan.note}</p>
        </div>

        <div class="comparison">
          <figure>
            <figcaption>3D source</figcaption>
            <div class="art-stage source-stage">
              <img src={fan.preview} alt="{fan.name} 3D source" />
            </div>
          </figure>

          <figure aria-busy={!renders[fan.id]}>
            <figcaption>Production 2D · blue / red</figcaption>
            <div class="art-stage two-d-stage">
              {#if renders[fan.id]}
                <img
                  src={renders[fan.id]?.blue}
                  alt="{fan.name} in blue motion color"
                />
                <img
                  src={renders[fan.id]?.red}
                  alt="{fan.name} in red motion color"
                />
              {:else}
                <span class="loading">Rendering measured artwork…</span>
              {/if}
            </div>
          </figure>
        </div>
      </article>
    {/each}
  </section>
</main>

<style>
  .review-page {
    min-height: 100dvh;
    padding: clamp(1rem, 3vw, 3rem);
    color: var(--theme-text, #f5f7ff);
    background:
      radial-gradient(
        circle at 50% -10%,
        color-mix(in srgb, var(--theme-accent, #7567dc) 22%, transparent),
        transparent 38rem
      ),
      #07080c;
    font-family: system-ui, sans-serif;
  }

  header,
  .fan-list,
  .error {
    width: min(100%, 92rem);
    margin-inline: auto;
  }

  header {
    padding-block: clamp(1rem, 3vw, 2.5rem);
  }

  .eyebrow,
  h1,
  .intro,
  h2,
  p,
  figure {
    margin: 0;
  }

  .eyebrow,
  .card-heading span {
    color: color-mix(in srgb, var(--theme-accent, #8d7ff0) 78%, white);
    font-size: max(0.75rem, var(--font-size-compact, 0.75rem));
    font-weight: 800;
    letter-spacing: 0.09em;
    text-transform: uppercase;
  }

  h1 {
    max-width: 16ch;
    margin-top: 0.35rem;
    font-size: clamp(2rem, 5vw, 4.5rem);
    line-height: 0.98;
    text-wrap: balance;
  }

  .intro {
    max-width: 63rem;
    margin-top: 1rem;
    color: var(--theme-text-muted, rgba(255, 255, 255, 0.68));
    font-size: max(0.9375rem, var(--font-size-min, 0.875rem));
    line-height: 1.6;
  }

  .error {
    margin-bottom: 1rem;
    padding: 0.8rem 1rem;
    color: #ffd6db;
    border: 1px solid rgba(255, 80, 100, 0.45);
    border-radius: 0.8rem;
    background: rgba(255, 50, 75, 0.1);
  }

  .fan-list {
    display: grid;
    gap: 1rem;
    padding-bottom: 4rem;
  }

  .fan-card {
    overflow: hidden;
    border: 1px solid var(--theme-stroke, rgba(255, 255, 255, 0.12));
    border-radius: clamp(1rem, 2vw, 1.5rem);
    background: color-mix(
      in srgb,
      var(--theme-panel-bg, #10121a) 94%,
      transparent
    );
  }

  .card-heading {
    display: grid;
    grid-template-columns: minmax(16rem, 0.72fr) minmax(20rem, 1fr);
    align-items: end;
    gap: 1rem 2rem;
    padding: clamp(1rem, 2.2vw, 1.6rem);
    border-bottom: 1px solid var(--theme-stroke, rgba(255, 255, 255, 0.1));
  }

  h2 {
    margin-top: 0.25rem;
    font-size: clamp(1.25rem, 2.5vw, 2rem);
    line-height: 1.1;
  }

  .card-heading p {
    color: var(--theme-text-muted, rgba(255, 255, 255, 0.62));
    font-size: max(0.875rem, var(--font-size-min, 0.875rem));
    line-height: 1.5;
  }

  .comparison {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  figure + figure {
    border-left: 1px solid var(--theme-stroke, rgba(255, 255, 255, 0.1));
  }

  figcaption {
    min-height: 2.75rem;
    padding: 0.8rem 1rem;
    color: var(--theme-text-muted, rgba(255, 255, 255, 0.58));
    border-bottom: 1px solid var(--theme-stroke, rgba(255, 255, 255, 0.08));
    font-size: max(0.75rem, var(--font-size-compact, 0.75rem));
    font-weight: 700;
  }

  .art-stage {
    position: relative;
    display: grid;
    min-height: clamp(13rem, 28vw, 25rem);
    overflow: hidden;
    place-items: center;
    background:
      radial-gradient(circle, rgba(117, 103, 220, 0.09), transparent 55%),
      #090a10;
  }

  .source-stage img {
    display: block;
    width: min(96%, 48rem);
    height: auto;
    object-fit: contain;
  }

  .two-d-stage {
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: clamp(0.35rem, 2vw, 1.5rem);
    padding: clamp(0.75rem, 2vw, 2rem);
  }

  .two-d-stage::after {
    position: absolute;
    inset-block: 15%;
    left: 50%;
    width: 1px;
    content: "";
    background: rgba(255, 255, 255, 0.08);
  }

  .two-d-stage img {
    display: block;
    width: 100%;
    max-height: clamp(11rem, 24vw, 21rem);
    object-fit: contain;
  }

  .loading {
    grid-column: 1 / -1;
    color: var(--theme-text-muted, rgba(255, 255, 255, 0.5));
    font-size: max(0.875rem, var(--font-size-min, 0.875rem));
  }

  @media (max-width: 48rem) {
    .card-heading {
      grid-template-columns: minmax(0, 1fr);
    }

    .comparison {
      grid-template-columns: minmax(0, 1fr);
    }

    figure + figure {
      border-top: 1px solid var(--theme-stroke, rgba(255, 255, 255, 0.1));
      border-left: 0;
    }

    .art-stage {
      min-height: clamp(12rem, 62vw, 19rem);
    }

    .two-d-stage img {
      max-height: clamp(10rem, 50vw, 17rem);
    }
  }
</style>
