export const CAMERA_DEFAULTS = {
	WALK_SPEED: 3.5,
	SPRINT_MULTIPLIER: 2.0,
	CROUCH_MULTIPLIER: 0.4,
	JUMP_VELOCITY: 5.0,
	GRAVITY: 9.81,
	TERMINAL_VELOCITY: -50,
	MOUSE_SENSITIVITY: 0.002,
	EYE_HEIGHT: 1.6,
	CROUCH_EYE_HEIGHT: 0.95,
	CAPSULE_HALF_EXTENT: 0.85,
	ROTATION_SMOOTHING: 8,
} as const;
