/**
 * The six elemental motifs — one per Vulcan Cave room, one per VTG category.
 *
 * The idea this harness exists to test (Austen, 2026-08-05): take a performer,
 * hide the avatar, hide the prop, and keep the effect. What is left is a trace
 * that moves through 3D space in that room's timing-and-direction modality and
 * nothing else — generated by the software rather than modelled by hand. Six
 * elements, six modalities, six signatures.
 *
 * Nothing here is new domain data. The sequences are the museum's own exhibit
 * sequences, already MCP-verified, one per category. The letter groups come
 * from the Flow Arts MCP (`get_letter_explanation`): Type 1 is organised by
 * VTG timing+direction as Split-Same (ABC), Together-Opp (DEF), Together-Same
 * (GHI), Split-Opp (JKL), Quarter-Opp (M-R), Quarter-Same (STUV).
 *
 * `defaultEffect` is a STARTING GUESS, not a decision. Every station's effect
 * is switchable in the harness, which is the whole point — the mapping from
 * element to effect is the open creative question, and it gets answered by
 * looking, not by arguing.
 *
 * ── The 3D coverage gap (measured 2026-08-05) ───────────────────────────────
 *
 * The effects registry lists sixteen effects. `EffectOrchestrator3D` — the one
 * that actually mounts inside `PerformerRig`'s effectsSlot — renders exactly
 * FOUR of them: `trails`, `led`, `charcoal`, `fire`. Everything else (goo,
 * bubbles, smoke, petals, sparkles, bloom, ghost, zap, ink, silk, animal,
 * pulse) has no renderer on that path; those emitters live in `EffectsLayer`,
 * which its own header marks as legacy and unmounted.
 *
 * So the candidate lists below are drawn from the four that exist in 3D. The
 * elemental character has to come from colour, palette and motion for now.
 * Giving Water an actual water effect in 3D is a porting job, not a config
 * change, and it is the single biggest lever on this whole idea.
 */

export interface ElementMotif {
  /** Vulcan Cave room id, so findings port straight into each room's graybox. */
  roomId: string;
  label: string;
  /** VTG category code as carried by CAVE_MODE_ROOMS. */
  category: "SS" | "SO" | "TS" | "TO" | "QS" | "QO";
  technicalMode: string;
  /** The Type 1 letter group for this category, per MCP. */
  letters: string;
  /** Key into MUSEUM_EXHIBIT_SEQUENCES. */
  sequenceId: string;
  /** Opening guess at the effect that reads as this element. Switchable. */
  defaultEffect: string;
  /**
   * The shortlist worth auditioning for this element. Kept to a handful so the
   * choice is a real comparison rather than a menu of sixteen. Trails is on
   * every list as the control: it shows the raw path with no elemental
   * character, which is the baseline every other option has to beat.
   */
  candidates: readonly string[];
  /** Room accent, used for the station label and the floor ring. */
  color: string;
  /** What the effect is being asked to evoke, in Austen's terms. */
  intent: string;
}

export const ELEMENT_MOTIFS: readonly ElementMotif[] = [
  {
    roomId: "cave-water",
    label: "Water",
    category: "SS",
    technicalMode: "Split-time / same-direction",
    letters: "ABC",
    sequenceId: "cave-water-seq-a",
    defaultEffect: "bubbles",
    candidates: ["bubbles", "goo", "trails", "led"],
    color: "#3a7fd9",
    intent: "A split-same circle drawn in water.",
  },
  {
    roomId: "cave-fire",
    label: "Fire",
    category: "SO",
    technicalMode: "Split-time / opposite-direction",
    letters: "JKL",
    sequenceId: "cave-fire-seq-dj",
    defaultEffect: "fire",
    candidates: ["fire", "charcoal", "led", "trails"],
    color: "#f97316",
    intent: "The one element whose effect already looks like itself.",
  },
  {
    roomId: "cave-earth",
    label: "Earth",
    category: "TS",
    technicalMode: "Together-time / same-direction",
    letters: "GHI",
    sequenceId: "cave-earth-seq-g",
    defaultEffect: "charcoal",
    candidates: ["charcoal", "trails", "led", "fire"],
    color: "#8a6a3a",
    intent: "Rock, or growing things. Coal and Petals are both worth a look.",
  },
  {
    roomId: "cave-air",
    label: "Air",
    category: "TO",
    technicalMode: "Together-time / opposite-direction",
    letters: "DEF",
    sequenceId: "cave-air-seq-dj",
    defaultEffect: "trails",
    candidates: ["trails", "led", "charcoal", "fire"],
    color: "#c8d8e8",
    intent: "Clouds and butterflies. Smoke, Silk and Petals are the candidates.",
  },
  {
    roomId: "cave-sun",
    label: "Sun",
    category: "QS",
    technicalMode: "Quarter-time / same-direction",
    letters: "STUV",
    sequenceId: "cave-sun-seq",
    defaultEffect: "led",
    candidates: ["led", "fire", "trails", "charcoal"],
    color: "#ffcf5c",
    intent: "Open question. Beam of light, or something living in the light.",
  },
  {
    roomId: "cave-moon",
    label: "Moon",
    category: "QO",
    technicalMode: "Quarter-time / opposite-direction",
    letters: "M-R",
    sequenceId: "cave-moon-seq",
    defaultEffect: "trails",
    candidates: ["trails", "led", "charcoal", "fire"],
    color: "#b8c4e0",
    intent: "Open question. Comet streaks, stars, moon dust.",
  },
];

/** Station spacing in metres. Wide enough that neighbouring traces don't read as one. */
export const STATION_SPACING = 5;

/** World position for station `i`, laid out as a straight line on Z = 0. */
export function motifPosition(index: number, count: number): { x: number; z: number } {
  const span = (count - 1) * STATION_SPACING;
  return { x: index * STATION_SPACING - span / 2, z: 0 };
}
