name = "tka-shortcode-redirect"
main = "shortcode-redirect.js"
compatibility_date = "2025-04-01"

routes = [
  { pattern = "tka.run/*", zone_name = "tka.run" }
]

[[kv_namespaces]]
binding = "SHORTCODES"
id = "c06e4b192f3c49f2a4e11cc44d012277"
